### ISSUE TITLE
Log xScale for large ranges doesn't trigger cursor

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1013]
**Describe the bug**
When using a log scale on the x axis with a large range something like `[1e-7, 10]`. The small values hover just fine but as you go to the larger values, the cursor does not find the indexed geometries.

**To Reproduce**
1. Go to https://codesandbox.io/s/adoring-leftpad-dnirp?file=/src/App.tsx
2. Drag your mouse from left to right along the line
3. Notice towards the right side, that tooltip does not find the points
4. Swap the commented and uncommented data
5. Notice the same effect at a larger order

**Expected behaviour**
The tooltip should know about log scale values and adjust the indexing accordingly. The buffer might be a fixed value that is not adjusted for the higher scales.

**Screenshots**
![Screen Recording 2021-02-04 at 12 39 PM](https://user-images.githubusercontent.com/19007109/106939897-7d8f8100-66e6-11eb-96f9-3712ba563291.gif)

> Notice it gets harder to trigger the tooltip as you go higher in magnitude, becoming impossible after a certain point.

**Comment by markov00** [comment]
fixed in #1258
