### ISSUE TITLE
Truncate labels for partition charts

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elastic-charts#1026]
When using the partition chart with the flame or icicle layout, text is hidden when it doesn't fit in the box. It would be great if we can configure the chart to truncate labels that are too long. As a reference, here's a screenshot from using real profiling data for the flamegraph:

![image](https://user-images.githubusercontent.com/352732/108086188-65b8e500-7076-11eb-8baf-7105924f7056.png)

**Comment by monfera** [comment]
Fixed by #1033
