### ISSUE TITLE
Text alignment is off for icicle/flame layouts

### ISSUE THREAD

**Issue by dgieselaar** [elastic/elastic-charts#1027]
In some cases, when using icicle/flame layouts, the text labels are vertically misaligned. Here's a reference screenshot:

![image](https://user-images.githubusercontent.com/352732/108086424-a3b60900-7076-11eb-9a0e-dc91b0c9c540.png)

Here's my config:

```
{
  fillLabel: {
    fontFamily: theme.eui.euiCodeFontFamily,
  },
  fontFamily: theme.eui.euiCodeFontFamily,
  minFontSize: 9,
  maxFontSize: 9,
  partitionLayout: PartitionLayout.icicle
}
```

**Comment by monfera** [comment]
Fixed by #1033
