### ISSUE TITLE
Re-position chart annotation when it is near the border

### ISSUE THREAD

**Issue by pheyos** [elastic/elastic-charts#1040]
**Is your feature request related to a problem? Please describe.**
The date label of the event rate chart in the ML revert model snapshot flyout does not look ideal when it is near the border of the chart:
![image](https://user-images.githubusercontent.com/1945390/109525592-f6011c00-7ab1-11eb-8521-384713bbd0e8.png)

See codesandbox repro here https://codesandbox.io/s/sad-pond-n2pqh?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/19007109/113899512-7f32ff00-9792-11eb-90e4-13fa3d03a8b3.png)

**Describe the solution you'd like**
Leave the small arrow where it is but re-position the text such that it is better readable / does not contain so many line breaks.

**Additional context**
In a [slack discussion](https://elastic.slack.com/archives/CFK9BJ248/p1614614308011200?thread_ts=1614610942.010700&cid=CFK9BJ248), it was suggested to reuse tooltip functionality to do this.

**Comment by nickofthyme** [comment]
Hey @pheyos this is now available in kibana `master` as of https://github.com/elastic/kibana/pull/98093.

You can now throw the squashed text content into the `markerBody` prop of the `LineAnnotation`. Here is an [example](https://elastic.github.io/elastic-charts/?path=/story/annotations-lines--advanced-markers) which looks like this in code...

https://github.com/elastic/elastic-charts/blob/62f8841822f82cbc1ce742defd46e0c11de1ff67/stories/annotations/lines/8_advanced_markers.tsx#L124-L132

Lmk if you can any questions or trouble with it. Thanks! 🙏
