### ISSUE TITLE
Fitted domain should apply to stacked domains

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1050]
**Describe the bug**
When using a stacked series and setting the y-axis `domain.fit` to `true`, the domain is _still_ locked to `0`.

**To Reproduce**
1. Go to https://codesandbox.io/s/cool-tree-42qto?file=/src/App.tsx
2. Comment on and off the `stackedAccessors` line
3. Notice the stacked series forces the baseline to be `0`, and the non-stacked series accurately fits the data to the dataset

**Expected behaviour**
Stacked data should be _fittable_

**Screenshots**

https://user-images.githubusercontent.com/19007109/109882424-7903ad00-7c3f-11eb-8669-2cf4015d19e7.mp4

**Version (please complete the following information):**
 - Elastic Charts: `master`

**Kibana Cross Issues**
https://github.com/elastic/kibana/pull/93352

**Checklist**

- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
I see this from a different point of view. We should allow fitting the data only for line series, nothing else.
This because: bar and area should always start at 0 baseline, no exception. Their height/area represents their value, and we should prevent truncations.

**Comment by markov00** [comment]
Removing the zero baseline for line series is fine in all cases.
Removing the zero baseline for area and ba is always wrong. The exception we are applying to log is more an exception to improve the rendering and reading of the chart for a particular data domain. We only know that there can be a `zero` when we use a log scale, so we are limiting the rendering to a similar, but very small, `zero-like` baseline. Applying domain fit to area or bar is not a good approach IMHO

**Comment by nickofthyme** [comment]
Won't fix per discussion with team over zoom. Main takeaways from the discussion:

- Area charts should always have a zero baseline
- Stacked log area charts don't make sense
- We should disallow log scales for area and bar charts
