### ISSUE TITLE
Ability to disable toggle visiblity behavior on legend items.

### ISSUE THREAD

**Issue by hbharding** [elastic/elastic-charts#1055]
**Is your feature request related to a problem? Please describe.**
We have charts in Observability that only ever plot 1 or 2 pieces of information. Users are able to click on a legend item to toggle the visibility of data. While this feature is useful when there are many pieces of data being shown (it allows the user to focus), it doesn't seem like it provides any value when the chart only has a single legend item.

**Describe the solution you'd like**
A way for developers to disable the toggle capability when it's not desired.

**Describe alternatives you've considered**
Consistency / expected behavior might be a concern. Some charts would allow toggling visibility (current default behavior), whereas other may not. How would a user know when this toggle behavior is available?

A simple solution could be to just remove this capability when there is only a single legend item. This behavior could apply to all chart types. If more than 1 legend item exists, then the toggle visibility feature would become available.

**Additional context**

<details>
<summary>See screenshots</summary>

![image](https://user-images.githubusercontent.com/847805/110016663-4dda9580-7cf3-11eb-82b0-16ef43285291.png)
![image](https://user-images.githubusercontent.com/847805/110016686-53d07680-7cf3-11eb-9659-733fe48c6aa5.png)

</details>

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests

**Comment by markov00** [comment]
Thank you @hbharding I think we can go with:
>A simple solution could be to just remove this capability when there is only a single legend item. This behavior could apply to all chart types. If more than 1 legend item exists, then the toggle visibility feature would become available.

The consistency issue created with that change is neglectable and is replaced by a better UX
