### ISSUE TITLE
[Docs] Incorrect dev server port number in README.md file

### ISSUE THREAD

**Issue by akashgp09** [elastic/elastic-charts#1059]
## Describe the bug

**The  elastic charts dev server runs on port : 9002** 

![Screenshot (331)](https://user-images.githubusercontent.com/55311336/110248804-e47bb080-7f98-11eb-9b83-ec3fc13bcbfa.png)

**This need to be fixed in the [README.md](https://github.com/elastic/elastic-charts/blob/master/README.md) file**

<img width="660" alt="Screenshot 2021-03-07 225639" src="https://user-images.githubusercontent.com/55311336/110249178-e9416400-7f9a-11eb-9958-7822194eb590.png">

**Comment by markov00** [comment]
Hi @akashgp09 thanks for reporting this, but it's not a bug. The default port number is `9001` but if you already have something on that port (like another instance of storybook) it will try and use the next available port in sequence.
Try to find what you have listening on port 9001, there can be probably an already running storybook or something else
