### ISSUE TITLE
[Legends] Align the legend item to the series shape

### ISSUE THREAD

**Issue by formgeist** [elastic/elastic-charts#1081]
# Summary

When using the Bubble chart you're able to change the shape for each series, but the legend item does not change from the dot.

Would the ideal to align the legend item dot to the shape.

<img width="1424" alt="Screenshot 2021-03-16 at 09 13 08" src="https://user-images.githubusercontent.com/4104278/111276882-1f848080-8638-11eb-92fd-49e2d76f4a90.png">

Here's an example of an already implemented chart in APM where it would be beneficial to have the legends be differentiable.

<img width="1093" alt="Screenshot 2021-06-23 at 11 25 59" src="https://user-images.githubusercontent.com/4104278/123072407-cdf94800-d415-11eb-8cab-6ceca7bf18ce.png">

**Comment by formgeist** [comment]
@markov00 Do you have any timeline for when this might be implemented? I imagine we'll make use of this a lot more in APM to differentiate our previous period time-series against the current by also adding a different stroke or shape to the series.

**Comment by markov00** [comment]
> @markov00 Do you have any timeline for when this might be implemented? I imagine we'll make use of this a lot more in APM to differentiate our previous period time-series against the current by also adding a different stroke or shape to the series.

Hey @formgeist we can put this into our next planning, probably it will be available before 7.15 FF

**Comment by formgeist** [comment]
@markov00 Thanks, much appreciated!
