### ISSUE TITLE
Remove debounce on resize for first render

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#109]
**Describe the bug**
There is a 200ms delay before you can get anything on the screen.
It's because the `chart-resizer`, that compute the chart parent size, has a `debounce` set to 200ms for any resize event. 

**To Reproduce**
1. Go to any chart
2. See the small delay between the page load and the rendering

**Expected behavior**
Rendering happens at the same exact time of rendering other contents

**Screenshots**
n/a

**Version (please complete the following information):**
 - OS: mac osx
 - Browser: chrome
 - Elastic Charts: master

**Additional context**
n/a

**Errors in browser console**
n/a

**Kibana Cross Issues**
n/a

**Checklist**
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
Closed by #229
