### ISSUE TITLE
Add chart type to chart label

### ISSUE THREAD

**Issue by myasonik** [elastic/elastic-charts#1098]
## Describe the bug
Each chart has a simple `aria-label="Chart"`. Next step is to add the chart type to it.

## Expected behavior
Examples include `aria-label="Bar chart"`, `aria-label="Bubble chart"`, etc

### Implementation notes
- If passing in labeling props is supported when this is implemented, the user supplied label should overwrite this

**Comment by rshen91** [comment]
Closed by #1104
