### ISSUE TITLE
Improvements on the way the values are depicted inside bar charts

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#1123]
**Is your feature request related to a problem? Please describe.**
We received some feedback from our users that the values inside bar charts do not render ideally in all cases. 

**Describe the solution you'd like**
Specifically, the problems identified are two:

- [x] #1234
- [x] we could give the option to the users to hide the white outline if it doesn't fit their charts styling

**Kibana Cross Issues**
Kibana issue [here](https://github.com/elastic/kibana/issues/97428)

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by ghudgins** [comment]
good discussion about this issue on https://github.com/elastic/kibana/issues/101573

**Comment by markov00** [comment]
@stratoula the following part of the request:
> we could give the option to the users to hide the white outline if it doesn't fit their charts styling

can be achieved with the `borderSize` option available in the `displayValue` style of the chart theme: 

```ts
export type DisplayValueStyle = Omit<TextStyle, 'fill' | 'fontSize'> & {
  offsetX: number;
  offsetY: number;
  fontSize:
    | number
    | {
        min: number;
        max: number;
      };
  fill:
    | Color
    | { color: Color; borderColor?: Color; borderWidth?: number } // borderWidth in pixel or
    | {
        textInvertible: boolean;
        textContrast?: number | boolean;
        textBorder?: number; // textBorder in pixel
      };
  alignment?: {
    horizontal: Exclude<HorizontalAlignment, 'far' | 'near'>;
    vertical: Exclude<VerticalAlignment, 'far' | 'near'>;
  };
};
```

**Comment by markov00** [comment]
Hi @stratoula I will close this issue as it looks like we have closed all the tasks. Please reopen and add any missing task to the list if any

**Comment by stratoula** [comment]
No Marco we are done with it! (at least for now) 🚀
