### ISSUE TITLE
How to best represent clipped y domains in line and area charts

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1129]
When a dataset domain is between `0` and `180` but the max domain is explicitly limited to `150` we treat the isolated points as if there is a discontinuity in the dataset by removing the points from being rendered like shown in the upper left corner below.

![mockup](https://aws1.discourse-cdn.com/elastic/original/3X/5/0/509ec7cc59e13a631209d2fe350e2982bed45103.jpeg)

Previously kibana (i.e. `vislib`) rendered these points as connected thus clamping the points that go beyond the max within the set domain.

![mockup](https://aws1.discourse-cdn.com/elastic/original/3X/c/f/cf3e6c193c0cbe1730c3cda4b671305c88cd476f.jpeg)

This issue is to discuss the best way to represent this scenario, as well as what options might be exposed to render one way or another.

See slack discussion [here](https://elastic.slack.com/archives/GQQQMNJ8M/p1618946087097200) and discuss post [here](https://discuss.elastic.co/t/kibana-visualize-a-value-greater-than-max-axis-extents-is-not-displayed-with-on-line-chart/269202).

Related issue https://github.com/elastic/elastic-charts/issues/1044

**Comment by nickofthyme** [comment]
### One option: ☝️ 

Render connecting lines to points outside of the domain and simply clip the lines. Could format lines differently to show discontinuity.

![image](https://aws1.discourse-cdn.com/elastic/original/3X/b/c/bcdb4cf50c5fac506867244af45f1ad602b7d43d.jpeg)

**Comment by markov00** [comment]
### Option ✌️



Render normally the lines (without using a different style), adds a small padding after the current max value and render a small annotation along the axis, like the one in this example, to describe that there is 'more' and something is clipped

![](https://www.carbondesignsystem.com/static/207c0e8b26945cd3f90c2e1ca9ba7f25/92c65/axislabel-break-2.png)

**Comment by markov00** [comment]
Thanks @waverly360 for your opinion, it definitely makes much more sense the way you described the extents than the way it works today.
The axis extends is basically the representation of a zoom action, where you just want to reduce and zoom in or out the current dataset.
@jgowdyelastic I've replicated your example here: https://codesandbox.io/s/sparkling-wildflower-10lxd if you switch between version 24.0.0 and 24.1.0 you will notice that in one the area is clipped (24.0) and in the other case the area is rendered as a set of orphan data points (24.1)
I will investigate further to understand exactly if that was a really wanted behaviour or not

**Comment by nickofthyme** [comment]
> If someone wants to filter out data that exceeds 80%, wouldn't it make more sense for them to add a filter specifically into their query for that?

@waverly360 This is true but you can only filter on documents, not on the aggregations.

**Comment by markov00** [comment]
> This is true but you can only filter on documents, not on the aggregations.

it's anyway not clear what happens and I'm pretty sure is not our task right now to filter on aggregation (at least not in that hidden way, but through a clear filter API)
