### ISSUE TITLE
[Tooltip] More interactive tooltip, for example to copy+paste the text

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#1143]
This is related to the overall [tooltip redesign](https://github.com/elastic/elastic-charts/issues/615). We got a request from a user to have tooltip that they can copy+paste from, which is currently not possible because the tooltip moves when the mouse moves. I don't have any specific proposal for how we can make this interaction happen, but maybe you all have some ideas on how we can do this?

Related to #615

**Comment by shaunmcgough** [comment]
Further info on the request from the user. They currently do screenshots of the tooltip whilst hovering on the area they want to share. The addition of a little icon on the tooltip that copied it's contents to the clipboard would be a nice way to solve their problem. Sharing a screenshot is not optimal. They really want to share the data as text.

**Comment by markov00** [comment]
Currently possible after the new tooltip redesign and the pinned ability of the tooltip
