### ISSUE TITLE
[Heatmap] Time scale type with a single row of data breaks the chart 

### ISSUE THREAD

**Issue by darnautov** [elastic/elastic-charts#1184]
**Describe the bug**
Passing a single row of data with a time scale on the X-axis breaks the chart. 

**To Reproduce**
Go to https://codesandbox.io/s/cool-sound-8j9m7?file=/src/App.tsx

> Notice by not setting the `xDomain` with a single values, causes the error below.

**Expected behaviour**
The chart is rendered with a single row of data 

**Version (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser: [e.g. chrome, safari] Chrome
 - Elastic Charts: [e.g. 1.0.1] latest

**Errors in browser console**
```
quantize.js:18 Uncaught RangeError: Invalid array length
    at rescale (quantize.js:18)
    at Function.scale.range (quantize.js:28)
    at Object.shapeViewModel (viewmodel.js:81)
    at Object.render (scenegraph.js:30)
    at geometries.js:42
    at resultFuncWithRecomputations (index.js:77)
    at index.js:70
    at index.js:30
    at index.js:84
    at index.js:30
```

**Comment by markov00** [comment]
I've lowered the priority because this issue has a workaround (set the minInterval in the xDomain)
