### ISSUE TITLE
Partition chart should pull from theme and spec not config 

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1185]
**Describe the bug**
The `config.width` and `config.height` in the partition chart, at least in the pie chart layout, are overwritten by the parentDimensions.

The first part where the `width` and `height` are overwritten is visible in the `getShapeViewModel` before merging the partial config.

The second place is in the `partitionMultiGeometries` where we compute the `chartWidth` and `chartHeight` as derived from the `marginedWidth/Height` (always coming from the `parentDimensions`). On the same function we should also check the `innerWidth/Height` that also comes from the `parentDimensions`

**To Reproduce**
1. Go to https://codesandbox.io/s/youthful-curran-egqkv?file=/src/App.tsx
2. Try to use `width`, `height` in the config, instead of the currently proposed workaround with margin/outerSizeRatio
3. The size of the pie will be always the size of the parent, no matter what value are used as width/height in the Config

**Expected behaviour**
We should respect the `config.width` and `config.height` parameters exposed by the `Partition` component. If we don't want that feature, we should remove them from the API.

**Version:**
 - Elastic Charts: 29.2.0

**Errors in browser console**
N/A

**Comment by ron-debajyoti** [comment]
I would like to take this up.

**Comment by markov00** [comment]
Hey @ron-debajyoti thanks again for your availability
I've chatted with @monfera about this issue and we decided that we should remove the `config.width` and `config.height` from the public API instead of letting the user specify these values.

If you are willing to work on It we are ok with that. You can probably do that by using `Omit` TS utility, but it's worth checking the alternatives.

**Comment by ron-debajyoti** [comment]
> Hey @ron-debajyoti thanks again for your availability
> I've chatted with @monfera about this issue and we decided that we should remove the `config.width` and `config.height` from the public API instead of letting the user specify these values.

Hey @markov00 thanks for the update. In that case, let me try to take up other open issues.
