### ISSUE TITLE
"Composite" annotations

### ISSUE THREAD

**Issue by smith** [elastic/elastic-charts#1200]
In APM we have annotations that are a line with a marker followed by a rectangle to mark the start of the alert and show its duration:

<img width="297" alt="CleanShot 2021-06-10 at 13 21 42@2x" src="https://user-images.githubusercontent.com/9912/121577199-e9645c00-c9ee-11eb-9d51-ecd65fe62612.png">

We have to implement this as two separate annotations, one for the line, and one for the rect. Seems like it would be better if we could treat is as a "composite" annotation, especially if we were able to show them in a legend (#555.)

**Kibana Cross Issues**

* elastic/kibana#96559

- [X] this request is checked against already exist requests
- [X] every related Kibana issue is listed under `Kibana Cross Issues` list
- [X] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
This could be implemented, in the first stage, just updating the current style options available, adding the ability to specify a border (border-left-right) and a few other options to the marker for example

**Comment by dej611** [comment]
Adding a +1 for Lens here as well.
Implementing threshold we've been hitting the same problem.

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
