### ISSUE TITLE
The gridline hides the horizontal axis 

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1203]
**Describe the bug**
Axis are rendered before rendering the grids.
This causes a rendering problem: the X-axis will be every time overwritten by the lowest horizontal grid line style that is always rendered on top of the axis line.

**To Reproduce**
1. Go to https://codesandbox.io/s/kind-fermat-hx7us?file=/src/App.tsx
2. The gridline is enabled, the axis line stroke color is set to black but the gridline covers the axis line

**Expected behavior**
The gridlines should be rendered before rendering the axis so that the axis is more prominent and can be styled correctly.

**Additional context**
A similar effect is also visible on the Y-axis where the horizontal grid lines are rendered on top, creating a dashed effect on the Y-axis line

**Screenshots**
<img width="718" alt="Screenshot 2021-06-14 at 11 19 27" src="https://user-images.githubusercontent.com/1421091/121869501-6733aa80-cd02-11eb-9c47-c298fb9dc292.png">

**Additional context**
A VRT should be added

**Comment by ron-debajyoti** [comment]
Hey @markov00 , I would like to take this up and try to solve this issue.

**Comment by markov00** [comment]
Hey @ron-debajyoti sure if you like to take that you are always welcome!
And thanks again for your contribution to the texture, it looks and works great!
