### ISSUE TITLE
[Charts] Annotations should have click handler 

### ISSUE THREAD

**Issue by alvarezmelissa87** [elastic/elastic-charts#1211]
**Is your feature request related to a problem? Please describe.**
When using the chart annotations, I am unable to hook into interactions with the annotation. 

**Describe the solution you'd like**
I would like to have an event handler (preferably click) that I can pass in so that I can easily trigger some other action from a click on the annotation. The handler I pass in would probably expect the annotation data as a parameter.

**Describe alternatives you've considered**
No alternatives I could find for the use case I'd like. 

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Target Release**
Would be great to get this in soon, if possible. 7.14 would be great but mindful it's a bit of a squeeze so 7.15 would be great, also. Thank you!

**Checklist**

Delete any items that are not applicable to this feature request.

- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by rshen91** [comment]
@alvarezmelissa87 What kind of annotation data would you like to have access to from within handler (if any)? Thanks!

**Comment by alvarezmelissa87** [comment]
Hi @rshen91  - so for `LineAnnotation` it should be `dataValue` and `details` and for `RectAnnotation` everything - `coordinates` and `details`. Thank you and please let me know if there's anything else I can help with!
