### ISSUE TITLE
[Heatmap] Scrollbars appear on container size change

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#1219]
**Describe the bug**
If a heatmap is configured to fill it's container element completely, changing the container size (e.g. by resizing the browser window), will change the size of the visible chart, but scrollbars will appear and the user can scroll into whitespace of the original size.

**To Reproduce**
1. Go to https://codesandbox.io/s/polished-snowflake-vwjqx
2. Reduce the browser height
3. A scrollbar appears

**Expected behaviour**
No scrollbar 

**Screenshots**
![heatmap_resize2](https://user-images.githubusercontent.com/1508364/123246354-fb152b80-d4e5-11eb-9106-3f5630c4f7da.gif)

It seems like the `echAnchorMainTooltip` element is keeping the element size:
<img width="560" alt="Screenshot 2021-06-24 at 12 02 41" src="https://user-images.githubusercontent.com/1508364/123246323-f5b7e100-d4e5-11eb-92a2-bdaae32b7e06.png">

**Version (please complete the following information):**
 - OS: macOS
 - Browser: Chrome 91
 - Elastic Charts: 30.2.0

**Additional context**
Can be seen in the Lens heatmap integration as well

**Kibana Cross Issues**
* https://github.com/elastic/kibana/issues/102036

**Checklist**

Delete any items that are not applicable to this issue.

- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
@flash I cannot reproduce this in Chrome nor Firefox with `30.2.0`. Could you confirm this?

https://user-images.githubusercontent.com/19007109/126665052-1bd1a8f5-529a-4bec-a180-16d8ec294ea5.mp4
