### ISSUE TITLE
[Heatmap] Add axes titles

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1221]
**Motivation / Problem**

*When* I am displaying data on a heatmap
*I need* to label the two dimensions of the heatmap 
*So I can* optionally provide additional context as to what the data is

**Describe the solution you'd like**
Expose optional axis labeling options in heatmap visualizations for upstream consumption 

**Describe alternatives you've considered**
None - there's no great workaround today

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/102036
https://github.com/elastic/kibana/issues/72390

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
One aspect that we don't consider much as part of the visualization is the title of the visualization itself.
Most of the time is enough to correctly describe the dimensions in play:

The monthly infection rate per Region/Age
![image](https://user-images.githubusercontent.com/1421091/124612065-4f1ef900-de72-11eb-8323-be5034ee2141.png)

Tshirt orders by color and size
![image](https://user-images.githubusercontent.com/1421091/124612186-6cec5e00-de72-11eb-806a-57c69a95fcbf.png)

In Kibana the title is actually only confided at the dashboard level, we can bring it back at the editing level. 
I don't think the title should change depending on dashboard, it depends on the data and the configuration, so it should stay the same everytime
