### ISSUE TITLE
Allow for using custom tooltip component

### ISSUE THREAD

**Issue by awkinley** [elastic/elastic-charts#1228]
**Is your feature request related to a problem? Please describe.**
While the default tooltip is generally perfectly time, there are cases where I would like more fine tuned control over the rendering, beyond what can be done with styling. So far as I can tell this is not an option that elastic charts currently provides.

**Describe the solution you'd like**
The ability to define a tooltip component for a chart would allow people full customization.

**Describe alternatives you've considered**
Other charting libraries provide this functionality, but elastic charts provides performance and features that those libraries do not. CSS styling can also be used to make some changes to a tooltips appearance, but this does not provide as much flexibility as a custom component could.

**Comment by nickofthyme** [comment]
We currently provide a `customTooltip` prop as of  to render any react component. This [story](https://elastic.github.io/elastic-charts/?path=/story/bar-chart--test-tooltip-and-rotation&knob-chartRotation=0&knob-stickTo=MousePosition&knob-Fallback%20Placements[0]=right&knob-Fallback%20Placements[1]=left&knob-Fallback%20Placements[2]=top&knob-Fallback%20Placements[3]=bottom&knob-tooltip%20type=vertical&knob-Boundary%20Element=default&knob-Custom%20Tooltip=true&knob-Tooltip%20offset=10&knob-Show%20axes=&knob-Show%20Legend=) shows an example of this.

The code would look something like...

```tsx
<Chart>
  <Settings
    tooltip={{
      customTooltip: () => (
        <div
          style={{
            padding: 10,
            height: 40,
            backgroundColor: 'blue',
            color: 'white',
          }}
        >
          My Custom Tooltip
        </div>
      ),
    }}
  />
</Chart>
```

![image](https://user-images.githubusercontent.com/19007109/124155215-df68d280-da5b-11eb-9fc0-4c0d95056c38.png)

We have yet to export the base component of our default tooltip. This would provide a way to match the existing styles of the tooltip but put any react component inside.

Is this issue ok to close or are you asking for something else?

**Comment by awkinley** [comment]
Alright great! That should solve my issue.
