### ISSUE TITLE
(a11y improvement & tooltip redesign) Add more semantic meaning to the tooltip if provided (goal)

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#1232]
**Is your feature request related to a problem? Please describe.**
This came up in PR https://github.com/elastic/elastic-charts/pull/1218#issuecomment-875733378. Using this issue to track and incorporate in the tooltip redesign. 

**Describe the solution you'd like**
In the new tooltip, if the bandLabels is provided in goal charts, the tooltip should also include some information for more context for users.

**Comment by markov00** [comment]
with the new bulletgraph I believe this become unnecessary, let's reopen this if someone asks for that specificity
