### ISSUE TITLE
Small multiple for gauges/bullet graph

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1235]
Add the ability to create small multiples for bullet graph.

Should implement chart title and description for small multiples, see #2002

**Kibana Cross Issues** 
* https://github.com/elastic/kibana/issues/118867

**Comment by gvnmagni** [comment]
Commenting only to confirm that we talked about this and we have a proper guide to follow

![iMac - 37](https://github.com/elastic/elastic-charts/assets/18484576/dc8b199e-79db-40ee-bf1f-509072bfb70b)
![iMac - 36](https://github.com/elastic/elastic-charts/assets/18484576/7dbc6cdd-e0f0-4479-89aa-b47741f7d96d)
![iMac - 35](https://github.com/elastic/elastic-charts/assets/18484576/50e3ca31-a9c0-40c6-a5e3-378aced8c7fc)
