### ISSUE TITLE
Add legend about bands/range with color picker

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1236]
**Is your feature request related to a problem? Please describe.**
related to TSVB/Visualize gauge replacement

**Describe the solution you'd like**
When displaying a bullet graph, the legend can be shown to display the various ranges values/color, allowing color picking.

**Describe alternatives you've considered**
to discuss:
- the bullet graph already shows a range of colors and their respective values, it looks redundant
- do we really need the color picking consistent and used only from the legend?

**Additional context**
related to TSVB/Visualize gauge replacement

**Comment by ghudgins** [comment]
do we _want_ legends on goal visualization? does it benefit with the new accessible values? could we wait for a shared legend feature and close this issue?

**Comment by rshen91** [comment]
Linking over https://github.com/elastic/elastic-charts/pull/1218#issuecomment-875733378 and https://github.com/elastic/elastic-charts/pull/1218#issuecomment-875974954

**Comment by nickofthyme** [comment]
@gvnmagni Do you think we should close this issue or do you see value in adding a legend to the new bullet design?

**Comment by gvnmagni** [comment]
The only useful way I can of this is when we have color ranges that stand for something, as we can see in the attached images (a quick mocukp), I think this is an edge case but I wouldn't drop completely the concept, I would like to be sure about this use first

<img width="730" alt="Screenshot 2023-11-09 at 10 59 47" src="https://github.com/elastic/elastic-charts/assets/18484576/dfc5ba01-c02c-40fd-b062-3a92496b4a97">

**Comment by markov00** [comment]
let's close this until we don't have a formal request for that
