### ISSUE TITLE
Auto-compute nice ticks for linear scales based on range

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1238]
**Is your feature request related to a problem? Please describe.**
related to TSVB/Visualize gauge replacement

**Describe the solution you'd like**
The ability to automatically compute a set of nice rounded ticks based on a range when using a linear bullet graph with no range bands

from original the issue: e.x. if `ticks` prop is not defined to detect automatically based on an interval (currently it renders default ticks from 0 to 100)
  
  ![image](https://user-images.githubusercontent.com/31325372/93488454-0f047f00-f90f-11ea-973e-e806767e6bc8.png)

**Describe alternatives you've considered**
Using a manual configuration for the ticks, in this case, can be tedious and error-prone.

**Additional context**
related to TSVB/Visualize gauge replacement

**Comment by ghudgins** [comment]
from @mbondyra's review just now, could we also consider special options for ticks on bands (in addition to auto tick placement over the full range...independent of bands)
