### ISSUE TITLE
[Legend] Improved readability on long legend values

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1245]
_Problem with long values_
**When** my data is long and varies mostly at the end of the value
**I need** to be able to see the ends of long values
**So I can** see the differences in my legend values from the front _and_ the back of the values

**Describe the solution you'd like**
Many options:
 - ~Option that lets you choose to middle `...` instead of at the end (as it is today)?~
 - Selected approach: Option multi-line legends

There are other solutions we shouldn't look into in the scope of this issue: https://github.com/elastic/elastic-charts/issues/963 Focus on a responsive solution (we should still do the resize issue too as that satisfies interactivity cases...just not as a solution to this issue)

**Describe alternatives you've considered**
There are none, makes lines with multiple series hard to read

**Additional context**
Screenshots on this issue: https://github.com/elastic/kibana/issues/41418
TSVB related issue: https://github.com/elastic/kibana/issues/102327
Related problem on dropdowns: https://github.com/elastic/kibana/issues/103701

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by ghudgins** [comment]
we selected multi-line legends as the approach because it 1) works really well with resizing #963 2) it works very well on horizontal legends (right / left) and 3) it enables future table legends. We also found issues with middle `...` - the most notable was the copy/paste not working correctly which was an original requirement

**Comment by nickofthyme** [comment]
Testing for center `...` solution...

Option 1 - [demo](https://codesandbox.io/s/legend-center-truncate-lhtbi)

separates legend labels at an index

![Screen Recording 2021-07-14 at 01 15 54 PM](https://user-images.githubusercontent.com/19007109/125845850-cc873f42-1e63-463b-b786-aea1cdfd7692.gif)

Causes line breaks when copying.

```
cloudfla
re.com - direct-cdn - y2
cloudfla
re.com - indirect-cdn - y1
```

Option 2 - [demo](https://codesandbox.io/s/legend-center-truncate-coping-6dgcg?file=/src/styles.css)

The same as option 1 with separating legend labels at an arbitrary index and uses `user-select: none` on split strings with a separate adjacent full string element. Thus the copied text is the full invisible text.

![Screen Recording 2021-07-15 at 02 32 30 PM](https://user-images.githubusercontent.com/19007109/125847086-0b231f58-0418-4281-a19c-51d90a463de7.gif)

Resulting copy is like this...

```
cloudflare.com - direct-cdn - y2
cloudflare.com - indirect-cdn - y1
cloudflare.com - indirect-cdn - y2
```

> I'm not sure if this trick works in all browsers but Chrome supposedly had a related bug for this as mentioned [here](https://stackoverflow.com/a/53675297/6943587)
