### ISSUE TITLE
[a11y] legend loses focus after closing its popover 

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#1266]
**Describe the bug**
When opening the legend popover and then closing it, the focus is lost (see video below)

**Expected behaviour**
The focus should go back to the popover handle.

**Screenshots**
in Kibana:
https://user-images.githubusercontent.com/4283304/126983142-90d5e0d4-d9a1-4be0-a9a8-202f6648b804.mp4

in Storybook:
https://user-images.githubusercontent.com/4283304/126983155-9a389ef9-3567-4a09-86e4-d635d98ddb8a.mp4

**Version (please complete the following information):**
Chrome, master

**Kibana Additional context**
Found when checking https://github.com/elastic/kibana/pull/106374

**Comment by ghudgins** [comment]
@rshen91 can we close this?

**Comment by rshen91** [comment]
There is one edge case that isn't yet handled in https://github.com/elastic/kibana/pull/115066#issuecomment-963319913 but I think it's ok to close this issue for now 👍🏻
