### ISSUE TITLE
Stacked bar charts do not render correctly with Positive / Negative Values 

### ISSUE THREAD

**Issue by bvader** [elastic/elastic-charts#1280]
**Describe the bug**
Stacked bar charts do not render correctly with Positive / Negative Values 
Also see Discuss [Here](https://discuss.elastic.co/t/how-to-create-stacked-bar-chart-with-negative-values/280169)

**To Reproduce**
Add the sample data below
Create a Non-Stacked and Stacked Lens Visualizations
Observe Correct Non-Stacked Bar Chart
Observer Incorrect Stacked Chart 

**Expected behaviour**

**Screenshots**

**Version (please complete the following information):**
 - Browser: [e.g. chrome, safari]
 - Elastic Charts: [e.g. 1.0.1] 7.13.4, 7.14.0-SNAPSHOT

Sample Data 
```
DELETE discuss-pos-neg

PUT discuss-pos-neg/
{
  "mappings": {
    "properties": {
      "category" : {"type": "keyword"},
      "value" : {"type": "float"}
    }
  }
}


POST discuss-pos-neg/_doc
{
      "category" : "10-20",
      "value" : 32
}

POST discuss-pos-neg/_doc
{
      "category" : "10-20",
      "value" : -45
}


POST discuss-pos-neg/_doc
{
      "category" : "20-30",
      "value" : 64
}

POST discuss-pos-neg/_doc
{
      "category" : "20-30",
      "value" : -23
}

POST discuss-pos-neg/_doc
{
      "category" : "30-40",
      "value" : 57
}

POST discuss-pos-neg/_doc
{
      "category" : "30-40",
      "value" : -33
}

GET discuss-pos-neg/_search
```

Non Stacked Chart Looks Correct 

<img width="2042" alt="Screen Shot 2021-08-02 at 6 06 03 AM" src="https://user-images.githubusercontent.com/15572155/127866741-505d6635-caba-467d-a22d-586eb1f72389.png">

Stacked Chart is Not Correct. It should look the same as above bu on the same line / category. 

<img width="2056" alt="Screen Shot 2021-08-02 at 6 06 15 AM" src="https://user-images.githubusercontent.com/15572155/127866781-f8257250-6fa4-42eb-86ba-f7ae5e209b3b.png">

**Comment by nickofthyme** [comment]
See reproduction [codesandbox](https://codesandbox.io/s/icy-architecture-g6jx1?file=/src/App.tsx)

**Comment by nickofthyme** [comment]
@monfera @markov00 what do you think the solution is here?

It seems like the only way to achieve the stacked result is to group the bars by polarity to not occlude other positive bars.

![image](https://user-images.githubusercontent.com/19007109/130140982-8c72c780-8220-4865-b234-715e43d62853.png)

**Comment by dej611** [comment]
More examples from this cross Kibana issue:


<img width="1090" alt="Screenshot 2021-11-09 at 19 08 36" src="https://user-images.githubusercontent.com/924948/140980617-c776ba32-8578-467e-bc53-f705f21873f1.png">
<img width="1092" alt="Screenshot 2021-11-09 at 19 08 45" src="https://user-images.githubusercontent.com/924948/140980621-8446edd2-6ed5-4580-883c-94124507ae15.png">

<img width="1096" alt="Screenshot 2021-11-09 at 19 12 50" src="https://user-images.githubusercontent.com/924948/140980811-8b15188e-a094-44b3-8b6a-ee9f90987a23.png">
<img width="1101" alt="Screenshot 2021-11-09 at 19 12 57" src="https://user-images.githubusercontent.com/924948/140980816-1bd488dc-6bf7-472f-82a7-9141b0bf08bf.png">

<img width="1091" alt="Screenshot 2021-11-09 at 19 12 04" src="https://user-images.githubusercontent.com/924948/140980693-1fae71b6-2c23-4ee3-ae81-cd0f43c88de2.png">
<img width="1096" alt="Screenshot 2021-11-09 at 19 12 13" src="https://user-images.githubusercontent.com/924948/140980701-805a610f-7e1c-4a04-8b13-ad640db021de.png">


https://github.com/elastic/kibana/issues/118066
