### ISSUE TITLE
Axis line covers cursor line

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1283]
**Describe the bug**
When using an `AreaSeries` or `LineSeries` the axis line appears to cutoff the cursor line on hover.

**To Reproduce**
1. Go to https://codesandbox.io/s/upbeat-shirley-rjqtm?file=/src/App.tsx

**Expected behaviour**
Cursor line appears above the axis line

**Screenshots**

https://user-images.githubusercontent.com/19007109/128219348-b3ddd428-2b6f-4c12-bd1c-65c4f9726073.mp4

**Additional context**

**Comment by markov00** [comment]
I don't understand why this happen only on some specific cases like yours, and not in examples like https://elastic.github.io/elastic-charts/?path=/story/line-chart--discontinuous-data-points&globals=theme:light

**Comment by flash1293** [comment]
It seems like this is happening for gridlines as well: https://github.com/elastic/kibana/issues/113719#issuecomment-948229126
