### ISSUE TITLE
[legend] top and bottom legend position doesn't work well with new truncate setting

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#1312]
Recently we added an option to truncate the legend in all Visualize, TSVB and Lens editors. It means that the user can 
- choose not to truncate their legend at all
- truncate their legend items between 1 to 5 lines

When user chooses a legend position `top` or `bottom`, the space taken by the legend is around 1.5 lines. Which was fine before, because the shade effect indicated that space is scrollable. I think it's fine for 1 line or not-truncated line, but as we give an option to truncate from 1 to 5 lines, maybe we could in these cases expand this space and show full truncated strings.  

<img width="535" alt="Screenshot 2021-08-19 at 11 12 02" src="https://user-images.githubusercontent.com/4283304/130046371-61500b3e-39a9-4c2b-b13a-31f53b37cc81.png">

https://user-images.githubusercontent.com/4283304/130046376-7e0b1614-5745-4d38-b5e7-ed0c39710b4a.mp4

**Comment by nickofthyme** [comment]
Yeah it seems that with a single value, like you show, the grid styles are not ideal. We could use a single row when there is only one value which would fix this singular case.

Are you thinking there is also an issue when there are multiple items in the legend? In such a case what would your solution be?
