### ISSUE TITLE
Improve time to release

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1321]
The current release action runs the following steps:
1. yarn build
2. yarn lint
3. yarn prettier:check
4. yarn test
5. yarn semantic-release

The steps `2`, `3` and `4` are already executed:
a) before merging a PR into `master`
b) when a new commit is merged into master (not sure about this, but looking at the commit in github there is always a status check)

We can reduce the time to release if, during the `release action`, we check and wait for the green status on the last commit on `master`. This will reduce the time having to execute only steps `1` and `5` 

Something like this action could be used in the release action: https://github.com/marketplace/actions/wait-on-check

cc @nickofthyme

**Comment by nickofthyme** [comment]
closed by 15a3941a716c922e7d53c3369cf093b739f30914
