### ISSUE TITLE
Series sorting missed in legend

### ISSUE THREAD

**Issue by sulemanof** [elastic/elastic-charts#133]
**Describe the bug**
Sorting of series is not working properly in legend

**To Reproduce**
1. Create a chart (use the TSVB as an example)
2. Group it by terms (select small amount of terms, that needed for rendering the same labels)
3. Choose an another type of sorting (`descending` -> `ascending`)
4. See that colors of series shuffled in different way in the legend, but labels stayed on the same position

**Expected behavior**
Labels should also change its position

**Screenshots**
![sorting_issue](https://user-images.githubusercontent.com/31325372/55274444-78db3400-52e9-11e9-96a5-3d9e53358863.gif)

**Version (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 73
 - Elastic Charts: 3.4.4

**Additional context**

**Errors in browser console**
If applicable, add any console error.

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by emmacunningham** [comment]
related to #143 (currrently legend is not associated with any values & there is no explicit sorting of the order of the legend items)
