### ISSUE TITLE
Dark mode doesn't change legend text color

### ISSUE THREAD

**Issue by sulemanof** [elastic/elastic-charts#139]
**Describe the bug**
When using `DARK_THEME` in settings component, labels in legend remain dark:
![image](https://user-images.githubusercontent.com/31325372/55335424-b84d8000-54a3-11e9-8348-3ccf061288da.png)

**To Reproduce**
1. Create any chart
2. Change a background to a dark color
3. Pass  `DARK_THEME` into settings (`<Settings theme={DARK_THEME} />`)
4. See, that labels in the legend remain dark

**Expected behavior**

**Screenshots**

**Version (please complete the following information):**
 - Elastic Charts: 3.4.5

**Additional context**

**Errors in browser console**
If applicable, add any console error.

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
@sulemanof the darkmode setting should be tested together with the Kibana dark theme as well.
Because the legend will use the EUI color schema configured in Kibana, you should enable the dark theme in the Kibana Settings, refresh the browser page and use the `theme={DARK_THEME}` prop.
