### ISSUE TITLE
Axis domain fit option to include also annotation's data

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1411]
**Is your feature request related to a problem? Please describe.**
While working on the new threshold feature in Lens, using the annotation components from this library, we found the need to use an automatic fit that would include also annotations in the domain calculation.

**Describe the solution you'd like**
Having a `fit` option to fit the data in the chart, including the annotation one.

**Describe alternatives you've considered**
Doing it manually on consumer side.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/112795
https://github.com/elastic/kibana/issues/129240

**Comment by flash1293** [comment]
@markov00 Fixing this would allow us to get rid of a bug (https://github.com/elastic/kibana/issues/129240) as well as removing some custom logic: https://github.com/elastic/kibana/blob/072fe63c0b326f6dfd0215cda648c982f4b6bee8/src/plugins/chart_expressions/expression_xy/public/components/xy_chart.tsx#L351
