### ISSUE TITLE
Support for RTL text

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1432]
**Is your feature request related to a problem? Please describe.**
I'd like to allow a way to support RTL text in canvas to match the behavior in the tooltip.

**Describe the solution you'd like**
Manually set `canvas` [`dir`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir) attribute according to locale.

**Comment by dej611** [comment]
There's also the canvas `dir` attribute (which has wider browser support): https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/dir
