### ISSUE TITLE
Interactions: onElementClick or onElementOver

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#1437]
Opening this issue for discussion, in #1428, I went with feature parity with the cartesian charts and have `onElementClick` _or_ `onElementOver` in partition charts lead to the pointer cursor versus default cursor. 

Is it misleading for a hover-only action to have a pointer cursor vs when there is a clickable action? Is there more context in how consumers want their pointers that might answer this? Thanks!

For example the screen recording below has an element _over_ listener however it has no element _click_ listener and it looks like it does.

https://user-images.githubusercontent.com/19007109/138120183-25bcb1bd-4095-441b-a126-193613bbaaa1.mp4

**Comment by markov00** [comment]
@gvnmagni what do you think? what pointer should we use if we just want to listen to an hover event, but we don't have a click action configured?

**Comment by gvnmagni** [comment]
I don't know about specific behaviour that we should follow but I agree that it's a bit misleading to have a pointer cursors if it's not linked to any onClick event.

Typically one thing that it's used is to leave the classic cursor while changing slightly one graphic feature as it is right now with the bars which get a little lighter.

I would personally suggest to just remove the fact that onHover the cursor became a pointer and I'll leave it as it is.

**Comment by nickofthyme** [comment]
Yeah I agree. We have implicit actions driven by hover in addition to the slight shading and highlighting on hover we also update legend values and non of these have a pointer visible.

**Comment by nickofthyme** [comment]
Does any other chart type have this same functionality, like heatmap? The PR just fixed this on xy.
