### ISSUE TITLE
Align start of week to ISO 8601 to match Elasticsearch

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1465]
**Is your feature request related to a problem? Please describe.**
Elastic-charts currently renders Sunday as the starting day of week which is inconsistent with the binning logic in Elasticsearch. Until localization support is configurable, this should be aligned

**Describe the solution you'd like**
Update elastic-charts to use [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) starting day of week (Monday) 

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
If I'm not wrong this is how it already works in charts, @monfera can confirm this.
We probably discuss about that but without checking the actual code.
From what I can see and test the actual code shows the start of the week from Monday, as desired.
In particular that behaviour is configured here:
https://github.com/elastic/elastic-charts/blob/0228e433075772a787602edea243b635757dc5bc/packages/charts/src/chart_types/xy_chart/axes/timeslip/rasters.ts#L252-L275
where at line 263 you can see that the we are creating weekly rasters only if the dayOfWeek is 1 that match with Monday in the luxon library world https://moment.github.io/luxon/api-docs/index.html#datetimeweekday
