### ISSUE TITLE
Configurable starting day of week

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1466]
**Is your feature request related to a problem? Please describe.**
Different cultures have different starting days of week that don't match the one standard we currently visualize in time series visualizations. 

**Describe the solution you'd like**
Enhance configuration to support starting day of week. (for the consumer of this change) This would need to be coupled with query time offset functions in Elasticsearch to match binning to this visual display option for starting day of week.

Once supported, allow darker week raster lines in time axis

**Kibana Cross Issues**
 - https://github.com/elastic/kibana/issues/66148

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
