### ISSUE TITLE
[Partition] Link label text color parameter passed is ignored

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1469]
**Describe the bug**
While the `textColor` parameter is still accepted as valid for the `linkLabel` configuration object, its value is overwritten internally to the best "contrast" color against the container background color.

While the aim sounds nice, in Kibana charts embeddable cannot have a background color as Canvas requires them to be styleable somehow, so the background color is currently set to `undefined`/`transparent`. This leads to manually compute the `textColor` programmatically in Lens, and we land on the point above.

**Expected behaviour**
Respect the passed value for `textColor`.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/116777

**Checklist**

Delete any items that are not applicable to this issue.

- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
I'll verify this is fixed in https://github.com/elastic/elastic-charts/pull/1402.
