### ISSUE TITLE
Jest not reporting type errors locally

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#148]
**Is your feature request related to a problem? Please describe.**
In the course of #147, the SeriesSpec was updated to include a required `hideInLegend` prop which should have cause some TS compiler errors, but did not locally.  They did, however, surface when the CI ran when the PR was submitted.

**Describe the solution you'd like**
Consistency between local and CI TS compiler responses.

**Describe alternatives you've considered**

**Additional context**

**Kibana Cross Issues**

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Can be caused by some jest cache. I usually run `yarn jest --clearCache`.
maybe it was caused by branch switching between PRs

**Comment by emmacunningham** [comment]
@markov00 ahhh that was it, thank you!
