### ISSUE TITLE
[Bullet] Add vis affordance for out of bound values

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1497]
**Is your feature request related to a problem? Please describe.**
When I define a metric based on dynamic data
And I am using a static min/max
I need an affordance for my vis that tells me when my value has exceeded my predefined min/max
And I need to still be able to see the vis (in case this happens "overnight" as the data changes)

**Describe the solution you'd like**
@gvnmagni might have ideas and can add here

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests

**Comment by gvnmagni** [comment]
A first solution for this issue will come with the new design. I believe it can still be improved, but at least it is going to be explicit from now on

![iMac - 11](https://github.com/elastic/elastic-charts/assets/18484576/056482e6-7c5a-42a1-9db7-5fc6466e6c4e)
