### ISSUE TITLE
Add a "Current time marker" feature to new charts

### ISSUE THREAD

**Issue by Avinar-24** [elastic/elastic-charts#150]
Like in the issue https://github.com/elastic/kibana/issues/26459 it would be nice to know that new charts have an opportunity to display a marker with current timestamp between the past and the near future.

Like this:
![image](https://user-images.githubusercontent.com/16738889/55620630-00bab580-57a4-11e9-89f2-a61a48dd3101.png)

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/26459

**Checklist**
- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
@Avinar-24 thanks for the request. I think you can already achieve this using an Annotations, we just delivered yesterday this feature and it's available starting from  `3.6.0` https://github.com/elastic/elastic-charts/pull/126

**Comment by markov00** [comment]
@emmacunningham could you check if it's possible to disable the tooltip, because I don't think we have any tooltip when hovering over the time marker in vislib

**Comment by emmacunningham** [comment]
@Avinar-24 With the merge of #154, you should now be able to disable the tooltip hover state by adding `hideTooltips={true}` to the `LineAnnotation` spec, so that the annotation for the current time will not show anything on hover.

**Comment by markov00** [comment]
@Avinar-24 please close this issue if release 3.8.0 solve your request

**Comment by markov00** [comment]
@Avinar-24 any news about that?

**Comment by Avinar-24** [comment]
@markov00 The issue depends on elastic/kibana#33558 and that issue also depends on the charts roadmap. But as I see new version of charts has been delivered with necessary functionality and it must speed the progress up. Updates will come soon. Thanks.

**Comment by markov00** [comment]
Closing as this is achievable with a LineAnnotation as written here https://github.com/elastic/elastic-charts/issues/150#issuecomment-480868529
