### ISSUE TITLE
[Bullet] Title position options

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1507]
**Is your feature request related to a problem? Please describe.**
The horizontal title is not using space efficiently when displaying a single bullet

**Describe the solution you'd like**

Ideas:
 - Allow the client to control where the title goes
 - Ensure, when doing #1235, that the horizontal option is available (as it will more efficiently use the space)

**Describe alternatives you've considered**
No known workarounds

**Additional context**
![image](https://user-images.githubusercontent.com/5465514/143896954-a088e04a-af81-44f6-8acb-94ea25e580dc.png)

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

CC @gvnmagni

**Comment by gvnmagni** [comment]
I believe the design update that is going to be implemented will automatically solve this issue

![iMac - 12](https://github.com/elastic/elastic-charts/assets/18484576/f102a043-2f93-4e53-93b1-f68540bc3141)
