### ISSUE TITLE
[Goal] when `actual` overflow maximum band, the chart is colored to green

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#1509]
When `bandFillColor` function is undefined and the `actual` is bigger than `bands`, the range is painted in green (the bigger the actual , the darker green it is). 

Here's where I reproduced this bug: https://codesandbox.io/s/busy-herschel-oy7u2?file=/src/App.tsx

**Comment by markov00** [comment]
Hi @mbondyra this actually is not a bug, but our default configuration when the prop is missing.
If you don't configure a `bandFillColor` prop we will use a green color scale by default. 
That goes from your min value to your max value (computed as the min and max of `[base, actual, target, ...ticks, ...bands]` We recently changed how we compute the min and max value and now we added a mandatory domain min and max props that will solve also the darkening of that band color https://github.com/elastic/elastic-charts/pull/1637.

For other situation we cover them with some defaults:
- If you provide the `band` array then we should fill it with something, and in this case is our default color scale
- if you don't provide the `band` array nor the `bandFillColor` we provide one by default
- if you provide an empty array for bands, we will not display any band.

I've added a point here https://github.com/elastic/elastic-charts/issues/1648 to double check our default values in the bullet graph
