### ISSUE TITLE
[Waffle] Calculating values for Legend items not working well for some cases.

### ISSUE THREAD

**Issue by alexwizp** [elastic/elastic-charts#1512]
**Describe the bug:**
This issue was based on https://github.com/elastic/kibana/pull/119339#issuecomment-981584962

**Summary:**
<img width="297" alt="Screenshot 2021-11-29 at 13 20 44" src="https://user-images.githubusercontent.com/4283304/143867178-bc8b6325-8662-4f92-a471-c68f4d4a9e9a.png">
I cannot make sense of this legend vs tooltip information. The tooltip says there's 4 records in range 0.0$, but the legend says 0.0$ 0. Am I missing something or is there a bug?
<img width="795" alt="Screenshot 2021-11-29 at 13 22 14" src="https://user-images.githubusercontent.com/4283304/143867404-dc011f7d-4974-4890-b15a-a5c42a49d354.png">

I see that it happens if value is `0`

**Comment by markov00** [comment]
that's odd, I can clearly spot that the `0` is even not styled as the other texts:
<img width="427" alt="Screenshot 2021-12-02 at 13 36 06" src="https://user-images.githubusercontent.com/1421091/144423154-50ff8729-73da-4e56-8f59-13086762d43d.png">

Checking the DOM, that `0` is not on the `extra` parameter, but something added to the DOM.
@rshen91 can you please take a look here?
I can't reproduce it directly within elastic charts storybook. I'm trying with a dataset that, within Lens shows that issue but not in charts only
```
data={[
          [0, 1161],
          [20, 1391],
          [40, 519],
          [60, 519],
          [80, 119],
          [100, 73],
          [120, 8],
          [140, 24],
          [160, 10],
          [180, 1],
          [200, 6],
          [340, 1],
          [400, 1],
          [420, 1],
          [1080, 1],
        ].map((d) => [`${d[0].toFixed(2)}$`, d[1]])}
```

**Comment by rshen91** [comment]
<img width="691" alt="Screen Shot 2021-12-27 at 10 05 34 AM" src="https://user-images.githubusercontent.com/20343860/147486818-1c6fdcd1-80a4-4854-97a4-0028f6ecde0f.png">

Confirming what Marco saw earlier - digging in the kibana code base to see what's overriding the legend item extra parameter 👀

**Comment by rshen91** [comment]
Ok I got this to be reproduced on the elastic charts side whew!
