### ISSUE TITLE
[Waffle] Cannot enforce proper visual sorting to float values

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1516]
**Describe the bug**

Even enforcing a data sorting with the `sortPredicate` prop there is some local issue with contiguous blocks as shown in the picture:

<img width="1118" alt="Screenshot 2021-12-01 at 17 14 47" src="https://user-images.githubusercontent.com/924948/144440884-6c368b47-f9d0-4ffd-aa3c-74c86d9f6c58.png">

The value represented by the violet blocks is smaller than the one of the previous pink block, but yet its size is bigger.

**Expected behaviour**

I'd say that having two contiguous values V1 and V2, if V1 > V2 then the visual representation of V2 cannot be bigger than the one from V1.

**Comment by ghudgins** [comment]
@monfera will provide some details about how the rolling rounding can cause these situations. This is a function of the waffle vis and is why we put the warnings about large breakdowns in the vis editor.

**Comment by ghudgins** [comment]
details about why this happens are listed here - https://github.com/elastic/elastic-charts/pull/1255#issue-944802845

we don't think we can solve this problem as it is working as intended. 

we will create an issue for limiting top values & filters for waffle to mitigate this
