### ISSUE TITLE
[Waffle] Blocks should be sorted by value

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1517]
**Describe the bug**

The current logic for block placement in the Waffle chart seems to rely only on the native data order, which looks often like a random criteria:

<img src="https://user-images.githubusercontent.com/924948/143276160-1e5520e7-7d42-45f8-aa4e-663aa9ba7ffc.png" />

The current workaround is to use the the `sortPredicate`, but I think it still makes sense to make a by-value sorting the default behaviour, with the possibility to override with the prop.

**Comment by markov00** [comment]
fixed in https://github.com/elastic/elastic-charts/pull/1510
