### ISSUE TITLE
[Gauge] allow the tooltip value to be formatted

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#1521]
Either by sharing tickFormatters or adding their own formatter.
<img width="702" alt="Screenshot 2021-12-09 at 16 27 50" src="https://user-images.githubusercontent.com/4283304/145425406-f56e31fd-b64e-41c3-b4c1-d0a37d8e0c08.png">

**Comment by markov00** [comment]
We can probably add a `valueFormatter` just for that
