### ISSUE TITLE
Cluster node performance (storage, heap and CPU)

### ISSUE THREAD

**Issue by cristina-eleonora** [elastic/elastic-charts#1536]
**Is your feature request related to a problem? Please describe.**

Deployment  administrators need to know how their Elasticsearch cluster is doing, performance wise. For each cluster node, HW wise, there are 3 parameters that matter:
- JVM memory pressure (heap)
- CPU usage
- Storage allocation

And we need to find a **visual way to represent that**.

Right now, we show the last 2 parameters in cloud, under the `Instances` section of a deployment. The layout isn't very visual and it's overwhelming the user with information that isn't necessary or useful, until you have a problem with the node. 

<img width="1345" alt="Screenshot 2021-12-23 at 09 52 48" src="https://user-images.githubusercontent.com/44808440/147214729-7c56ba92-f307-410d-8f1b-6df1e50a6417.png">

**Describe the solution you'd like**

We'd need a 3 parameter component per node, that shows heap, CPU usage and storage. 
A cluster can have between 1 node and tens of nodes, so it needs to scale well. 

Ideally, the node viz should also be able to show the overall health of each node, which can be: 
- `healthy` 
- `stopped routing requests` 
- `unhealthy`

High CPU usage does not make a node unhealthy, nor does high JVM memory pressure. 

<img width="980" alt="Screenshot 2021-12-24 at 11 41 12" src="https://user-images.githubusercontent.com/44808440/147346034-bbc2f3ae-57f4-4290-89e7-916bb1565b88.png">

Each parameter should be actionable. 

I'd like to give users the filters for:
- node types
- node health
- deciding which parameters they want to see.

I'm not married to this idea and am very open to different explorations 🙂 

**Describe alternatives you've considered**

Now showing the name of the node, and have it display on hover: 

<img width="700" alt="Screenshot 2021-12-23 at 15 16 15" src="https://user-images.githubusercontent.com/44808440/147252472-0c1eb4bb-28b2-416e-aec3-571445271afb.png">

**Additional context**
Inspiration

| 1 | 2 | 3 | 
|--|--|--|
| <img width="478" alt="Screenshot 2021-12-22 at 14 36 35" src="https://user-images.githubusercontent.com/44808440/147221065-63316f18-14b3-402f-90d1-e5a9b98ed3e7.png"> | <img width="447" alt="Screenshot 2021-12-23 at 10 43 12" src="https://user-images.githubusercontent.com/44808440/147221710-b4fc6d38-3161-4ccb-8cd6-88551c07ca2a.png"> | <img width="285" alt="Screenshot 2021-12-23 at 10 41 20" src="https://user-images.githubusercontent.com/44808440/147221736-15ee75ba-74f8-4259-b727-68d601e2eaed.png">|

**Comment by ghudgins** [comment]
here's a similar discuss post of someone trying to do APM inventory vis from a dashboard and getting hung up on how to do it - https://discuss.elastic.co/t/how-to-create-birds-eye-visualization-in-kibana/290628/

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
