### ISSUE TITLE
Heatmap axis does not account for formating

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1558]
**Describe the issue**
When creating a heatmap which uses formatted axis labels, if the formatted string is longer than the original string label, the axis size is not recomputed.

**To Reproduce**
1. Go to https://codesandbox.io/s/kind-wood-gmko1?file=/src/App.tsx
2. Toggle on and off the `yAxisLabelFormatter` prop 
3. Notice the truncation of the axis labels with `...`

**Expected behaviour**
The formatted string labels are used to size the axes.

**Screenshots**

![Screen Recording 2022-01-19 at 11 16 35 AM](https://user-images.githubusercontent.com/19007109/150181084-aa2bb81d-0097-4224-9f60-32581769cbea.gif)

**Version (please complete the following information):**
 - Elastic Charts: `latest`

**Comment by markov00** [comment]
You are right, the current implementation doesn't consider the label formatting logic :(
