### ISSUE TITLE
XY Annotations

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1579]
### Summary

This meta issue tracks annotations in XY elastic-charts and the phasing to improve the functionality 

This form of annotations is often used on time series visualizations to show event data which can help to understand possible cause and effect between multiple datasets.

### Planned issues
Create/replace with issues:
 - range annotations - formal support in charts
 - hover adds opacity on other annotations
 - tooltip support for annotations (https://github.com/elastic/elastic-charts/issues/2384)
--- ^^ ga (re)release ^^ ---
 - annotation text - overlap support in charts 
 - minimap annotations display option (separate from line vis)

Related Kibana meta issue: https://github.com/elastic/kibana/issues/119240

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
