### ISSUE TITLE
[Goal] Full circle is cut off when container is resized

### ISSUE THREAD

**Issue by Kunzetsov** [elastic/elastic-charts#1598]
## Problem description

While trying to replace the `vislib` gauge with the goal from the `elastic-charts`, it has been found the further issue.

If the `full circle` has been drawn and its container has been resized, the bottom of the circle is cut off and a lot of space on the top is left.

### Circle angle configuration

```js
const angleStart = Math.PI / 2;
const angleEnd = -(Math.PI + Math.PI / 2);
```

### Current behavior

https://user-images.githubusercontent.com/22456368/154477843-d2478554-278d-44af-b00d-101374b9c7d5.mov

## Expected behavior
After the resizing, the circle should be in the middle of the container and should be resized according to the new size of the container.

---

**Version:**
 - Elastic Charts: 43.1.1

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by markov00** [comment]
See my request here: https://github.com/elastic/elastic-charts/issues/1599#issuecomment-1046954325

**Comment by Kunzetsov** [comment]
![Screenshot 2022-02-21 at 16 56 59](https://user-images.githubusercontent.com/22456368/154979562-8d4fd9ad-bb93-4eb3-b36d-a276a37ce72d.png)


```ts
export const Example = () => (
  <Chart>
    <Settings baseTheme={useBaseTheme()} />
    <Goal
      id="spec_1"
      subtype={subtype}
      base={0}
      target={260}
      actual={280}
      bands={[200, 250, 300]}
      ticks={[0, 50, 100, 150, 200, 250, 265, 280]}
      tickValueFormatter={({ value }: BandFillColorAccessorInput) => String(value)}
      bandFillColor={({ value }: BandFillColorAccessorInput) => bandFillColor(value)}
      labelMajor=""
      labelMinor=""
      centralMajor="280 MB/s"
      centralMinor=""
      angleStart={Math.PI / 2}
      angleEnd={-(Math.PI + Math.PI / 2)}
    />
  </Chart>
);
```

**Comment by markov00** [comment]
it looks strage (with a padding on the top), can you please check this link https://elastic.github.io/elastic-charts/?path=/story/goal-alpha--full-circle&globals=theme:light

**Comment by Kunzetsov** [comment]
@markov00, about cutting the bottom: https://codesandbox.io/s/festive-yalow-d1rsik?file=/src/App.tsx

**Comment by Kunzetsov** [comment]
@markov00, here is a difference:

your example:
```ts
      angleStart={Math.PI + Math.PI / 2}
      angleEnd={-Math.PI / 2}
 ```
 
my example:

```ts
      angleStart={Math.PI / 2}
      angleEnd={-(Math.PI + Math.PI / 2)}
```

**Comment by markov00** [comment]
oh that's interesting thanks, I will take a look and see what is going on there

**Comment by Kunzetsov** [comment]
@markov00, thanks a lot)

**Comment by markov00** [comment]
the issue is caused by a wrong calculation of the saggitta introduced here: https://github.com/elastic/elastic-charts/pull/1413
@nickofthyme can you please take a look and see why those different angles are not working nicely?
