### ISSUE TITLE
[Goal] Resizing limitations.

### ISSUE THREAD

**Issue by Kunzetsov** [elastic/elastic-charts#1599]
## Problem description

While trying to replace the `vislib` gauge with the goal from the `elastic-charts`, it has been found the further issue.

The `goal` chart has limitations on its maximum size.

### Current behavior

https://user-images.githubusercontent.com/22456368/154481512-ea9daa67-f9e3-477a-a60a-be0712f85e8d.mov

## Expected behavior

After the resizing of the container, the `goal` chart should be resized without any limitations.

https://user-images.githubusercontent.com/22456368/154482261-dc2641a1-58b0-44bb-bf4f-08ed9f210998.mov

---

**Version (please complete the following information):**
 - OS: macOS Big Sur, v11.6.1
 - Browser: chrome, Version 97.0.4692.99 (Official Build) (x86_64)
 - Elastic Charts: 43.1.1

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by markov00** [comment]
@Kunzetsov this is actually strange and looks like not an issue with the elastic-charts, but with the style of the container.
I've tried locally in our storybook, and the parent can be reduced to a very small size keeping the chart within its center
<img width="458" alt="Screenshot 2022-02-21 at 15 41 35" src="https://user-images.githubusercontent.com/1421091/154977017-c9728f48-4480-49d3-88d4-7537e2271a18.png">

Taking a look at your image and recording it looks like the chart has been pushed down a bit from the center of the rendering panel: see the alignment here for example
<img width="889" alt="Screenshot 2022-02-21 at 15 44 35" src="https://user-images.githubusercontent.com/1421091/154977415-8b4e4662-2fbd-477a-b292-3ef98c445143.png">

Please can you double check the CSS style of the chart and make sure the parent doesn't have any padding/marging/flexing for its children?

**Comment by Kunzetsov** [comment]
@markov00, sure, I can do that.

**Comment by markov00** [comment]
Sorry @Kunzetsov my comment was related to the other issue, this is about the max size, not the min
I will check the max size and will be back https://github.com/elastic/elastic-charts/issues/1598

**Comment by markov00** [comment]
I've double checked internally and we have an internal limiter on the size:
```
const referenceCircularSizeCap = 360; // goal/gauge won't be bigger even if there's ample room: it'd be a waste of space
const referenceBulletSizeCap = 500; // goal/gauge won't be bigger even if there's ample room: it'd be a waste of space
```
I think we can remove that limit, or configure them in the theme.
As written in the comment, having such big charts is actually a waste of space and the sizing should be limited on the canvas/lens/visualize/dashboard side or at least the user should be educated with good practices

**Comment by markov00** [comment]
@Kunzetsov (cc @flash1293) We are going to expose these limit parameters in the `theme` but we highly discourage changing them to something more extreme. Due to the two little pieces of information rendered on the goal chart and its circular nature, increasing its size above the suggested params will become a big waste of space and a disproportioned chart in your dashboard.

**Comment by flash1293** [comment]
Makes sense @markov00 - we can make sure to only use it for the legacy charts (not for Lens).
