### ISSUE TITLE
[Goal] Small-multiples details

### ISSUE THREAD

**Issue by Kuznietsov** [elastic/elastic-charts#1601]
## Feature description

- It should be added one common label for all small multiples.
- The `centralMajor` label should be filled by the bucket value by default.
- Chart with small-multiples should support three types of alignment: automatic, vertical and horizontal.

### Common and `centralMajor` label values  
![Image 17 02 2022 at 16 23](https://user-images.githubusercontent.com/22456368/154501344-4f4d361b-0e96-4f38-9fbf-ebd43db2a9e0.jpeg)

### Alignment (automatic)
![Screenshot 2022-02-17 at 16 24 58](https://user-images.githubusercontent.com/22456368/154501658-ea7908f4-6c1a-45a1-aca8-7e03bf358b2e.png)
![Screenshot 2022-02-17 at 16 25 30](https://user-images.githubusercontent.com/22456368/154501749-8843eee9-03f5-490a-88ee-39271ae14455.png)

---

**Version (please complete the following information):**
 - OS: macOS Big Sur, v11.6.1
 - Browser: chrome, Version 97.0.4692.99 (Official Build) (x86_64)
 - Elastic Charts: 43.1.1

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by nickofthyme** [comment]
@gvnmagni I think we close this, the only outstanding item would be the option to add a **common** label for rows and columns as we do for xy charts and other.
