### ISSUE TITLE
[Goal] Outline for the goals of the white color.

### ISSUE THREAD

**Issue by Kunzetsov** [elastic/elastic-charts#1602]
## Problem description

While trying to replace the `vislib` gauge with the goal from the `elastic-charts`, it has been found the further issue.

There is a known bug with goals, colored in the white color. There is a workaround for this edge case - applying the outline to the chart. Here is an example of the usage in vislib:

![Screenshot 2022-02-17 at 16 37 03](https://user-images.githubusercontent.com/22456368/154503930-ac4a8676-91d3-4620-b1cb-3fa50e02f2a2.png)
![Screenshot 2022-02-17 at 16 37 18](https://user-images.githubusercontent.com/22456368/154503975-b3af2e9d-7f9d-4b6e-ac4e-2d4bb838531a.png)

## Feature request

Could you, please, implement this behavior or provide the standardized workaround for such an edge case (with the idea of supporting legacy visualizations, created in the previous versions of the Kibana).

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by markov00** [comment]
@Kunzetsov @stratoula as defined in our chat, we should never use such low contrast colors in our charts.
My suggestion is to revise the color scales increasing the contrast in the color scales edges.
