### ISSUE TITLE
[Goal] Scale coloring.

### ISSUE THREAD

**Issue by Kunzetsov** [elastic/elastic-charts#1603]
## Problem description

While trying to replace the `vislib` gauge with the goal from the `elastic-charts`, it has been found the further issue.

`Vislib` contains the functionality of coloring ticks (scale) by the color of the band. Could you, please, provide such a feature?

### Example: 

![Screenshot 2022-02-17 at 16 49 37](https://user-images.githubusercontent.com/22456368/154506416-39ea38f3-92af-4c9a-88f1-d8160eda639b.png)

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by markov00** [comment]
@Kunzetsov @stratoula there is a major difference between the vislib gauge and the elastic-charts one:
the color scale in the elastic-chart is always visible and present in the background, and this removes the need of rendering an additional colored line-scale + ticks right below/internally to the gauge.

The `actual` value is rendered with the use of the internal "black" bar that shows at what level the current chart is
<img width="355" alt="Screenshot 2022-02-21 at 11 48 03" src="https://user-images.githubusercontent.com/1421091/154940504-b9086c6c-0701-42c0-92b0-2951730d9d22.png">

I think we can remove completely that "show scale" concept from the UI. Such thin line combined with the not so great color patterns provided by default (in particular with the lowest values in the various color scales) is an accessibility killer. Just take a look at the yellow in the example screenshot. Instead, having always the scale in the background will increase the accessibility in reading the ranges.

**Comment by stratoula** [comment]
I am fine with that. Let's disable it with a tooltip as we are doing on the heatmap. Something like
<img width="400" alt="image" src="https://user-images.githubusercontent.com/17003240/154976638-3622333a-bd7b-4566-8ca4-28e82f51537b.png">

and see if the users complain.
