### ISSUE TITLE
[Goal] Extra-space between the labelMinor/major and horizontal bullet

### ISSUE THREAD

**Issue by Kuznietsov** [elastic/elastic-charts#1604]
## Problem description

While trying to replace the `vislib` gauge with the goal from the `elastic-charts`, it has been found the further issue.

There is a lack of space between labelMajor/labelMinor and horizontal bullet. _For now, it is added extra spaces to labels, but expected to be a native behavior of the chart to have a margin between labels and the chart_.

### Current behavior

![Screenshot 2022-02-18 at 10 05 24](https://user-images.githubusercontent.com/22456368/154642782-9ac4d3ae-42eb-439e-a454-3406704c01a7.png)

### Expected behavior

![Screenshot 2022-02-18 at 10 06 11](https://user-images.githubusercontent.com/22456368/154642865-3f28f62b-d5f6-4c1b-9986-1c5581465274.png)

---

Kibana Cross Issues:
- https://github.com/elastic/kibana/issues/118867

**Comment by gvnmagni** [comment]
The design update that is going to be implemented for this chart will deprecate this issue

![iMac - 12](https://github.com/elastic/elastic-charts/assets/18484576/bab8c993-3dcf-424a-b017-0ec35e753de8)
