### ISSUE TITLE
[axis] time axis minute / second notation is confusing to some users

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1614]
**Is your feature request related to a problem? Please describe.**
Some users are interpreting the time axis minute / second notation as other units (like degrees or imperial feet / inches) 

Conflicting formats: 
 - Prime symbol https://en.wikipedia.org/wiki/Prime_(symbol) 
 - Imperial feet (`'`) and inches (`"`) https://discuss.elastic.co/t/discover-histogram-changed-to-use-inches-from-timestamps/298438/5?u=marco_liberati
 - "i'm only accustomed to those meaning seconds and minutes _in longitude and latitude_"

**Describe the solution you'd like**
Display options and/or improved tick formatting that doesn't conflict

**Describe alternatives you've considered**
None

**Comment by markov00** [comment]
https://github.com/elastic/kibana/issues/131117

**Comment by markov00** [comment]
This was fixed and we are not showing anymore the minutes and seconds with `'` and `''`
