### ISSUE TITLE
[Annotations] Reduce opacity of non-hovered annotations

### ISSUE THREAD

**Issue by gvnmagni** [elastic/elastic-charts#1625]
**Is your feature request related to a problem? Please describe.**
Large number of annotations can clutter the visualization and could be hard to loo at the chart when there are too many of them 

![Frame 10](https://user-images.githubusercontent.com/18484576/158194824-dc721f6f-dece-4003-996b-dc3441f246cc.jpg)

**Describe the solution you'd like**
In order to improve chart readability when interacting with annotations, it would be great to reduce opacity of annotations that are not selected/hovered (image shows a test with 0.1 opacity)

![Frame 11](https://user-images.githubusercontent.com/18484576/158195038-35afab4d-7240-4bdb-b340-0248a1894c0d.jpg)
_[images are made purely to explain the concept]_

**Comment by nickofthyme** [comment]
Thanks for opening this @gvnmagni already started working on this.

Should be apply this same effect to rectangular annotations as well or just line annotations?

**Comment by gvnmagni** [comment]
> Thanks for opening this @gvnmagni, I already started working on this.
> 
> Should we apply this same effect to rectangular annotations as well or just line annotations?

I would apply to them as well, all annotations (of any kind) but the one selected get lighter

**Comment by nickofthyme** [comment]
Ok thanks and lastly, should this apply across all annotations such that hovering on a line annotation lightens all other annotations lines or rectangles? Or should the lines be grouped separate from the rectangle annotations, regarding the hover state?

**Comment by gvnmagni** [comment]
> Ok thanks and lastly, should this apply across all annotations such that hovering on a line annotation lightens all other annotations lines or rectangles? Or should the lines be grouped separate from the rectangle annotations, regarding the hover state?

I would apply this across all annotations, no separate grouping
