### ISSUE TITLE
Stack area and bar series independently of each other

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#1631]
**Is your feature request related to a problem? Please describe.**
Right now it's possible to end up with area and bar series which are stacked on top of each other.

**Describe the solution you'd like**
elastic-charts should handle this case by stacking the area and bar series independently of each other

**Describe alternatives you've considered**
This can be handled as part of the spec as well, but as this configuration is considered bad practice, it shouldn't be possible to configure it in the first place.

**Additional context**
<img width="1255" alt="Screenshot 2022-03-01 at 14 23 18" src="https://user-images.githubusercontent.com/924948/156177131-50d81a55-112d-4640-8768-2b9888eb7ea4.png">

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/126586

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
I don't think this is something that should be fixed on the elastic charts side.

The solution here would be to group all the bars/areas and split them into their own group using `groupId` to define separate `Axis` specs. Doing this in elastic charts would require us to assume the preference of the user if they want multiple axes or to ignore the defined `stackAccessor`, either is a bold assumption.

The task of splitting the specs to separate axes can be difficult if you want the separated axes to share the same domain extents. I opened https://github.com/elastic/elastic-charts/issues/2519 to track this request.

**Comment by markov00** [comment]
I think we probably need to reconsider this. definitely Lens should block this behaviour, but we should also not provide an option for that.
