### ISSUE TITLE
[Axis] The new time axis displays wrong text for the dates with 1s

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#1633]
**Describe the issue**
On the new time axis there are cases that the dates with 1s are displayed wrongly. For example 1th of March instead of 1st of March.

**To Reproduce**
1. Initialize kibana locally
2. Click on Lens
3. Create a bar chart with the flights dataset
4. Use a 30 days timespan
5. Check the x axis

<img width="1725" alt="image" src="https://user-images.githubusercontent.com/17003240/160394122-511c204a-6662-4dd9-b0b1-76f4c481ba2f.png">

you can see the 21th here

If you change the timespan to 7 days you can see that is displayed correctly
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/17003240/160394214-7f0174a1-e5c0-46e6-8acc-b868b28b10ba.png">

**Expected behaviour**
It should be 1st in all cases

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/128504

**Checklist**
- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

**Comment by nickofthyme** [comment]
Created codesandbox repro [here](https://codesandbox.io/s/charming-beaver-4gdxpq?file=/src/App.tsx)
