### ISSUE TITLE
[Bullet] improve style and defaults

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1648]
The current bullet graph style (but also the goal/gauge one) can be improved to increase the readability in various cases.

Some example of style improvements:
<img width="1058" alt="Screenshot 2022-04-13 at 18 11 43" src="https://user-images.githubusercontent.com/1421091/163224478-085ebab6-28ae-47a0-9e35-6272dc1dda4e.png">

Other possible improvements:
- [ ] better default: (should we keep the `labelMinor` `unit` default?, should we change/remove the default green band scale)?

**Comment by nickofthyme** [comment]
A request from eui was to also control the `font-weight` of the titles or at least reduce it by `~200`.
