### ISSUE TITLE
EUI ColorPicker issues due to CSP

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#165]
**Describe the bug**
Looks like the merge of 56d67aa9e610945a3614dcf1a0a77c7cc42e547a is causing issues with EUI ColorPicker functionality.

**To Reproduce**
1. Go to Stylings story
2. Notice that though the bars have the correct color, the dot next to the legend item is black on Firefox.  Additionally on all browsers, the color picker when open does not render correctly.

**Expected behavior**
Dot next to legend item should match color of elements in chart.  Color picker should show full color range when open.

**Screenshots**
Firefox:
<img width="758" alt="image" src="https://user-images.githubusercontent.com/452850/55972750-f3387c00-5c38-11e9-8727-22a05bb2c758.png">

<img width="265" alt="image" src="https://user-images.githubusercontent.com/452850/55974044-ac985100-5c3b-11e9-813d-ffcc7c5679eb.png">

Chrome:
<img width="917" alt="image" src="https://user-images.githubusercontent.com/452850/55972767-fdf31100-5c38-11e9-90fd-c842023daf54.png">

<img width="262" alt="image" src="https://user-images.githubusercontent.com/452850/55974077-be79f400-5c3b-11e9-9bf7-c6e129159512.png">

**Version (please complete the following information):**
 - OS: Mac OS X
 - Browser: Firefox for color dot issue, all for open ColorPicker issues
 - Elastic Charts: 3.10.0

**Additional context**

**Errors in browser console**
Firefox:
<img width="350" alt="image" src="https://user-images.githubusercontent.com/452850/55972921-4f9b9b80-5c39-11e9-9396-c834dd1afff8.png">

Chrome:
none

**Kibana Cross Issues**
N/A

**Checklist**
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
mmm you are right, in the past i've noticed it. 
Still a good thing: the policy is restricting the tooltip picker from its 'illecit' use (see https://github.com/elastic/eui/pull/1472) and I think this needs to be addressed on `EUI` or we need to add specific rule for that

**Comment by cchaos** [comment]
FYI: EUI 11.3 replaced the color picker external library with a completely custom component: https://github.com/elastic/eui/pull/1914

**Comment by markov00** [comment]
I'm closing this issue because of the new color picker. We will add it back directly from a kibana wrapper
