### ISSUE TITLE
Support for Network Diagram charts

### ISSUE THREAD

**Issue by superermiao** [elastic/elastic-charts#1740]
Add support for new [Network Diagram](https://datavizcatalogue.com/methods/network_diagram.html) chart type as defined below.

> Description
> Also known as Network Graph, Network Map, Node-Link Diagram.
> 
> This type of visualisation shows how things are interconnected through the use of nodes / vertices and link lines to represent their connections and help illuminate the type of relationships between a group of entities.
> 
> Typically, nodes are drawn as little dots or circles, but icons can also be used. Links are usually displayed as simple lines connected between the nodes. However, in some Network Diagrams, not all of the nodes and links are created equally: additional variables can be visualised, for example, by making the node size or link stroke weight proportion to an assigned value.
> 
> By mapping out connected systems, Network Diagrams can be used to interpret the structure of a network through looking for any clustering of the nodes, how densely nodes are connected or by how the diagram layout is arranged.
> 
> The two notable types of Network Diagram are "undirected" and "directed". Undirected Network Diagrams only display the connections between entities, while directed Network Diagrams show if the connections are one-way or two-way through small arrows.
> 
> Network Diagrams have a limited data capacity and start to become hard to read when there are too many nodes and resemble "hairballs".
> ![image](https://user-images.githubusercontent.com/19007109/177582674-1d367ca4-bc0e-4abb-b535-078c536aecbf.png)

Example usage as a service map.

![image](https://user-images.githubusercontent.com/24588825/177146516-c4493dd9-715a-4411-a0f8-5819a8691f33.png)

**Comment by nickofthyme** [comment]
@superermiao We unfortunately do not yet support this type of chart. I updated your description with some more details, feel free to add anything you'd like.

**Comment by markov00** [comment]
Thanks for the request, is definitely an interesting visualization but is also a very vast in terms of details, layout, interactions and rendering capabilities. There are various libraries that I've tried in the past, from [SigmaJS](https://www.sigmajs.org/) (recently revamped) to [Cytoscape](https://js.cytoscape.org/)
cc @dej611 that is our graph expert probably know more about the complexity and intricacy of building our own graph visualization

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
