### ISSUE TITLE
[Tooltip] Minor style updates

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1764]
Here I am, after a little explorations it seems that the best option we have is to introduce a white 1px border to the whole tooltip, it would work as shown in the following image.

If there are other/better ideas I would love to hear that, for now this seems to be a clean, elegant and easy fix. @nickofthyme I hope it's not too hard to fix

<img width="655" alt="Screenshot 2022-07-25 at 16 30 41" src="https://user-images.githubusercontent.com/18484576/180802973-34f3ab55-e250-4da8-8439-4a4ad4827663.png">

_Originally posted by @gvnmagni in https://github.com/elastic/kibana/issues/136984#issuecomment-1194136879_

**Comment by markov00** [comment]
I'm closing this because it is already how it works
