### ISSUE TITLE
[partition] add hierarchical path to tooltip info

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1780]
**Describe the solution you'd like**
When rendering multi-layer partition chart, I'd like to render the hierarchical path of the element I'm currently hovering.
The current tooltip shows only the information related to the current, hovered, slice, but the hierarchical path starting from the root node is useful to understand the partition itself.

**Additional context**
We have a similar information on the LegendItems, where a `path` property is used to describe the hierarchical path of each single item. The same could be added to the tooltip itself.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/111246

**Comment by nickofthyme** [comment]
what do you think about adopting a `child`/`parent` structure for the tooltip and legend info? This would replace the `path` property that conveys the same context. Then the children array would just be empty for non-hierarchical data.

**Comment by markov00** [comment]
Good idea, I think that will work too

**Comment by markov00** [comment]
Fixed for now in #1843 
If we want to expose the full hierarchical information we should reopen this issue, because the linked PR will just render the full hierarchical tooltip values without any specific relationship across them
