### ISSUE TITLE
Improve appearance of vacant tile slots

### ISSUE THREAD

**Issue by andrewctate** [elastic/elastic-charts#1786]
**Is your feature request related to a problem? Please describe.**
In some cases, the vacant tile slots can make the visualization appear broken.

![broken-looking vis](https://user-images.githubusercontent.com/3884767/180838437-5734b858-eac9-444f-941f-8e29514a671b.png)

**Describe the solution you'd like**
Clearer visual queues that these slots are empty for a reason instead of just being broken.

**Describe alternatives you've considered**
Nothing here...

**Additional context**
Can look at @MichaelMarcialis's [review](https://github.com/elastic/kibana/pull/136567#pullrequestreview-1049822988) for more context. We have received similar feedback from others as well.

**Checklist**

- [x] this request is checked against already exist requests

**Comment by andrewctate** [comment]
Relevant discussion / ideas https://github.com/elastic/kibana/issues/137769#issuecomment-1205006769

**Comment by markov00** [comment]
cc @gvnmagni can you post here the final design of those empty tiles?

**Comment by gvnmagni** [comment]
Here you can find the screenshots, I'm not reposting the same images here in order to avoid repetition but please let me know if you prefer to have them also here

https://github.com/elastic/kibana/issues/137769
