### ISSUE TITLE
Add Graph Visualization support

### ISSUE THREAD

**Issue by timductive** [elastic/elastic-charts#1807]
The Profiler team is interested in a standardized graphing visualization, requirements are still tbd.

**Comment by dej611** [comment]
Potential overlap with #1855

**Comment by dej611** [comment]
Also overlap with #1740

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
