### ISSUE TITLE
Remove kibanamachine contributor checks from our repo

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1824]
We should probably disable the kibanamachine checks on our repo, because we don't use anymore Jenkins and we don't need anymore such control (done today by buildkite I suppose, @nickofthyme correct me if I'm wrong.

This is an example of messages that we don't require anymore
https://github.com/elastic/elastic-charts/pull/1818#issuecomment-1244349293

**Comment by nickofthyme** [comment]
I thought this was from the `.ci/` content but the message persisted after that was deleted. So just deleted the jenkins jobs the other day, after seeing it on #1818. Let me know if you see it again and I'll ping infra for help. For now I'll close this until it resurfaces.
