### ISSUE TITLE
ci deploys non-`master` branches to gh-pages

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#1871]
CI deploys gh-pages for non-`master` branches. See https://github.com/elastic/elastic-charts/actions/runs/3440483683

**Comment by markov00** [comment]
So this is a good or bad thing? Is bad because it overwrite the existing pages but good because we can also use gh pages to deploy the PR storybook?

**Comment by nickofthyme** [comment]
Yes, bad. It deploys all branches/PR to firebase but for `gh-pages` it should only deploy master or it will override the actual master. 

The example run above was from the webGL backport on `50.2.x` which replaced latest master on `gh-pages` as the tooltip changes are gone!

**Comment by nickofthyme** [comment]
The issue here was that the `skip` option for each step is determined based on changed files which does not apply to push events, only pull requests. So I added logic to override the `skip` and force the checks to run for upstream base branches. This forced the gh-pages deploy step to fire, causing this issue.
