### ISSUE TITLE
Remove the white border for custom tooltip

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#1901]
**Describe the issue**
The tooltip has a 1px border by default (that is useful to split the optional color stripe from the chart background).
This is applied to the container of the tooltip.

When rendering a custom tooltip, the white border remains visible creating the following issue: a border on every custom tooltip and in particular a 1x1 border pixel when rendering a null tooltip (in the case when we just want to show the cursor line and no tooltip)

<img width="182" alt="Screenshot 2022-12-12 at 17 54 57" src="https://user-images.githubusercontent.com/1421091/207105827-7a115eb6-1298-4efd-8131-4f6b844cde61.png">

**To Reproduce**
1. Go to [the custom legend PR preview](https://ech-e2e-ci--pr-1889-0j6h522w.web.app/?path=/story/legend--custom-legend&globals=theme:light)
2. Move your mouse around
3. See the white dot floating near the cursor

**Expected behaviour**
I'm expecting to see a such border only with our exposed custom tooltip components.

**Version (please complete the following information):**
 - Elastic Charts: 51.x

**Additional context**

I see some possible solutions:
- find a better way to put such white border at the left of the color stripe
- create a `TooltipContainer` component that needs to be used to contain our exposed tooltips
- find a way to force such border when using the color-strip

**Comment by markov00** [comment]
cc @nickofthyme what are your ideas on that? how should we proceed?

**Comment by nickofthyme** [comment]
The css solution would require us knowing the children to style the partent or using container size to hide the border. These two would require [`:has`](https://caniuse.com/css-has) or [CSS Container Queries](https://caniuse.com/css-container-queries), respectively. However, both are lacking firefox support.

I think the best approach is to add a `style` prop to the `TooltipSpec` that allows setting select styles on the tooltip wrapper container (i.e. `echTooltip`).
