### ISSUE TITLE
Show tooltip by icon in Metrics chart

### ISSUE THREAD

**Issue by formgeist** [elastic/elastic-charts#1936]
**Is your feature request related to a problem? Please describe.**

We often want to clarify the metric or the intent for the chart in a tooltip. Today we're solving this by showing a tooltip on the chart hover itself, but this doesn't feel intuitive. In many Observability visualizations, we'd place an icon tooltip by the title to show this type of description.

<img width="400" alt="CleanShot 2023-01-18 at 09 32 45@2x" src="https://user-images.githubusercontent.com/4104278/213122167-4643593d-b340-4b87-8305-8ccd32504102.png">

**Describe the solution you'd like**

The metrics charts already supports an icon to be displayed. I wonder if it's possible to extend this to provide a tooltip to provide a description instead.

![CleanShot 2023-01-18 at 09 26 04@2x](https://user-images.githubusercontent.com/4104278/213121499-020ca381-1ebf-4310-b767-501870932e87.png)

**Describe alternatives you've considered**

The alternative is to allow for adding custom components within the title or description to e.g. be able to show a `EuiIconTip`.

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests

**Comment by markov00** [comment]
Hi @formgeist you can already pass an `EuiIconTip` to the metric `icon`, it accept by default a react component so you can use whatever you want there.

```tsx
<Metric
 data={[[
{
...
icon: <EuiIconTip
          aria-label="Warning"
          size="m"
          type="alert"
          content="Your tooltip desc here"
        />
}]]}
/>
```
(don't look at the tooltip style that is probably missing in our storybook)
<img width="372" alt="Screenshot 2023-02-06 at 12 12 04" src="https://user-images.githubusercontent.com/1421091/216957485-5685ff35-bc22-4106-bfdd-6198a9be0af3.png">

**Comment by formgeist** [comment]
@markov00 Thanks for looking into it 👍
