### ISSUE TITLE
The Legend is not displayed correctly in the 'Bottom' mode

### ISSUE THREAD

**Issue by alexwizp** [elastic/elastic-charts#194]
**Describe the bug**
The Legend is not displayed correctly in the 'Bottom' mode

**Screenshots**
![image](https://user-images.githubusercontent.com/20072247/56721348-5b18b780-674d-11e9-97ac-be63aa87417c.png)

**Comment by markov00** [comment]
closed by https://github.com/elastic/elastic-charts/pull/208

**Comment by markov00** [comment]
fixed by https://github.com/elastic/elastic-charts/pull/208
