### ISSUE TITLE
Cannot set line width (strokeWidth) for BarSeries

### ISSUE THREAD

**Issue by alexwizp** [elastic/elastic-charts#196]
**Describe the bug**
Setting the line width works for AreaSeries but doesn't work for BarSeries

**Screenshots**
![image](https://user-images.githubusercontent.com/20072247/56722197-36254400-674f-11e9-8af9-b9c44c0f2df6.png)

**Comment by markov00** [comment]
Duplicate of https://github.com/elastic/elastic-charts/issues/189
Fix will be released in 3.11.4
