### ISSUE TITLE
Color Picker functionality cannot be disabled

### ISSUE THREAD

**Issue by alexwizp** [elastic/elastic-charts#198]
**Describe the bug**
I cannot disable the Color Picker functionality. It's a problem because for some modes we shouldn't allow user to change colors for series

![image](https://user-images.githubusercontent.com/20072247/56730151-d5523780-675f-11e9-8b22-9fa850f4d732.png)

**Comment by nickofthyme** [comment]
@alexwizp I'm assuming you don't want to allow the user to click the color dot to open the `rbg(104,188,0)`. Is that correct?

**Comment by markov00** [comment]
Yes @nickofthyme. So we are going to disable this functionality here: https://github.com/elastic/elastic-charts/pull/208
but we have to find a way to inject a color picker from outside

**Comment by markov00** [comment]
fixed by https://github.com/elastic/elastic-charts/pull/208
