### ISSUE TITLE
Avoid clipping tooltip markers on edges

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#20]
Find a way to fully display tooltip markers near the edges.

<img width="236" alt="screenshot 2019-01-31 at 22 32 13" src="https://user-images.githubusercontent.com/1421091/52086877-45f61780-25a8-11e9-9765-fe327439c0a1.png">

Kibana Cross Issues:
* https://github.com/elastic/kibana/issues/13248

**Comment by angorayc** [comment]
Hi @markov00,
Thanks for writing this down.
Just a note that I've got the same issue to the y tick as well.
<img width="799" alt="Screenshot 2019-06-04 at 23 49 33" src="https://user-images.githubusercontent.com/6295984/58893984-bf9f3d00-8723-11e9-8671-9533573920a3.png">

**Comment by cchaos** [comment]
Can we boost this one in priority?
