### ISSUE TITLE
Allow partial changes to a theme

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#201]
**Is your feature request related to a problem? Please describe.**
I'd like to change the style of a single property of the theme without having to create the full object that specify the style.

**Describe the solution you'd like**
I'd like to have a recursive partial type for the Theme object so I can specify only a small portion of the theme.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Kibana Cross Issues**
n/a

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by cchaos** [comment]
**Describe the solution you'd like**
Also, be able to use `mergeWithDefaultTheme` with partial objects.
