### ISSUE TITLE
Gauge/Bullet Chart: Labels and ticks handling

### ISSUE THREAD

**Issue by gvnmagni** [elastic/elastic-charts#2095]
The goal of this issue is to provide the team instructions on how to deal with labels of ticks for the bullet chart new design. We mainly have two cases, linear gauges (vertical and horizontal) and circular ones.

**Linear**

The label is positioned at the right of the tick, similar to what happens with time based axis. The last tick though, should behave as labels do when they reach the margin of the chart on the time-axis. They never trespass the limit, they stay fixed until the tick gets out of margin and only then they disappear as well. Hopefully the following images could help in understanding this concept.

Basically, our goal is that labels never get off the chart limit.

<img width="746" alt="Screenshot 2023-07-10 at 16 42 54" src="https://github.com/elastic/elastic-charts/assets/18484576/63134949-4e2a-4d3e-8e9f-08080ff1d4c0">

-------------
**Circular**

For circular bullet/gauge charts, given the complexity of the case, we prefer to go with a simpler approach. Labels are always centered on the tick, so that we don't have to deal with crazy calculation, and there is no custom of positions according to how close we are to the end of the chart, they just follow the tick.

<img width="850" alt="Screenshot 2023-07-10 at 16 46 38" src="https://github.com/elastic/elastic-charts/assets/18484576/48728dcd-2083-4cd1-8d96-03627c13e65b">

**Comment by nickofthyme** [comment]
Thanks for these example @gvnmagni. I believe we don't exactly follow these guidelines for linear specifically.

As it stands today, the last tick is set to the right/top of the tick when the space allows. If the space does not allow of the tick the value is pushed to the left/bottom of the tick.

![Screen Recording 2023-11-08 at 03 08 38 PM](https://github.com/elastic/elastic-charts/assets/19007109/6b9dbccd-2771-4bb0-ad67-7612c99cb2cf)

Until which point the tick value if no long within the domain and the tick and tick label are removed.

---

I'm not sure if there was discussion between you are Marco to address this change but this was the logic when I took over the code from Marco.

If you want the value to be fixed (aka stuck) to the end, we can do this pretty easily just need confirm this change. Would also be in a follow up PR.

**Comment by gvnmagni** [comment]
I am totally fine with this approach (and playing with the storybook I liked it a lot), the most important thing to me is to be consistent with the rest of axis on other charts, rather than the actual style of it.

I'm totally fine in going with this technique and re-evaluate that in the future with you and Marco according to IF we want to update that everywhere in a different way. Thank you for taking care of such a detail!
