### ISSUE TITLE
[API] wrap `onRenderChange` with a RAF

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#2135]
As follow up from this issue, https://github.com/elastic/elastic-charts/issues/2124 we should wrap again the `onRenderChange` callback into a RAF to precisely call the function only after the painting is done.

**Comment by nickofthyme** [comment]
@markov00 is this different than what @drewdaemon did here? https://github.com/elastic/elastic-charts/pull/2131

**Comment by markov00** [comment]
fixed by https://github.com/elastic/elastic-charts/pull/2131
