### ISSUE TITLE
[partition] issue with sparse date histogram result in treemap

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#2148]
**Describe the issue**

In some specific scenarios the Treemap throws a Maximum stack error.
Note that Treemap is the only partition visualization type affected by this issue.

**To Reproduce**
Steps to reproduce the behavior for Lens in the linked issue.

For local reproduction, this is the dataset used:
```
"timestamp per 30 seconds","Count of records"
1692887640000,
1692887670000,
1692887700000,1
1692887730000,
1692887760000,
1692887790000,
1692887820000,
1692887850000,
1692887880000,
1692887910000,
1692887940000,
1692887970000,
1692888000000,
1692888030000,
1692888060000,
1692888090000,
1692888120000,
1692888150000,3
1692888180000,
1692888210000,
1692888240000,
1692888270000,
1692888300000,
1692888330000,
1692888360000,
1692888390000,
1692888420000,1
1692888450000,1
1692888480000,
1692888510000,
1692888540000,
```

**Expected behaviour**

**Screenshots**

![treemap_forever](https://github.com/elastic/elastic-charts/assets/924948/4db9cf40-a549-438a-826e-da8b522fcb80)

**Errors in browser console**
```
Uncaught RangeError: Maximum call stack size exceeded
    at bestVector (treemap.js:39:1)
    at treemap (treemap.js:76:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
    at treemap (treemap.js:98:1)
```

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/164730

**Checklist**

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

**Comment by markov00** [comment]
closed in https://github.com/elastic/elastic-charts/pull/2214

**Comment by nickofthyme** [comment]
@markov00 #2214 was never merged 🤔

**Comment by markov00** [comment]
@nickofthyme correct, sorry about that, but I remember we fixed that somehow. Let me find how and in case I will close it again

**Comment by nickofthyme** [comment]
Yeah I thought it was fixed too but I was thinking about this issue https://github.com/elastic/elastic-charts/pull/2260 you fixed right when you got back.

**Comment by markov00** [comment]
yep, it was fixed here https://github.com/elastic/elastic-charts/pull/2260
