### ISSUE TITLE
New Gantt-like chart

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#2203]
**Is your feature request related to a problem? Please describe.**
The type of chart requested is typically used for request tracing and it is already possible to see a form of it within Kibana "Timeline waterfall" traces page:

![image](https://github.com/elastic/elastic-charts/assets/924948/7a99f37b-5e2f-4725-a35d-8c66fc006438)

I think something similar is available also on the Chrome DevTools side:

<img width="403" alt="Screenshot 2023-10-18 at 10 09 14" src="https://github.com/elastic/elastic-charts/assets/924948/cd41d2b0-5a0b-4e67-98d0-a8bf8abb44e4">

**Describe the solution you'd like**
It would be useful to have a reusable chart type like that to be used to trace durable events, like request flights and processing.

**Additional context**
We've considered also the icycle and flamechart but they have fundametally different shapes.

**Kibana Cross Issues**
Not yet.

**Checklist**

- [x] this request is checked against already exist requests

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
