### ISSUE TITLE
`onRenderChange` not called on chart resize

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elastic-charts#2221]
**Describe the issue**
When a chart is resized with no configuration changes, `onRenderChange` fails to fire leaving no way for a consumer to detect the rerender.

**To Reproduce**
1. Create a chart and instrument `onRenderChange` with a console statement
2. Resize the chart canvas (resizing the browser works)

See https://codesandbox.io/s/focused-rubin-n6s97f?file=/src/App.tsx

The chart resizes, but the `onRenderChange` isn't called.

https://github.com/elastic/elastic-charts/assets/19007109/56a2f383-5cb6-410c-8fe4-135e18eaedbd

**Comment by nickofthyme** [comment]
So after playing around with this a bit I noticed that the `onRenderChange` callback is **not** necessarily coupled directly with when the canvas is re-rendered.

Below you see console logs for a simple single series area chart from refresh. The logs are on the `onRenderChange` and the internal _**render to canvas**_ function.

### Current

<img width="526" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/f5a9947e-7a2a-43c3-a48d-28b3153fecad">

### With proposed changes

<img width="522" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/300cbcbd-9030-4712-8c81-1cee99bb55a0">

Here `onRenderChange` is initially called `5` time with `rendered === false`, then draws to canvas, then resized (which now sets the rendered state to `false`), Then something changes the state to `true`, the chart renders to canvas, the rendered `false` and rendered `true`.

I think this is badly in need of a cleanup
