### ISSUE TITLE
Metric text bounces when container size changed

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elastic-charts#2238]
**Describe the issue**
When the container size is updated along with the layout of the tiles, the text of the metric briefly changes size before adjusting itself.

**To Reproduce**
1. Visit the metric grid story [here](https://elastic.github.io/elastic-charts/?path=/story/metric-alpha--grid&globals=toggles.showHeader:true;toggles.showChartTitle:false;toggles.showChartDescription:false;toggles.showChartBoundary:false;theme:light&knob-show%20grid%20border=&knob-attach%20click%20handler=true&knob-use%20progress%20bar=true&knob-progress%20bar%20direction=vertical&knob-max%20trend%20data%20points=30&knob-number%20of%20columns=4&knob-debug%20randomized%20data=)
2. Change the column count

**Expected behaviour**
The text shouldn't resize.

**Screenshots**

https://github.com/elastic/elastic-charts/assets/315764/e499b29c-91ba-4ef5-80aa-de9fb59ac355

**Kibana Cross Issues**
Blocking https://github.com/elastic/kibana/issues/136993

**Checklist**

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] Every related Kibana issue is listed under `Kibana Cross Issues` list and the `kibana cross issue` tag is applied

**Comment by drewdaemon** [comment]
Both the data and the container dimensions are needed to [compute the correct text size](https://github.com/elastic/elastic-charts/blob/main/packages/charts/src/chart_types/metric/renderer/dom/index.tsx#L92-L97).

It seems like this bug is due to the calculation being run with up-to-date data and out-of-date container dimensions.

The following console statements illustrate this.

<img width="595" alt="Screenshot 2023-11-09 at 8 27 24 AM" src="https://github.com/elastic/elastic-charts/assets/315764/fba91e88-d855-41ac-9e00-a0c6c7a8fe70">

The first two lines are logged from the first parent render. You can see that a grid of width `4` is rendered with a container width of `800`.

The second two are from the second parent render. Now we have a grid of width `3` being rendered with a container width of `600`.

The third pair (highlighted) are from the first chart render. Here we have a grid of width `3` (new data) being rendered with an assumed width of `800` (old width). This is where we see the incorrect text size.

Then, the fourth pair are from the second chart render. It is triggered when the container width catches up to the data and the text size is corrected.

**Comment by drewdaemon** [comment]
@nickofthyme any insights into why this might be happening?

**Comment by nickofthyme** [comment]
@drewdaemon From the start I see this is happening even at the story level outside of the chart. So I if add these logs in the `/metric/grid.story.tsx`...

```ts
console.log(containerWidth);
console.log(chartData);
console.log('----');
```

<img width="521" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/200e02b0-2bd3-4aa4-94a0-70ff585c11ae">

...which then gets directly passed to charts which tries to render one after the other.

That said the question is can/should we somehow debounce these renders by a few 100 milliseconds to catch then quick re-renders.

**Comment by drewdaemon** [comment]
## What is going on?
@nickofthyme and I did some investigating. Here is what is roughly happening

### First React render
1. the user updates the number of columns setting
2. container CSS and `Metric` `data` prop are updated
3. container is resized by the browser
4. metric renderer receives new data
5. text size is computed (incorrectly) using old container dimensions with new data

### Second React render
1. metric renderer receives updated container dimensions
2. text size is computed correctly, using new container dimensions and existing data

### Recap
So, the problem is essentially that computing correct text size
1. depends on the browser updating the dimensions of the parent container
2. is tied to the React render queue instead of the browser's layout process, causing a delay

If the new data is held back until the new container dimensions are received, the text size issue isn't present, however a distorted visualization is shown when the container dimensions have been updated, but React hasn't had a chance to render yet:

https://github.com/elastic/elastic-charts/assets/315764/0b2ae255-5f82-4758-98de-dd95421ae175


## Possible solutions
- The client could supply expected dimensions through the React contract that are then replaced with the real container dimensions once available. In many cases, they would match or be close, so the text wouldn't need to be updated.
- The text could be sized using [CSS container queries](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_container_queries). This would divorce text size from the React cycle and allow it to update on container resize as part of the browser's layout sequence.
