### ISSUE TITLE
Add color picker for legend item

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#23]
**Is your feature request related to a problem? Please describe.**
Add a color picker to choose a new series color when clicking on the legend item.

**Describe the solution you'd like**
Will use EUIColorPicker

**Describe alternatives you've considered**

**Additional context**

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/28618
https://github.com/elastic/kibana/issues/19341

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
@markov00 & @rshen91 Do you think we could just require a React component, i.e. `EuiColorPicker`,  to render allow this? I think it would look bad if the charts had a different color picker.

**Comment by rshen91** [comment]
> @markov00 & @rshen91 Do you think we could just require a React component, i.e. `EuiColorPicker`, to render allow this? I think it would look bad if the charts had a different color picker.

I don't have a problem with this, and keeping the color pickers consistent makes sense to me. It looks like it already is a11y friendly so that's a plus  https://github.com/elastic/eui/issues/789
