### ISSUE TITLE
Heatmap labels are hard to see with dark theme

### ISSUE THREAD

**Issue by drewdaemon** [elastic/elastic-charts#2347]
**Describe the issue**
When `EUI_CHARTS_THEME_DARK` is used as the theme for a heatmap (per [these directions](https://eui.elastic.co/#/elastic-charts/creating-charts)), the labels are very dark.

**To Reproduce**
[Sandbox](https://codesandbox.io/p/sandbox/bug-repro-attempt-2-forked-g3yfgc)

**Expected behaviour**
The labels should be light enough to contrast with the background.

**Screenshots**
<img width="706" alt="Screenshot 2024-03-01 at 5 37 09 AM" src="https://github.com/elastic/elastic-charts/assets/315764/5da9917e-5afb-4ae1-8dae-088566988025">

**Version (please complete the following information):**
 - OS: OSX
 - Browser: Brave, Edge, etc
 - Elastic Charts: `64.0.0`

**Comment by nickofthyme** [comment]
Thanks @drewdaemon, that usage is no longer the ideal approach as we are deprecating the theme consumed from eui in favor of our new charts `LIGHT_THEME` and `DARK_THEME` from #2175. My next task is to update the eui docs and exports to reflect this change.

**Comment by drewdaemon** [comment]
@jpcarey see the above guidance to resolve your issue with the dark theme on the heatmap vis. Try importing `LIGHT_THEME` and `DARK_THEME` from the charts library instead of using the EUI themes.

**Comment by nickofthyme** [comment]
Also see https://github.com/elastic/kibana/pull/170914#issuecomment-1823014121 for changes applied to kibana.

**Comment by nickofthyme** [comment]
Closing as we are updating the eui docs to reflect this change in https://github.com/elastic/eui/pull/7572

<img width="989" alt="image" src="https://github.com/elastic/elastic-charts/assets/19007109/fe9d3b92-a52f-4605-a443-0778286a0a5c">

**Comment by jpcarey** [comment]
That worked, thank you @nickofthyme and @drewdaemon
