### ISSUE TITLE
Allow customization of sub series names

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#245]
**Is your feature request related to a problem? Please describe.**
Currently the name for a sub series is automatically created by concatenating the split series values and yAccessors.  This leads to issues in both the legend and element hover tooltip when the split series values need to be formatted.

(in the example below, the UUIDs are defined as `yAccessors`, not `splitSeriesAccessors`)
![image](https://user-images.githubusercontent.com/452850/59775215-a8a13480-9265-11e9-8da1-f20f7a6733e2.png)

**Describe the solution you'd like**
This is related to the request in #241 though not completely the same as with that request, the user may want to do more than just the series name formatting.

For this enhancement, we could do something similar to how @nickofthyme  is extending the Accessor type for colorAccessors so that we can define either a string field accessor as we do now (in which case the series name would be the default concatenation) or a function which has `specId` and `colorValues` params that can be used to return a custom formatted string.

**Describe alternatives you've considered**
We already have the `name` prop on a series and could use that; the problem there is that for a split series, we may want different custom names per split series and so just using the one `name` prop may not be the best.

The other possibility is that instead of adding the function as a type on `splitSeriesAccessors` and `yAccessors`, we could add it to `name` instead and ensure that if `name` is defined, it always takes precedence over the default.

**Additional context**
related to #241 

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Checklist**

- [ ] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by angorayc** [comment]
Hello,
I am excited about this feature, as we have similar request in SIEM.
When splitAccessor's got a single value, the legend label shows different from what we expected.
https://github.com/elastic/kibana/pull/48260#issuecomment-542651714
I'm looking forward to have the same behaviour for showing the legend label doesn't matter how many group we have in the dataset.
Thank you for taking this into consideration.

**Comment by nickofthyme** [comment]
Hey @angorayc we needed to refactor some of the code in order to make this work in a useful way without going through the rigmarole of this 👇 

```tsx
const barCustomSeriesNames: CustomSeriesNamesMap = new Map();
const barDataSeries: DataSeriesColorsValues = {
  colorValues: ['cloudflare.com', 'direct-cdn', 'y2'],
  specId: getSpecId('bars'),
};
barCustomSeriesNames.set(barDataSeries, 'MY CUSTOM SERIES');

return (
  <Chart className="story-chart">
    {/* base config stuff */}

    <BarSeries
      id={getSpecId('bars')}
      xScaleType={ScaleType.Linear}
      yScaleType={ScaleType.Linear}
      xAccessor="x"
      yAccessors={['y1', 'y2']}
      splitSeriesAccessors={['g1', 'g2']}
      customSeriesNames={barCustomSeriesNames}
      data={TestDatasets.BARCHART_2Y2G}
    />
  </Chart>
)
```

The good news is that that work is currently in progress and I expect this feature to be available sooner rather than later. See progress in PR https://github.com/elastic/elastic-charts/pull/419

**Comment by markov00** [comment]
@nickofthyme I think we can close this as it's solved in https://github.com/elastic/elastic-charts/pull/539, is it right?
