### ISSUE TITLE
Elastic-charts on non-white backgrounds

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#249]
**Is your feature request related to a problem? Please describe.**
Currently elastic-charts renders under the assumption of having a full white (`#fff`) background. If this isn't the case, there are some minor UI issues:
<img width="626" alt="Screenshot 2019-06-25 at 17 14 32" src="https://user-images.githubusercontent.com/1508364/60110832-09040a80-976d-11e9-86d3-607b1564d32d.png">

**Describe the solution you'd like**
* No fading background on legend container (or having this behavior configurable)
* Small margin on `.echContainer` (This could also be done on the consumer side, but it's probably a nice default)

**Describe alternatives you've considered**
Having a full white background, which works in this specific case, but it would be nice to even out these cases.

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Good catch. I've seen this behaviour and we will for sure fix that.
Let's cc @cchaos because I want to find a nice solution for the gradient: do you think it's possible to change the gradient of the container to reflect the background color?
For the margin, we can do few things: 
- add a padding settings on the <Chart /> component or on the theme (it can create some confusion together with the chartMargins chartPaddings property of the theme)
- we can compute the parent size minus the .echContainer padding value if someone added a class with that style
- we can keep it like that and inform the user to specify the padding on the parent
- any other ideas?

**Comment by cchaos** [comment]
The overflow gradient is created via a SASS mixin and can take any color to replace the white. However, @flash1293 I'm guessing that your screenshot is more of a "temporary" background color for the chart? Meaning, that looks like the droppable area background highlight when dragging an item. I don't know what the best approach should be for a highlighted background versus a theme selected background color.

As for the padding around the chart, this should be left to the consumer. Either by supplying them with a top level prop on `<Chart>` or by informing them to supply their own wrapper to `<Chart>` with the padding they need.

**Comment by flash1293** [comment]
You are right @cchaos, this is about dynamic background colors.
I haven’t tried it but could we use the mask-image property for the overflow effect instead? https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image
Then it would be background independent. I can look into whether this would be possible in our case if you haven’t tried already.

I agree with your comment regarding padding.

**Comment by cchaos** [comment]
@flash1293 Good idea with the `mask-image`. I've created a PR in EUI to fix those.https://github.com/elastic/eui/pull/2088

**Comment by flash1293** [comment]
@markov00 The fix will be released with eui 12.3.0 https://github.com/elastic/eui/pull/2088 Can we close this issue?

**Comment by markov00** [comment]
@flash1293 I've created a PR to fix that issue, it's on review
