### ISSUE TITLE
[Colors] New color palette testing

### ISSUE THREAD

**Issue by gvnmagni** [elastic/elastic-charts#2517]
Issue created to monitor progresses on testing and implementation of new color palette.

```[tasklist]
### Related
- [ ] https://github.com/elastic/elastic-charts/issues/2512
- [ ] https://github.com/elastic/elastic-charts/issues/2513
```

**Comment by gvnmagni** [comment]
Related issue: https://github.com/elastic/elastic-charts/issues/2512

**Comment by gvnmagni** [comment]
Related issue: https://github.com/elastic/elastic-charts/issues/2513

**Comment by teresaalvarezsoler** [comment]
@gvnmagni fyi, we will create a new issues in the Kibana repository because this palette will go into Kibana.

**Comment by teresaalvarezsoler** [comment]
Closing this one in favour of https://github.com/elastic/kibana/issues/192848
