### ISSUE TITLE
[Metric Chart] New font-sizes handling might cause existing Metric charts to look off

### ISSUE THREAD

**Issue by gvnmagni** [elastic/elastic-charts#2543]
In `8.15` a new handling of font-sizes has been introduced, moving it from being `width-related` to `height-related`. This was motivated by a series of considerations that are still valid but it could result in weird appearances for panels that are taller than large, or with very large numbers (lot of digits).

Example of problematic Metrics
![Image](https://github.com/user-attachments/assets/6da0217e-49cf-497f-9022-7626087bb74d)

In order to solve this, I would propose to introduce a way to take in consideration also the width of panel when defining the font-size of values so that value don't get cut off.

I would see two approaches to implement this solution:

1. Font-sizes are still determined according to break-points that take in consideration height of the panel, if the numbers are cut off their font-size automatically jumps to a smaller breakpoints, until it fit.

2. Same but instead of jumping to a smaller breakpoint, we automatically swtich to `FIT` function and get back to `DEFAULT` function as soon as the panel gets back to be big enough

Both options have pros and cons in terms of final look & feel but both will solve the original issue.

Thanks to @MichaelMarcialis and @markov00 and @nickofthyme for the conversation around this topic.

**Comment by gvnmagni** [comment]
Expected result of two proposed options:

![Image](https://github.com/user-attachments/assets/dbb9f1a8-3627-49a7-8adb-1d85a569b9cc)

**Comment by muthu-mps** [comment]
@gvnmagni, @markov00  - The integrations upgraded to 8.15.0 needs to get upgraded to the latest version to get this issue resolved without any changes to the metric visualisation?

**Comment by nickofthyme** [comment]
Correct, changes from #2548 will be in [`@elastic/charts@v68.0.1`](https://github.com/elastic/elastic-charts/releases/tag/v68.0.1) and targeted to be in `8.16.1`/`8.17.0` (https://github.com/elastic/kibana/pull/197473).

**Comment by markov00** [comment]
probably also in `8.16.0`
