### ISSUE TITLE
How to dynamically switch themes？

### ISSUE THREAD

**Issue by tripitakav** [elastic/elastic-charts#2550]
![Image](https://github.com/user-attachments/assets/7c430148-66b6-474d-9713-7ca99df6c518)
![Image](https://github.com/user-attachments/assets/068e306e-ddf1-496f-8f7e-7f5db2219f1d)

I want to use this chart library externally, but when I tried to switch themes, I found that importing multiple theme CSS files would be overwritten。

**Comment by nickofthyme** [comment]
Yeah unfortunately this is not idea as the chart theming depends on both the `Theme` as a js object and the exported `scss` files.

One way to do this is using a [`nested @import`](https://sass-lang.com/documentation/at-rules/import/#nesting), as we do in our storybook for dynamically switching themes.

https://github.com/elastic/elastic-charts/blob/1b39f630ee616664a03d275a425eed8822a47edc/storybook/style.scss#L27-L31
