### ISSUE TITLE
Refactor AxisStyle object to include custom styles for AxisSpec

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#260]
**Is your feature request related to a problem? Please describe.**
Refactor custom styles to be included in the `Axis Style` object started in PR https://github.com/elastic/elastic-charts/pull/217

Currently the `AxisStyle` only includes tickLabelPadding

**Additional context and Potential Solution**
Suggestion for the object to match `AxisConfiguration`: https://github.com/elastic/elastic-charts/pull/217#discussion_r300051330

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
closing in favour of #452
