### ISSUE TITLE
Allow the value part of the chart tooltip to be hidden

### ISSUE THREAD

**Issue by peteharverson** [elastic/elastic-charts#275]
Following https://github.com/elastic/elastic-charts/pull/233 the header part of a tooltip can be customized, but for some charts it would also be beneficial to hide the value part of the tooltip, when the values are of little or no meaning to the user.

For example, this area chart used in the ML data visualizer plots the distribution of metric values in a density curve, and the y axis values should ideally not be shown to the user as they are only numbers used in the calculations to give equal area bars for the percentiles plotted in the chart:

![image](https://user-images.githubusercontent.com/7405507/62211674-14170f80-b397-11e9-948a-cade7946b9d7.png)

**Comment by markov00** [comment]
Done, now the tooltip could be fully customizable, see [docs here](https://github.com/elastic/elastic-charts/wiki/Custom-Tooltip)
