### ISSUE TITLE
Add webpack build config

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#282]
**Is your feature request related to a problem? Please describe.**
I want a more configurable build. Allow for watch mode for built assets.

**Describe the solution you'd like**
Combine all build scripts into `webpack.config.js` file. This would facilitate [`yarn link`](https://yarnpkg.com/lang/en/docs/cli/link/)ing of `@elastic-charts` into other codebases, for seamless debugging.

**Describe alternatives you've considered**
Use [watchman](https://facebook.github.io/watchman/docs/install.html) to watch file changes and build _everything_ over again.

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
@nickofthyme can we close this within https://github.com/elastic/elastic-charts/pull/1164 ?

**Comment by nickofthyme** [comment]
I think the main issue here is fixed but I would still like to have our chart builds run by webpack or [vite](https://vitejs.dev/guide/) instead of `tsc`.
