### ISSUE TITLE
Group series on legend

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#295]
Charts should be able to provide consumers an easy to attain this result:

<img width="876" alt="Screen Shot 2019-08-06 at 12 06 44 PM" src="https://user-images.githubusercontent.com/549577/62556556-1ff54c80-b843-11e9-912c-6f4210324a09.png">

## Styling

- [ ] Allow providing series more than just different colors
  - [ ] Line style (dashed/dotted)
  - [ ] Point shape (triangle, square, etc..)
  - [ ] Area/bar pattern fills

## Legend

- [ ] Group color vs style into two legends
- [ ] Provide a nested legend that is collapsed by default

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
