### ISSUE TITLE
The order of the series in the tooltip does not match the legend

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#303]
**Describe the bug**
The order of the series listed in the tooltip is reverse of that listed in the Legend

**To Reproduce**
1. Create any multi-series chart
2. Show the legend
3. Hover item in chart to get the tooltip

**Expected behavior**
The orders should match

**Screenshots**
<img src="https://d.pr/free/i/tIYDMj+" width="50%" />

**Version (please complete the following information):**
 - Elastic Charts: 9.0.0

**Comment by markov00** [comment]
Thanks @cchaos. I completely agree on that, what do you think could be the right order on the legend/tooltip for the following situations:

**starting from top: blue, red, green**
**or red, blue, green**
<img width="104" alt="Screenshot 2019-08-14 at 16 43 36" src="https://user-images.githubusercontent.com/1421091/63030589-dba52480-beb2-11e9-89ef-fb6522182bdc.png">

**starting from top: green, blue, red**
<img width="83" alt="Screenshot 2019-08-14 at 16 43 49" src="https://user-images.githubusercontent.com/1421091/63030597-dd6ee800-beb2-11e9-808a-b8cd7b17e6a5.png">

**starting from top: red, blue, green**
<img width="80" alt="Screenshot 2019-08-14 at 16 43 59" src="https://user-images.githubusercontent.com/1421091/63030603-e069d880-beb2-11e9-82ed-3ca0e8e31a39.png">

**Comment by cchaos** [comment]
It just needs to match the same order as the legend.
