### ISSUE TITLE
Axes tick labels should be hide-able

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#312]
**Is your feature request related to a problem? Please describe.**
There are times where a chart will want to keep the axis lines but hide axes tick labels. For instance on very small charts where the values can be described elsewhere.

**Describe the solution you'd like**
Either allow passing `showTicks={false}` or something else.

**Describe alternatives you've considered**
I'm currently using `tickFormatter={() => {}}` and it does remove the actual labels, **but** it doesn't remove the spacing.
![image](https://user-images.githubusercontent.com/549577/63049651-3042a280-bea7-11e9-9826-f78d557c628a.png)
<img src="https://d.pr/free/i/oQDwEM+" width="50%" />

**Checklist**

- [x] this request is checked against already exist requests
- ~[ ] every related Kibana issue is listed under `Kibana Cross Issues` list~
- ~[ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present~

**Comment by markov00** [comment]
fixed in https://github.com/elastic/elastic-charts/pull/711
