### ISSUE TITLE
Legend should resize when series titles change

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#367]
**Is your feature request related to a problem? Please describe.**
When configuring a visualization in Kibana the chart legend with render a narrow legend then create longer series labels and create a squashed legend.

![Screen Recording 2019-09-05 at 10 45 AM](https://user-images.githubusercontent.com/19007109/64357923-26562000-cfcb-11e9-994d-bece9fc8c733.gif)

**Describe the solution you'd like**
The legend size should resize, preferably animate, when legend series labels change.

**Describe alternatives you've considered**
None really come to mind.

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Additional Context**

Fixed by a full-page refresh
![Screen Recording 2019-10-24 at 03 50 PM](https://user-images.githubusercontent.com/19007109/67524315-1dea9f00-f676-11e9-9049-0d338f30bfd3.gif)

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
what about a manually resizable legend ? an handle can be dragged to resize it 😬

**Comment by nickofthyme** [comment]
like a method on the Chart (i.e. `chartRef.updateLegnedSize()`)?

**Comment by markov00** [comment]
I think that should be done automatically by the chart itself. If one of the legend item changed it's value, than the legend should resize
