### ISSUE TITLE
IE 11 infinie loop

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#371]
**Describe the bug**
https://elastic.github.io/eui/#/

**To Reproduce**
1. Go to EUI [docs](https://elastic.github.io/eui/#/) on __IE 11__
1. Open dev tools
1. Search for `chart`
1. Click on `Creating charts` link
1. Notice site freezes
1. Click the pause button in the `Debugger` tab to see the call stack

**Expected behavior**
Page doesn't freeze

**Version (please complete the following information):**
 - OS: windows
 - Browser: IE11
 - Elastic Charts: `v11.2.0`

**Errors in browser console**
<img width="305" alt="Screen Shot 2019-09-11 at 9 22 21 AM" src="https://user-images.githubusercontent.com/19007109/64743871-2a040e00-d4c7-11e9-816e-cea9095c28ae.png">

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
The source of error appears to be related to lack of polyfills for `Map` and `Set`.

The console error points to this line of code
https://github.com/elastic/elastic-charts/blob/db543988644dfa20d3c33b9463019be2e4cee164/src/chart_types/xy_chart/utils/series.ts#L326-L328

replacing this with...
```ts
dataSeries.xValues.forEach((xValue) => {
  xValues.add(xValue);
});
```

solves this issue and then throws error on

https://github.com/elastic/elastic-charts/blob/db543988644dfa20d3c33b9463019be2e4cee164/src/chart_types/xy_chart/domains/x_domain.ts#L160

Which [`Set.prototype.values`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set/values) is not supported in IE11. Replacing this line with...

```ts
const scaleType = [...scaleTypes][0];
```

I think possible fixes to this are
- Include the missing polyfills
- Update the missing polyfills in consuming applications
- `worst case` Fix all code and prevent certain usages of unsupported es2015+ in IE11 which seems extreme and annoying.

@markov00 @chandlerprall any thoughts?

**Comment by chandlerprall** [comment]
Poked at this more in the EUI docs (where I don't see a console error, just an infinite loop in the script).

The compiled/`dist` code for the

```javascript
 for (const xValue of dataSeries.xValues) { 
   xValues.add(xValue); 
 } 
```

loop is

```javascript
        try {
            for (var _b = __values(dataSeries.xValues), _c = _b.next(); !_c.done; _c = _b.next()) {
                var xValue = _c.value;
                xValues.add(xValue);
            }
        }
```

so the `x of y` syntax is at least attempted to be polyfilled, but the `__values` definition is interesting:

```javascript
var __values = (this && this.__values) || function (o) {
    var m = typeof Symbol === "function" && o[Symbol.iterator], i = 0;
    if (m) return m.call(o);
    return {
        next: function () {
            if (o && i >= o.length) o = void 0;
            return { value: o && o[i++], done: !o };
        }
    };
};
```

the `typeof Symbol === "function" && o[Symbol.iterator]` test returns `false` and the function hits the last return, and look at that `next` function: `o.length` and `o[i++]` expressions both return `undefined` for Set objects and therein lies the infinite loop: `i` will _never_ be `>= undefined`

The two things that I observe from this:
* If `Set` were completely polyfilled and had a proper `Symbol.iterator` this should execute properly
* The charts' build has a bad/incomplete definition for the `x of y` syntax and is publishing broken code

**Comment by nickofthyme** [comment]
This could be related to the [`downlevelIteration`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-3.html#new---downleveliteration) I'm not sure how that affects the final output.

**Comment by chandlerprall** [comment]
Good find, this is from the docs you linked

> Please note that this requires a native Symbol.iterator or Symbol.iterator shim at runtime for any non-array values.

Which is exactly the problem here.

**Comment by nickofthyme** [comment]
Sweet! yeah I read that and thought it could relate to your description. Also I verified the `@elastic/charts` in `kibana` does not experience this issue.

**Comment by nickofthyme** [comment]
@chandlerprall are you ok if we close this issue? Or leave it open until we know there is nothing to do on our side?

**Comment by chandlerprall** [comment]
Let's get document the polyfill need in https://github.com/elastic/elastic-charts/blob/master/wiki/consuming.md , then I think this is closable and I'll update EUI to include a full polyfill. Thanks for testing this out in Kibana!
