### ISSUE TITLE
Updating the barSeriesStyle in `theme` doesn't change the tooltip color. 

### ISSUE THREAD

**Issue by andrew-moldovan** [elastic/elastic-charts#383]
**Describe the bug**
I wanted to update the color of the bar in a bar graph so that it wasn't the default green. I did this by doing:
```
            theme={{
              barSeriesStyle: {
                rect: {
                  fill: euiColorPrimary,
                },
              },
            }}
```
This changed the color of the bar graph, but the tooltip color was still showing the original green.

<img width="253" alt="Screen Shot 2019-09-19 at 12 55 37 PM" src="https://user-images.githubusercontent.com/2496425/65277288-6d213b00-dade-11e9-9417-0cf2210471f0.png">

**Expected behavior**
The tooltip should be the same color as the bar. 

**Version (please complete the following information):**
 - Elastic Charts: [e.g. 12.0.2]

**Comment by nickofthyme** [comment]
Hey Andrew. After discussing this with Marco I now understand why it doesn't work as expected.

The global theme styles are meant for changing global theme styles. Say if you wanted bars with white fill and only the outer border as the assigned series color. In that case, you pass a theme such as...

```tsx
theme={{
  barSeriesStyle: {
    rect: {
      fill: 'white',
    },
    rectBorder: {
      visible: true,
      strokeWidth: 1,
    },
  },
}}
```

If you are wanting you change the color of a given series you can use the `CustomSeriesColorsMap` prop to select the series and assign a color.

Or replace the `theme.colors.vizColors` like I mentioned.

Sorry for the confusion and thanks for creating this issue now I know for the future. 

I opened a PR to try to clarify those props on the `Theme` object to prevent this type of misunderstanding in the future. I am hoping to be able to enhance our docs around the charts library to clarify things like this.

**Comment by andrew-moldovan** [comment]
@nickofthyme makes total sense and as I was thinking more about this, I agree as well that you've made the right choice to limit this to `CustomSeriesColorsMap.

Thanks!
