### ISSUE TITLE
Stacked area charts render with gaps when the X coordinates are not continuous

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#388]
**Describe the bug**
Gaps appear in the rendering when you skip an X coordinate in your stacked area chart. It only appears in stacked areas, since stacked bars render correctly.

<img width="450" alt="Screenshot 2019-09-23 14 08 34" src="https://user-images.githubusercontent.com/666475/65450652-a4a82400-de0b-11e9-82e0-fa7d1b8bde52.png">

**To Reproduce**
This is an example of discontinuous data:

```
      <AreaSeries
        splitSeriesAccessors={['split']}
        stackAccessors={['x']}
        id={getSpecId('y')}
        xAccessor={'x'}
        yAccessors={['y']}
        data={[
          {
            x: 5,
            y: 10,
            split: 'a',
          },
          {
            x: 5,
            y: 30,
            split: 'b',
          },
          {
            x: 10,
            y: 2,
            split: 'a',
          },
          // {
          //   x: 10,
          //   y: 3,
          //   split: 'b',
          // },
          {
            x: 20,
            y: 30,
            split: 'a',
          },
          {
            x: 20,
            y: 20,
            split: 'b',
          },
        ]}
        xScaleType={ScaleType.Linear}
        yScaleType={ScaleType.Linear}
      />
```

**Expected behavior**
With the data above, I would expect the chart library to insert an extra vertex at the missing X coordinates.

**Comment by nickofthyme** [comment]
@markov00 would this be a non-standard behaviour through a prop or should it always ignore discontinuous data?

**Comment by wylieconlon** [comment]
As a consumer of elastic-charts I would expect stacking to work regardless of the input data. I would expect that the stacking is always cumulative, so that every vertex in the bottom stack will create a vertex in stacks above.

**Comment by nickofthyme** [comment]
Ok cool, that makes sense! I'll make it happen. Thanks @wylieconlon

**Comment by markov00** [comment]
@wylieconlon what is the expected output for the above example?
Do you expect that, by default, the missing value is configured as a zero as in the following screenshot:
<img width="816" alt="Screenshot 2019-09-27 at 14 59 53" src="https://user-images.githubusercontent.com/1421091/65771117-ca993580-e137-11e9-888a-cbcf7426920e.png">

Or something like this (where I just extended a bit the x axis domain to show the effect a bit more
<img width="828" alt="Screenshot 2019-09-27 at 15 07 26" src="https://user-images.githubusercontent.com/1421091/65771489-97a37180-e138-11e9-9848-5d4535a75919.png">

I think we could go with something configurable from the consumer.

@nickofthyme I think we can partially resume this: https://github.com/elastic/elastic-charts/pull/55

**Comment by wylieconlon** [comment]
@markov00 I see cases where both of those charts are correct. I just tried recreating this in google sheets and found that they do the first behavior, treating missing values as 0 and connecting the lines. Elasticsearch aggregations support both behaviors, they are null by default but can be configured to have a value: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-avg-aggregation.html#_missing_value

I actually think I was expecting a rendering that is in between the two, because the "gaps" rendering would look very strange in the example I gave at the top, or with any other stacks.

Imagine the shape I've drawn here, but with a fill underneath the dotted line:

<img width="814" alt="65771757-2f08c480-e139-11e9-842a-ae84c6d2e4ff" src="https://user-images.githubusercontent.com/666475/65883187-876fda00-e364-11e9-907f-c857fa75cc8e.png">

**Comment by markov00** [comment]
@wylieconlon I like the idea of having a dashed line that describe the missing part of the chart.
I think we can use a fitting function #55 to define the value of the missing point: null, 0, last available, the next available etc.

I think the segmented/dashed line can take a bit more time to implement because we need to separate that line from the rest of the chart but we can work on adding the fitting function to that.

**Comment by nickofthyme** [comment]
> Based on slack/zoom conversations with @wylieconlon and @markov00  

`LineSeriesSpec` and `AreaSeriesSpec` should allow the user to specify a fitting function to fill `null` values in the dataset. Similar to https://github.com/elastic/kibana/issues/17717.

For the meantime, the style of the "fitted" line should be dashed and area fill, if applicable, will be the same as the "non-fitted" fill color. Later improvement could pass a style to be applied.

Edge cases:
- Stacked areas where void is in lower series such that the upper series would potentially have to fill the void in the lower series.

**Comment by wylieconlon** [comment]
Looking at existing work in Kibana, I think this area chart rendering issue can also create single dots:

<img width="510" alt="Screenshot 2019-10-02 14 36 46" src="https://user-images.githubusercontent.com/666475/66071939-137b3080-e522-11e9-85b6-7257ac18c0d6.png">

**Comment by markov00** [comment]
@wylieconlon the example shown already works in elastic-chart (infra is using elastic charts). The problem here is more on how to handle stacked area chart more than single area chart that work as expected (the main difference is that the style of the area chart is configured to shoiw the area points)

**Comment by wylieconlon** [comment]
@markov00 Sorry if I was unclear, but I showed that screenshot not because it's a problem in isolation but because I'm not sure what the correct stacking behavior would be there. Imagine that we're tracking total network traffic and want to split it by machine, and the traffic looks like above. How would it stack?

**Comment by wylieconlon** [comment]
@markov00 Thanks for the update! The "quick fix" behavior you've described will work for us as long as we are able to get it in for 7.5
