### ISSUE TITLE
Add nice option for axis ticks

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#397]
**Is your feature request related to a problem? Please describe.**
Allow user to set the option for [`nice`](https://github.com/d3/d3-scale#continuous_nice) tick ending values.

**Describe alternatives you've considered**
User manually sets the domain based on dataset

**Additional context**
An attempt was made in #384 but ran into issues with ticks aligning to the geometry domain.

See this branch for attempt https://github.com/elastic/elastic-charts/compare/master...nickofthyme:feat/nice-ticks

`computeSeriesDomains` computes the `xDomain` and `yDomains` which are then passed to all subsequent function. I think this would be the best place to set the nice value so the domain is set from the beginning.

Better yet is this could return the `xScale` and `yScales` that would be better so the scale is not instantiated in the `getAxisTicksPositions` and then in `getScaleForAxisSpec`

**Comment by markov00** [comment]
> An attempt was made in #384 but ran into issues with ticks aligning to the geometry domain.

@nickofthyme do you remember a specific SB story that shows that tick alignment problem?

**Comment by nickofthyme** [comment]
No this was so long ago I can't remember what problems there were with tick alignments.
