### ISSUE TITLE
Mixing bars with line or area series breaks legend toggle

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#399]
**Describe the bug**

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/mixed-charts--bar-and-lines or https://elastic.github.io/elastic-charts/?path=/story/mixed-charts--areas-and-bars
1. Click to toggle the `bars` series in the legend.
1. Notice the line/area series is no longer visible.

**Expected behavior**
The line and area charts do not hide when bar series is toggled.

**Screenshots**
### Bars with line
![Screen Recording 2019-09-30 at 10 31 AM](https://user-images.githubusercontent.com/19007109/65893337-69f33e00-e36d-11e9-8673-1eea5770c098.gif)

### Bars with area
![Screen Recording 2019-09-30 at 10 31 AM](https://user-images.githubusercontent.com/19007109/65893411-855e4900-e36d-11e9-90d8-966dddd8f60b.gif)

Also remove the `0` in upper left corner

<img width="848" alt="Image 2019-09-30 at 11 23 50 AM" src="https://user-images.githubusercontent.com/19007109/65897449-e9d0d680-e374-11e9-804b-8e636b8fbffe.png">

**Version (please complete the following information):**
 - OS: all
 - Browser: chrome/all
 - Elastic Charts: `master`

**Additional context**
The hover state works fine so must be something related to the `deselectedDataSeries` or `toggleSingleSeries` method in `chart_state.ts`

**Comment by rshen91** [comment]
_Notes to self:_ 
This might be a Konva bug on initial investigation: 
console.logging before ```this.deselectedDataSeries = updateDeselectedDataSeries(this.deselectedDataSeries, legendItem.value);``` in chart_state.ts shows `null` for deselecting bars in the legend but shows `[]` for deselecting line or area based on the story 🤔 
The errors in the console point to Konva warnings about `"points" attribute has non numeric element NaN`...checking out where Konva comes in and seeing if the null is not being cast whereas the [] can be cast to a number 🤔 


<img width="1246" alt="Screen Shot 2019-10-07 at 12 06 49 PM" src="https://user-images.githubusercontent.com/20343860/66336766-f7e5a080-e8fa-11e9-921d-58005850131a.png">

**Comment by rshen91** [comment]
`export function buildLineRenderProps` in `rendering_props_utils.ts` takes in 'x' as a parameter and adding before the return statement the following below resolves the Konva Infinity warning:

```js
if (x === Infinity) {
    x = 53.53125;
}
```

I took the 53.53125 from the lines value but I'm not sure if this value would make sense for all cases beyond the mixed stories.
