### ISSUE TITLE
Empty chart state

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#400]
**Is your feature request related to a problem? Please describe.**
There can be cases where the user want to see an empty chart with axis, ticks etc, but without data

**Describe the solution you'd like**
Have a way to describe a chart data placeholder for empty charts.
The placeholder needs to specify a basic description of the chart like: axis extents, type of scales etc.

**Describe alternatives you've considered**
n/a

**Additional context**
SIEM team is using a custom placeholder with a simple text: https://github.com/elastic/kibana/blob/a325611c407358b6ef90bcd1bef07e1edf704b0b/x-pack/legacy/plugins/siem/public/components/charts/common.tsx#L40

we should provide a way to implement that within the elastic-charts library, having either a text placeholder or a empty chart

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues/feature requests here.

**Checklist**

- [x] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by angorayc** [comment]
We also have a similar question about if we should present a chart holder instead of an empty chart when all the data set are zero in bar chart:
https://github.com/elastic/kibana/issues/47021

**Comment by angorayc** [comment]
I'm working on some enhancement of the chart and chart holder. Please find here for the cases that presenting a chart holder: https://github.com/elastic/kibana/pull/47130

**Comment by markov00** [comment]
Let's link this task with https://github.com/elastic/elastic-charts/issues/202, we should work on chart state in a uniform way

**Comment by markov00** [comment]
closing in favour of https://github.com/elastic/elastic-charts/issues/2380
