### ISSUE TITLE
Fix chart rotation animations

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#41]
When rotating the chart, the left/right edges of the chart animation are bounded to the dimensions of the chart container, but not for the top/right edges so that the chart will appear to animate from outside of the container.

![chart_rotation_animation](https://user-images.githubusercontent.com/452850/52309046-d0959880-2953-11e9-93d3-ed8336c93976.gif)

**Comment by markov00** [comment]
I've 3 ideas here:
- we don't fix it directly: since we have a clipping rectangle, the final user will never see elements outside the clipping rectangle. 
- we can fix the animation
- we can disable animation on rotation (rotation is a setting and we don't need to animate that change)

**Comment by markov00** [comment]
closing for now as animation is not a priority at the moment and the underlying architecture is has changed
