### ISSUE TITLE
Add Docs to Storybook 

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#457]
**Is your feature request related to a problem? Please describe.**
This came up a bit in #451 and I'm opening this issue for tracking and  to personally follow-up. Storybook provides a [Docs](https://www.learnstorybook.com/design-systems-for-developers/react/en/document/) add-on which we might want to include to provide a docs section per story. 

It seems like some stories are using the info parameter currently, which is good, but a full blown docs section per story would be clearer for users (hopefully). 

**Describe the solution you'd like**
Mentioned above, there are some resources to get this started: 
https://www.learnstorybook.com/design-systems-for-developers/react/en/document/
https://medium.com/storybookjs/storybook-docspage-e185bc3622bf

**Describe alternatives you've considered**
It looks like there might be a similar issue opened in #379 but with a different approach. I'll keep @nickofthyme in the loop.

**Kibana Cross Issues**
I'm not sure this directly impacts Kibana but would be generally helpful for any consumer. 

**Checklist**

- [x] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by rshen91** [comment]
We are on an older version of Storybook 5.1.9 and docs are available on 5.2. Exploring options...

**Comment by markov00** [comment]
@rshen91 we are on a fixed 5.1.9 because there was some small typescript issues switching to 5.2.
Since we are now merged the redux PR I think we can easily switch to 5.2 fixing those issues

**Comment by nickofthyme** [comment]
Some of these may not work at all. Like they used to allow for `object[]` types and now only allow certain types in an array.

Also, the VRT relies on the query params to interpolate the correct value. Like a number will come out as a string not a number.

**Comment by nickofthyme** [comment]
Also #379 is to create a separate docs page apart from storybook.

**Comment by markov00** [comment]
> Some of these may not work at all. Like they used to allow for `object[]` types and now only allow certain types in an array.
> 
> Also, the VRT relies on the query params to interpolate the correct value. Like a number will come out as a string not a number.

I've did a preliminary check few  days ago and seems that there are only few `arrays` to parse back to number or string before using them. There was few differences on adding the info-addon.
All the rest seems to work quite straight forward.
