### ISSUE TITLE
Bar charts on linear scales with static bar width

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#497]
**Is your feature request related to a problem? Please describe.**
Add the possibility to render bar-charts with static bar width along a linear/time scale to mimic the behaviour of various other tools like tableau.

**Describe the solution you'd like**
I'd like to create a `<BarSeries>` component where the `minInterval` is 0 but where I can specify a bar width in pixel or percentage.
The consumer needs to know that the bars can overlaps each other.
The pointer detection algorithm needs to detect multiple bars if they overlaps, or should always detect the nearest one to the pointer x value.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Kibana Cross Issues**
n/a

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by shahzad31** [comment]
we also have a similar need in uptime to have different width for bars.
