### ISSUE TITLE
Heatmap chart (beta)

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#501]
Already listed in the roadmap #3, but I want to reference this issue directly.

<img width="329" alt="Screenshot 2019-12-17 18 26 15" src="https://user-images.githubusercontent.com/666475/71209292-224bc680-2279-11ea-8177-c107e604fc6f.png">

<img width="1174" alt="Screenshot 2019-12-19 16 07 47" src="https://user-images.githubusercontent.com/666475/71209505-ba49b000-2279-11ea-9f84-54ac97cfa17b.png">

This is more general than the specific type of heatmap requested here: https://github.com/elastic/elastic-charts/issues/263

Heatmaps with labels require contrasting colors, which is an existing feature in Kibana.

**Kibana Cross Issues**
None

**Checklist**

- [x] this request is checked against already exist requests
- ~[ ] every related Kibana issue is listed under `Kibana Cross Issues` list~
- ~[ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present~

**Comment by wylieconlon** [comment]
Also shown in the screenshots above: Kibana visualizations do not currently support continuous gradient coloring, but I believe the Kibana Maps app does support them. Heatmaps would be the best way of displaying continuous quantitative data and should support continuous color scales and legends (as shown above). Related issue: https://github.com/elastic/elastic-charts/issues/492

**Comment by markov00** [comment]
Closing this as a first alpha version of the heatmap chart was released 
ref: https://github.com/elastic/elastic-charts/pull/831
