### ISSUE TITLE
customSeriesColors as function

### ISSUE THREAD

**Issue by stacey-gammon** [elastic/elastic-charts#507]
According to Storybook docs, looks like customSeriesColors can be a function.

<img width="800" alt="Screen Shot 2020-01-03 at 11 06 53 AM" src="https://user-images.githubusercontent.com/16563603/71734124-2a7b3880-2e19-11ea-90b9-05433d5111a8.png">

But when I tried this, it threw an error:

<img width="680" alt="Screen Shot 2020-01-03 at 11 04 47 AM" src="https://user-images.githubusercontent.com/16563603/71734143-349d3700-2e19-11ea-9987-733bf9b895e2.png">

`utils.js:72 Uncaught TypeError: spec.customSeriesColors.forEach is not a function`

Though, I think storybook is tested so I'm not sure how it's working in there, unless that is a new feature and Kibana is on an older version.  I looked in the pull requests but didn't find anything recent that matched by `customSeriesColors` search.

**Comment by markov00** [comment]
It's now fixed thanks to https://github.com/elastic/elastic-charts/pull/557
It was an issue with the Storybook `addon-info` addon, that doesn't render correctly the story sources. In the mentioned PR we are rendering the source code of each example with a different addon that shows a cleaner and more faithful source code
