### ISSUE TITLE
Gauge/Goal Chart type

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#520]
**Is your feature request related to a problem? Please describe.**
Add Gauge and Goal Charts, part of https://github.com/elastic/elastic-charts/issues/3

**Describe the solution you'd like**
In Kibana we describe the two chart types as the following:
- Gauges indicate the status of a metric. Use it to show how a metric's value relates to reference threshold values.
- A Goal chart indicates how close you are to your final goal.

Grafically they looks similar, usually the gauge chart has a needle that indicate the metric value and the radial data range that is usually divided into multiple colored areas. The Goal chart doesn't have a needle but and a single radial colored bar that specify the percentage on how close the value is to its goal.

<img width="403" alt="Screenshot 2020-01-21 at 17 47 14" src="https://user-images.githubusercontent.com/1421091/72825019-93b2d680-3c76-11ea-8788-4f8185333f68.png">
<img width="503" alt="Screenshot 2020-01-21 at 17 52 18" src="https://user-images.githubusercontent.com/1421091/72825175-dc6a8f80-3c76-11ea-9979-9b2f176683a5.png">

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by monfera** [comment]
Just pasting here the types of Kibana gauge and goal charts currently available
![image](https://user-images.githubusercontent.com/1548516/76500078-2e8e8c80-6440-11ea-9983-e28c0c463e6c.png)

**Comment by monfera** [comment]
Range autoextend disabled will truncate the viz at the highest band cap but still shows the correct number:
![image](https://user-images.githubusercontent.com/1548516/76511255-386dbb00-6453-11ea-8f00-e099b5628373.png)

Range autoextend enabled will introduce a last, implicit, unmarked band (not that easy to see as both the sector and the arc band marker are green):
![image](https://user-images.githubusercontent.com/1548516/76511325-5804e380-6453-11ea-8fa4-6551cce326a6.png)
