### ISSUE TITLE
Partition charts with legend and tooltip

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#532]
Legends and tooltips are a requirement for replacing pie and donut charts in Kibana. The main reason is that when rendered in a dashboard, it's not obvious what the visualization shows without the tooltip to indicate the source of the data.

The legend and coloring implementation that exists in Kibana combines all values into a flat legend, regardless of the layer it's displayed on. That behavior might not be needed if we can come up with a better way of displaying legends.

<img width="630" alt="Screenshot 2020-01-30 14 27 50" src="https://user-images.githubusercontent.com/666475/73483192-04d84500-436d-11ea-9be1-5c1ef567ee74.png">
<img width="504" alt="Screenshot 2020-01-30 14 28 42" src="https://user-images.githubusercontent.com/666475/73483292-289b8b00-436d-11ea-8a51-245962e52608.png">

While there are customization options in the current implementation, they are pretty minimal. For example, the legend can't be hidden.
<img width="1379" alt="Screenshot 2020-01-30 14 29 46" src="https://user-images.githubusercontent.com/666475/73483393-5a145680-436d-11ea-8c7f-25ead1cb427d.png">

**Comment by wylieconlon** [comment]
To break down this feature more, I think there are a few elements:

* Color legend for the first layer is a requirement for us in Lens. Because we are using color on the first layer to indicate category, this would be enough for our use. The first layer is often too small to show labels inside the slices or rectangles, but the color matters a lot. Because of these limitations, a one-level legend would be enough.
* Supporting some kind of [nested legend](https://github.com/elastic/elastic-charts/issues/223) is a nice-to-have, but I understand it's a harder problem.
* I think tooltips that show "field" and "value" as seen in the screenshot would be nice to have.

**Comment by markov00** [comment]
I've opened #623 for the tooltip request
