### ISSUE TITLE
Box plot / violin plot

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#541]
Box plots and violin plots show distribution, and can be used to compare side-by-side distributions. Box plots show quartiles (25, 50, and 75), while violin plots show the full distribution using a smoothing function.

[<img width="432" src="https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Michelsonmorley-boxplot.svg/1920px-Michelsonmorley-boxplot.svg.png" />](https://en.wikipedia.org/wiki/Box_plot#/media/File:Michelsonmorley-boxplot.svg) (Public domain)

[<img width="792" src="https://upload.wikimedia.org/wikipedia/commons/3/3a/Violin_plot.gif" />](https://en.wikipedia.org/wiki/Violin_plot) (Public domain)

Elasticsearch is about to merge a box plot aggregation, which would return min, 1st quartile, median, 3rd quartile, and max.  We also already have the percentiles aggregation in general, so the data will soon be readily available in the right shape for these visualizations.

Cross-kibana issue:
https://github.com/elastic/kibana/issues/4157

**Comment by monfera** [comment]
Closing this in favor of https://github.com/elastic/elastic-charts/issues/1675
