### ISSUE TITLE
Charts' JavaScript is unparseable by IE11

### ISSUE THREAD

**Issue by chandlerprall** [elastic/elastic-charts#549]
**Describe the bug**
When including `@elastic/charts` in a bundle, IE11 fails to parse the JavaScript file and logs the error `Expected ';'` from this line:

```javascript
      for (i of a.entries())
```

found in

```javascript
/***/ "../../node_modules/@elastic/charts/node_modules/fast-deep-equal/es6/index.js":
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";


// do not edit .js files directly - edit src/index.jst


  var envHasBigInt64Array = typeof BigInt64Array !== 'undefined';


module.exports = function equal(a, b) {
  if (a === b) return true;

  if (a && b && typeof a == 'object' && typeof b == 'object') {
    if (a.constructor !== b.constructor) return false;

    var length, i, keys;
    if (Array.isArray(a)) {
      length = a.length;
      if (length != b.length) return false;
      for (i = length; i-- !== 0;)
        if (!equal(a[i], b[i])) return false;
      return true;
    }


    if ((a instanceof Map) && (b instanceof Map)) {
      if (a.size !== b.size) return false;
      for (i of a.entries())
        if (!b.has(i[0])) return false;
      for (i of a.entries())
        if (!equal(i[1], b.get(i[0]))) return false;
      return true;
    }
```

**To Reproduce**
1. Open dev tools in IE11
2. Visit https://eui.elastic.co/

**Expected behavior**
Page shouldn't be broken in IE11

**Version (please complete the following information):**
 - OS: Windows 8 & 10
 - Browser: IE11
 - Elastic Charts: 17.0.2

**Additional context**

**Errors in browser console**
`Expected ';'`

**Kibana Cross Issues**
Add any [Kibana](https://github.com/elastic/kibana) related issues here.

**Checklist**
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Hi @chandlerprall this is already fixed in 17.0.3
