### ISSUE TITLE
Add annotations to the legend

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#555]
**Is your feature request related to a problem? Please describe.**
Actually, the legend shows only the series names. We should also add the ability to include any annotation to the legend with it's own marker/colors/icons

<img width="621" alt="Screenshot 2020-02-18 at 16 25 27" src="https://user-images.githubusercontent.com/1421091/74750021-550b3e80-526b-11ea-9d05-12e6f53b5005.png">

<img width="235" alt="Screenshot 2020-03-27 at 15 33 22" src="https://user-images.githubusercontent.com/1421091/77766726-538a1e80-7040-11ea-8451-0f72354ad832.png">

**Describe the solution you'd like**
We should have a prop in the Annotation component that describe if we want that annotation displayed on the legend or not. (By default, to avoid breaking changes, that option should be off).
The legend should display the name/id of the annotation + one of the following:
- the marker/icon if the LineAnnotation has a marker configured
- a small vertical/horizontal line if the LineAnnotation doesn't have a marker configured, the color should be the same of the annotation stroke
- a small square with the same fill/opacity of the RectAnnotation 
- Annotation groupings should be toggleable the same as chart series in the legend.

The legend item for each annotation should also allow the user to hide/show the group of annotations.

**Describe alternatives you've considered**
n/a

**Additional context**
The requests comes from https://github.com/elastic/elastic-charts/issues/522

**Kibana Cross Issues**
- https://github.com/elastic/kibana/issues/84178

**Checklist**

- [x] this request is checked against already exist requests
- [ ] every related Kibana issue is listed under `Kibana Cross Issues` list
- [ ] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by formgeist** [comment]
@markov00 @nickofthyme Not sure about your prioritization for 7.11, but this is another much-needed addition to the charts in order to display averages across selected time ranges in APM. Can you share an update on this? Thanks 👍

**Comment by formgeist** [comment]
I posted this comment in the wrong issue, but would still be valuable to have in the charts for APM as we're displaying multiple different annotations in the charts, and I believe it's not good practice not to show what they each indicate.

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
