### ISSUE TITLE
Allow selection of single series from tooltip

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#562]
**Is your feature request related to a problem? Please describe.**
Having a click listener that returns single desired value/point/series

**Describe the solution you'd like**

From discussion on #548 

A static tooltip to allow the user to select a series within a given proximity.

> If consumers only want a single point passed back to them, they could tell the chart to allow "affixing" the tooltip when the user clicks on a point. This will then allow the exact point in the tooltip to be clickable and sent back to the consumer. (https://github.com/elastic/elastic-charts/issues/548#issuecomment-585831176)

![Screen Recording 2020-02-11 at 09 14 AM](https://user-images.githubusercontent.com/19007109/74250002-9fab1a80-4caf-11ea-9e05-1e954111eea0.gif)

**Describe alternatives you've considered**
Handle multiple series form the event

**Checklist**
- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
Done in #1782
