### ISSUE TITLE
Interactive Charts to enable Machine Learning Interpretability for Elastic ML

### ISSUE THREAD

**Issue by Winterflower** [elastic/elastic-charts#576]
**Is your feature request related to a problem? Please describe.**
Hello Kibana team! In the last few releases of Elastic ML, we have shipped supervised learning capabilities: regression and classification. In supervised learning, a machine learning model is trained on a labeled dataset. The model learns the features of the data. The trained model is then used on unlabeled data to, for example, predict which class to assign to each dataset. 
A growing trend in the machine learning community has been to develop various techniques that enable "machine learning interpretability", which, while it doesn't have a fixed explanaination, is usually meant to denote how well a decision/classification made by a machine learning model can be interpreted or explained.

To enable this type of interpretability in our Elastic ML product, we have added a feature based on Shapley value calculations. To take full advantage of the results, we would like to enable the user to visualise how these Shapley values, or as we call the, `feature_importance` values interact with the classification decisions/regression output of a model.

**Describe the solution you'd like**
It would be great if we could leverage Kibana building blocks to build charts like the ones linked below

<img width="795" alt="Screen Shot 2020-03-02 at 6 07 42 PM" src="https://user-images.githubusercontent.com/4982858/75700316-29984300-5cb2-11ea-9e4e-df8761d02ce4.png">

<img width="861" alt="Screen Shot 2020-03-02 at 6 08 31 PM" src="https://user-images.githubusercontent.com/4982858/75701382-f656b380-5cb3-11ea-8875-3d96b0e56cbf.png">
<img width="878" alt="Screen Shot 2020-03-02 at 6 08 40 PM" src="https://user-images.githubusercontent.com/4982858/75701398-0078b200-5cb4-11ea-858b-82b69187b2f1.png">

**Describe alternatives you've considered**
Building similar charts with Vega. 

cc: @AlonaNadler

**Comment by markov00** [comment]
Hi @Winterflower thanks for your request.
Can you provide a bit more context on each visualization you are interested in?
For example:
-  the first example seems to be a bee swarm chart (https://flowingdata.com/charttype/beeswarm/) but I'm not sure if the Y axis on each category brings information or it's just a visual effect

- I'm not sure about the one in the middle, actually it's not possible with our elastic-charts but I'd like to understand a bit better the usecase and what you want to visualize and express here

- the last one seems to be an band area chart, that is already achievable with elastic-charts, but maybe I'm missing something there

**Comment by markov00** [comment]
Hey @Winterflower what version you are currently targeting for this chart types?

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
