### ISSUE TITLE
Weird artifacts of small pie slice strokes

### ISSUE THREAD

**Issue by cchaos** [elastic/elastic-charts#598]
**Describe the bug**
Small pie slices show an extended border outside of the pie bounds.

**Screenshots**
Easily seen on a dark background

![Screen Shot on 2020-03-23 at 16:19:51](https://user-images.githubusercontent.com/549577/77359853-a56e3400-6d22-11ea-877d-1dce335e7395.png)

**Comment by monfera** [comment]
@cchaos thanks for the report, will look into these
