### ISSUE TITLE
Stacked bars/area should support displaying the subtotal

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#635]
As originally requested in https://github.com/elastic/kibana/issues/55262, there should be a way to include a subtotal indication for each position on the X axis.

<img width="773" alt="Screen Shot 2020-01-17 at 5 44 33 PM" src="https://user-images.githubusercontent.com/11432120/72656612-5934fb00-3951-11ea-900d-c14f1a23d5b2.png">

https://github.com/elastic/kibana/issues/55262

**Comment by nickofthyme** [comment]
Closing in favor of #1355
