### ISSUE TITLE
Two layered pie chart issue in case of only 1 data point

### ISSUE THREAD

**Issue by yizheliu-amazon** [elastic/elastic-charts#637]
**Describe the bug**
Hi Elastic/Kibana developers,

I’m seeing a bug with rendering in Kibana when I’m using a 2 layered sunburst/pie chart with a **_single_** data point for the chart. The label of the outer circle overlaps with the inner circle.

**To Reproduce**
1. Change [line 29](https://github.com/elastic/elastic-charts/blob/master/stories/sunburst/8_sunburst_two_layers.tsx#L29) to `data={[mocks.sunburst[0]]}`
2. Open local url: http://localhost:9001/?path=/story/sunburst--sunburst-with-two-layers
3. You will see label of inner and outer circle overlaps with each other, as show in Screenshot 1

**Expected behavior**
Labels of 2 layers sunburst/pie chart in case of only 1 data point should be clearly visible.

**Screenshots**
Screenshot 1:
![Screen Shot 2020-04-17 at 12 43 47 PM](https://user-images.githubusercontent.com/59710443/79624526-f6313c80-80d6-11ea-8193-2d38c7f0780f.png)

Screenshot 2:
![Screen Shot 2020-04-17 at 12 46 51 PM](https://user-images.githubusercontent.com/59710443/79624605-90918000-80d7-11ea-833b-75961a04bed3.png)

**Version (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: chrome
 - Elastic Charts: 18.2.2

**Additional context**
I tried to avoid this issue to display both labels properly by making change to the `linkLabel` [config](https://github.com/elastic/elastic-charts/blob/master/stories/sunburst/8_sunburst_two_layers.tsx#L60-L63) as below:
```
linkLabel: {
    // maxCount: 0,
    fontSize: 14,
    maximumSection: Infinity,
},
```
And then go to URL in step 2, you will see the label of inner circle is invisible, as shown in Screenshot 2.

**Errors in browser console**
N/A

**Kibana Cross Issues**
N/A

How do I display the labels of 2 layers sunburst/pie chart in case of only 1 data point?

Thanks for your help.

**Comment by markov00** [comment]
Hi @yizheliu-amazon, thanks for issuing the ticket. 
Unfortunately, this is a known bug, it can be also visible here https://elastic.github.io/elastic-charts/?path=/story/sunburst--single-sunburst

@monfera do you see any workaround for that issue that can be used before we release the fix?

**Comment by monfera** [comment]
There's no good workaround for now - while it's possible to add an artificial, vanishingly small but nonzero-valued slice to prevent the special layouting for the single-valued case, it'll still show up in the legend. However it's a small fix so it could be part of the next release

**Comment by yizheliu-amazon** [comment]
Thanks for your comments. @markov00 @monfera .

Could you please let me know when next version will be released?

**Comment by yizheliu-amazon** [comment]
Sorry for late reply. Thank you for the fix!
