### ISSUE TITLE
Treemap should also observe the fillLabel.padding setting

### ISSUE THREAD

**Issue by wylieconlon** [elastic/elastic-charts#659]
Thanks @monfera for merging the update to add grooved text! I'm trying it out, and found what looks like a bug. I see in the "groove label" storybook example the commented out settings for `fillLabel.padding`, but when I uncomment the settings nothing changes. This is also happening in my Lens configuration:

<img width="655" alt="Screenshot 2020-04-30 18 16 53" src="https://user-images.githubusercontent.com/666475/80764509-d6563b80-8b0e-11ea-9e4b-60bbe16d2b11.png">

**Comment by monfera** [comment]
@wylieconlon correct, [see description](https://github.com/elastic/elastic-charts/pull/652#issue-409634204). As it's a different layouting it hasn't yet been added back, the plan is to reinstate it in a next PR now that #658 is merged - it's very motivating to see it with this small typeface where it's most felt, thanks! 

Btw. it looks good with these EUI colors! Maybe it'd be better for group separation and group label readability to not color the groups themselves (it's unrelated to your note so I don't view it as a design decision). The grooves are also height constrained, sandwiching the group label text, which therefore have inherent visual noise above and below, so using color there has a worse effect than coloring the leaf nodes themselves. The group delineation also varies with lightness, Men's Shoes is better separated than Women's Accessories

**Comment by monfera** [comment]
Minor note, the `padding` was never in effect for the treemap but it wasn't obvious as text was centered verticlaly and horizontally, so I'm removing the bug label
