### ISSUE TITLE
Brushing domain is not calculated properly for custom `minInterval` bigger than time range 

### ISSUE THREAD

**Issue by mbondyra** [elastic/elastic-charts#663]
**Describe the bug**
Brushing domain is not calculated properly for custom `minInterval` bigger than time range.

[Codesandbox](https://codesandbox.io/s/keen-butterfly-zs1sd?file=/src/App.tsx)

**To Reproduce**
Here's the video recording the bug:
https://www.loom.com/share/97539270863b4d238736fe1aa9369559

1. Go to Lens visualisation and create simple date histogram on records count.
2. Setup time range for 30 minutes and custom interval for 7 days (more than 30 minutes) as in the picture
![image](https://user-images.githubusercontent.com/4283304/81066262-1fc2d400-8edd-11ea-9ebd-0ee0bf40a24c.png)
3. Try to brush in the chart to change time range outside of the setup time range.
4. `min` will be correct but `max` will be evaluated to xDomain.max. Min is bigger than max. 

**Expected behaviour**
Time range will be evaluated correctly.

**Comment by mbondyra** [comment]
I found a similar problem on Discover bar chart - when having a partial data bucket, if you brush only in the area after the red line, the range will be incorrect (min bigger than max). Recording shows it best: https://www.loom.com/share/1455d66f77bf4fde9cfdac426ba0af01 . 

@markov00 it looks like the same issue, but if you want me to submit the separate one, let me know.

**Comment by nickofthyme** [comment]
@mbondyra This functionality is the indented functionality. I'm talking with @markov00 to see if we could handle this better internally and maybe update the max domain to reflect the interval.

In the meantime, there is a workaround that is used in `xy_vis_type` which is to add the `allowBrushingLastHistogramBucket` prop to the `Settings` component.

**Comment by nickofthyme** [comment]
You can see it working [here](https://codesandbox.io/s/bold-newton-6183x?file=/src/App.tsx)

![Screen Recording 2021-02-05 at 12 58 PM](https://user-images.githubusercontent.com/19007109/107077052-f0b1f980-67b1-11eb-86dd-b5e76d0f6979.gif)

Please reopen if this does not solve your issue.
