### ISSUE TITLE
Smarter duplicate ticks finder

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#667]
**Is your feature request related to a problem? Please describe.**
We introduced the `showDuplicateTicks` property to show/hide duplicated ticks on a specific axis.
This works great until the user wants a set of repeated tick like in the following example:
I'm rendering a line series chart, where my x-axis has a time scale. My data spans 3 days, and I want to display ticks at midnight and at twelve o'clock. 
Should the library be smart enough to detect this situation or should we leave the consumer to choose and handle that case? 

This is, for example, the current situation in TSVB when choosing a time range of 3 days and an `auto` time interval.

<img width="1237" alt="Screenshot 2020-05-07 at 10 52 59" src="https://user-images.githubusercontent.com/1421091/81280509-e020f700-9058-11ea-8ca3-2cb9a5f240a0.png">

The `showDuplicateTicks` is off by default and the ticks are wrongly deduplicated.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/47045
https://github.com/elastic/kibana/issues/70956

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by flash1293** [comment]
It seems like `showDuplicateTicks` is not what the user wants in most cases. I think the behavior should be `showConsecutiveDuplicateTicks` - those almost never add any value and should not be shown by default.

Also, the deduplication logic could be smart enough to place the remaining label of a deduplicated sequence in the center of the covered range.

**Comment by markov00** [comment]
Thank @flash1293, that's indeed a better behavior than the current one.

> Also, the deduplication logic could be smart enough to place the remaining label of a deduplicated sequence in the center of the covered range.
I'm not sure I've understood perfectly what you mean, but the tick should always indicate the starting of an interval because it's much more clear to understand where one interval start and end, having them in the center of each interval could create confusions between users: some could interpret them as the center of the interval, some other as the beginning.

<img width="890" alt="Screenshot 2020-05-07 at 12 26 18" src="https://user-images.githubusercontent.com/1421091/81284119-fda48f80-905d-11ea-8cc2-24db9bf185d7.png">

The bottom-most axis/tick/label alignment is for me a better alignment in this case, what do you think? The tick lines are aligned with the beginning of each interval, where the label is centered in each interval instead of centered on the tick

**Comment by flash1293** [comment]
@markov00 you are completely right, thanks for the illustration.

I think the current deduplication logic keeping the first tick is fine. The "tradeoff" option looks interesting but it seems to be uncommon.
