### ISSUE TITLE
Value labels option for charts without hovering

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elastic-charts#67]
Often raised by users,  users use dashboard/visualization in kiosk node displaying it on monitor, they can't tell the value of the chart without hovering on the area of the chart, this issue often also raised in the context of reporting, when you export a report  isn't possible to hover and know the value of the chart. 
It will be helpful if we had an option to display the chart with the values labels (similar to pie)
![image](https://user-images.githubusercontent.com/32550316/53023887-e8b8ed80-3412-11e9-85ff-99f2489dc587.png)

**Comment by markov00** [comment]
That's a great feature. Let me write down some possible edge cases that we need to handle:
- text/value on short or narrow bars can overlap other bars or texts
- long text/value can overlap other bars specially
- medium to high density charts can be quite crowded

Possible solutions (configurable via editor/code):
- display only labels that doesn't overlap (hide value on short/narrow bars, hide value when it it's longer than the bar width, hide value when overflowing on another bar)
- show only values on min and max bars
- try a positioning algorithm to display label without overlaps like for piechart
- add annotations to specific values only

**Comment by emmacunningham** [comment]
For a first pass on this, we can handle just the simple implementation (and when `TextAnnotation` is implemented, refactor so that text labels are handled internally as a `TextAnnotation`) and set aside edge cases.
