### ISSUE TITLE
Allow greater control over layer rendering order

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#674]
## Feature

Allower greater control over the layer rendering order on canvas layers. Should sync with legend and tooltip order somehow.

## Proposed API

Very rough idea right now to start thinking about the best approach

```ts
// Render ordering
interface OrderFn = (series: SeriesIdentifier) => number; // number to use as global z-index
interface OrderSortFn = (seriesA: SeriesIdentifier, seriesB: SeriesIdentifier) => -1 | 0 | 1; // relative ordering of series
type Order = OrderFn | OrderSortFn | number // number would be the simplest ordering or spec
interface BasicSeriesSpec {
  order: Order;
}

// Edge clippings
interface EdgeClippingProps {
  lineWidth?: boolean; // including line width on edge
  points?: boolean; // including point radius on edge
  highlighter?: boolean; // include all highlighter elements outside of chart area
  padding?: number; // max padding for clippings
}
interface SettingsSpec {
  // not sure if Settings is the right place for this but it should be a global thing
  edgeClipping: EdgeClippingProps;
  ...
}
```

Related to #315, #303, #585  & #160

### Overall ordering

Order rendering per spec, based on simple number or order.

### Series ordering

Order rendering per series, overriding spec order. For example, select which line gets drawn on top of the other.

![image](https://user-images.githubusercontent.com/19007109/81722614-3e7a1b00-9447-11ea-8daf-00496ae3d840.png)

### Edge clipping

Greater control for clipping at the edge for line widths and points

<img width="1238" alt="Image 2020-05-12 at 11 57 03 AM" src="https://user-images.githubusercontent.com/19007109/81722970-c6f8bb80-9447-11ea-9dfa-7a0f29a5fc23.png">

**Comment by markov00** [comment]
@nickofthyme do you think we can close this for now? does the new rendering sorting mechanism solves the request here?

**Comment by nickofthyme** [comment]
Yeah, I don't know why I grouped sorting with the edge clipping, I think that issue still stands but we can address that in a separate issue.
