### ISSUE TITLE
Dashed Lines Not Working

### ISSUE THREAD

**Issue by mtiller** [elastic/elastic-charts#687]
When setting the `line.dash` value for annotation styles, it doesn't actually impact the appearance of the line.

**To Reproduce**
1. Go to [the line styling example in the StoryBook](https://elastic.github.io/elastic-charts/?path=/story/annotations-lines--styling)
2. Adjust the dash related values
3. Note there is no change in the appearance of the line.

**Expected behaviour**
I would expect the appearance of the line to change.  Note that I suspected a bug in the StoryBook itself, but I see the same behavior with my own annotations.

**Version (please complete the following information):**
 - OS: Whatever is hosting your StoryBook
 - Browser: Chrome
 - Elastic Charts: Version rendering current StoryBook (I couldn't find any indication)

Note - I don't see any examples in your StoryBook (although perhaps I missed them) that demonstrate dashed or dotted lines.

**Comment by markov00** [comment]
Thanks @mtiller I can confirm the bug, we will fix this as soon as possible.
Triage details:
- the `LineAnnotationStyle` type doesn't have the `StrokeDashArray` prop
- as a consequence the `renderLineAnnotations` doesn't render the line with the provided dash arrat
