### ISSUE TITLE
X-axis labels vertically to save space

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elastic-charts#69]
Often the x-axis is based on timestamp which can be very long, it will be helpful to show the x-axis vertically to save space and allow more labels in the given limited space
![image](https://user-images.githubusercontent.com/32550316/53025183-4ea67480-3415-11e9-9da8-6bb8dcbf74ca.png)

**Comment by markov00** [comment]
This can already be done, you can configure the `tickLabelRotation` props of each `Axis`
Check the example here, go to the `knobs` tab on the right panel and tweak the label rotation sliders: https://elastic.github.io/elastic-charts/?selectedKind=Axis&selectedStory=tick%20label%20rotation&full=0&addons=1&stories=1&panelRight=1&addonPanel=storybooks%2Fstorybook-addon-knobs
