### ISSUE TITLE
Format timestamp x-axis labels 

### ISSUE THREAD

**Issue by AlonaNadler** [elastic/elastic-charts#70]
Currently, the x-axis labels for timestamp shows full dates for more than 24 hours, it will be helpful to allow more formatting, examples:
When looking at a month show only the day (1-30)
When trying to compare weeks, the timestamp will be able to be in the context of weeks,  show the day of the week instead of the full date (Sunday-Sutarday)
With these options, users will be able to switch the format based on what they are analyzing,

**Comment by markov00** [comment]
You are already able to do so: each `Axis` component has the `tickFormat` props to change the format of the axis labels. We provide a simplified formatter for date, but the user/dev can use their preferred format here.
