### ISSUE TITLE
Make legend in charts selectable

### ISSUE THREAD

**Issue by timroes** [elastic/elastic-charts#710]
We currently use `user-select: none` on the legend in elastic charts. I've heard from users, that they would like to select the element items to copy and paste (e.g. there is a legend of ip addresses). I think it's worth discussing if the use-case of copying values from the legend wouldn't be worth keeping the legend selectable.

**Comment by archon810** [comment]
I'm one such user. I had to resort to using this extension to override this for now https://chrome.google.com/webstore/detail/absolute-enable-right-cli/jdocbkpgdakpekjlhemmfcncgdjeiika.

Before finding this solution, I also resorted to using tables for IP lists. I can easily copy from tables without any hacks.

**Comment by nickofthyme** [comment]
That a reasonable ask. I believe we added that because they are typically clickable and clicking them twice would tend to highlight all legend items. But this is purely cosmetic and we can change this if desired.

**Comment by unixsurfer** [comment]
It is very common for system engineers to select a certain legend and paste it into ssh cmd for instance. During an incident for instance, this is what we need to do most of the time. 
Currently, the only way I know to workaround this limitation is to open develop mode in the browser and find the value of the legend from there.

**Comment by markov00** [comment]
As described in chat, one possible way to solve this is to add an action to copy the legend item text through a contextual menu. We have a task about redesign the legend that will take in consideration also a better way to select the text and a way to display fully the text on the legend

**Comment by unixsurfer** [comment]
> As described in chat, one possible way to solve this is to add an action to copy the legend item text through a contextual menu. We have a task about redesign the legend that will take in consideration also a better way to select the text and a way to display fully the text on the legend

I am fine with this approach. Thank you.

**Comment by archon810** [comment]
That sounds good. The action can appear on hover to about cluttering the UI.
