### ISSUE TITLE
Small multiples aka liteFields integration into charts

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#735]
Start the liteFields integration into chart to include the small multiple feature like it's available for Kibana Visualize Editor: split charts by row/column.

### Where
`liteFields` should live, at the moment, between the Chart Specs/Configuration and the  chart rendering functions, it should:
- be the data source for each trellis, also on a single chart use case
- provide the width/height specific for each trellis
- provide the order/position of each trellis on the grid

### How
A few possible way to integrate the `liteFields`:
- move the `data` out from the single `SeriesSpecs` into its own specific component something like `<Data />` that starts bringing some data transformation concepts layer into chart library. 
- keep the `data` inside the `SeriesSpecs`: `liteFields` could take the data from the `SpecSeries` and then process that and brings that back to each chart

In both cases we need to:
- detach the data processing from the specs and connect to the `liteFields` output
- detach the width/height container/parent dimensions from the main parent dimensions and attach it to the `liteFields` (axis dimension is no more needed to compute the internal data representation)
- detach the axis dimension calculation (axis defined as a decoupled chart type)
- detach the legend dimension calculation (legend defined as a decoupled chart type)

### Open questions
1) how do we want to handle the small multiples? as a set of separate charts rendering? 
2) how do we want to handle the tooltip? are we going to synch them across these charts?

**Comment by nickofthyme** [comment]
I think this could be a great use for a redux registry of charts. There could be a distinction between a small multiple and a different `<Chart />` element altogether. But each `<Chart />` or small multiple can register to a shared store. This could also make sharing data across small multiples easier and treat the data as a _first class citizen_.

**Comment by markov00** [comment]
Closing as the small multiple is already integrated without liteFields at the moment. liteFields will replace the provided implementation
