### ISSUE TITLE
Can't get graph to render

### ISSUE THREAD

**Issue by ffknob** [elastic/elastic-charts#747]
**Describe the bug**
I can't get my graph to render. I've tried to simplify every aspect of it, but still no results. I mean, the DOM gets updated, but it is like the graph never receives it's data...

I think I'm facing some issue with my React app, but I just want to check with you what would make chart status `render-complete` to true.

Funny thing is, in the codepen below everything works fine...

**To Reproduce**
Take a look at...

1. This issue I've opened: https://github.com/elastic/elastic-charts/issues/720
2. This working codepen @nickofthyme had provided: https://codesandbox.io/s/epic-lehmann-4idwx?file=/src/App.tsx
3. The appropriate file in my project: https://github.com/ffknob/elastic-apm-demo/blob/master/app/frontend/src/Simulation/components/Results/Stats/SimulationStatsGraph.tsx

**Expected behaviour**
Graph rendered.

**Screenshots**
![Bildschirmfoto vom 2020-07-09 14-57-00](https://user-images.githubusercontent.com/23581855/87073885-75c13a00-c1f4-11ea-8e59-00e3daad5750.png)

**Version (please complete the following information):**
OS: Linux
Browser: Chrome
Elastic Charts: 19.8.1

**Additional context**
Initially discussed in https://github.com/elastic/elastic-charts/issues/720 (there was another error then, which was solved, but the no-rendering result is still the same)

**Errors in browser console**
None.

**Comment by markov00** [comment]
Hey @ffknob, thanks for submitting this.
From what I can see there shouldn't be any issue with the chart configuration, everything seems legit.
The only thing that I see that could be an issue is the parent width, the chart is using a 100% width but if the parent doesn't have a valid width the chart will not render.
Could you please check with the inspector the computed width of the `echChart` div?
You can also quickly try to add a fixed width on the chart like this to test if it renders
```
 <Chart size={{ height: 200, width: 400 }}>
```

**Comment by ffknob** [comment]
> Hey @ffknob, thanks for submitting this.
> From what I can see there shouldn't be any issue with the chart configuration, everything seems legit.
> The only thing that I see that could be an issue is the parent width, the chart is using a 100% width but if the parent doesn't have a valid width the chart will not render.
> Could you please check with the inspector the computed width of the `echChart` div?
> You can also quickly try to add a fixed width on the chart like this to test if it renders
> 
> ```
>  <Chart size={{ height: 200, width: 400 }}>
> ```

hi @markov00 

thank's for taking the time.

Tryied your suggestion but unfortunatelly it didn't work. The computed `ehcChart`'s height and width are set appropriately, as you can see in the image below.

![Bildschirmfoto vom 2020-07-10 10-05-02](https://user-images.githubusercontent.com/23581855/87157636-eddf3c80-c294-11ea-9e3e-a24f5b994858.png)

I am no React expert, but I think it might have something to do with React's rendering cycle, I don't know, I saw https://github.com/elastic/elastic-charts/blob/7d91d8f9ee1b3262c772245c6b865147bccf4a3c/src/components/chart_status.tsx#L44 and that gave this feeling...

By the way, couldn't find where in the lib the state's `chartRendered` and `chartRenderedCount` get updated. Searching the repo por "chartRenderedCount" only shows its declaration:

https://github.com/elastic/elastic-charts/search?q=chartRenderedCount&unscoped_q=chartRenderedCount

So, where would I find something like `state.chartRendered = true` and `state.chartRenderedCount++`?
I'm trying to pinpoint where the lib decides that the chart was rendered and see which conditions are taking in account.

**Comment by markov00** [comment]
the rendering status as the rendering count is something is updated after we effectively render something on the screen, and only in that case. For example if you take a look at this: https://elastic.github.io/elastic-charts/?path=/story/bar-chart--basic after rendering on the canvas element it will update the count and the status.
From your screenshot, I can see that probably you are missing the styling for the chart, have you imported the css as written on the [wiki](https://github.com/elastic/elastic-charts/blob/master/wiki/consuming.md)  and shown also on the codesandbox?
```
import "@elastic/charts/dist/theme_light.css";
```

**Comment by ffknob** [comment]
> the rendering status as the rendering count is something is updated after we effectively render something on the screen, and only in that case. For example if you take a look at this: https://elastic.github.io/elastic-charts/?path=/story/bar-chart--basic after rendering on the canvas element it will update the count and the status.
> From your screenshot, I can see that probably you are missing the styling for the chart, have you imported the css as written on the [wiki](https://github.com/elastic/elastic-charts/blob/master/wiki/consuming.md) and shown also on the codesandbox?
> 
> ```
> import "@elastic/charts/dist/theme_light.css";
> ```

I most certainly did not. I now you have helped me to solve an issue with which I've being fighting for the past weeks:

![Bildschirmfoto vom 2020-07-10 10-32-38](https://user-images.githubusercontent.com/23581855/87160074-becaca00-c298-11ea-8d08-99b9ecc8e969.png)

Graph finally rendered!

To be honest with you I didn't even knew about the consuming wiki page (l now know the it is listed in the repo's README). The only resources I knew about were the section in EUI's documentation, the live styling guide and the README (ok, which contained a link to the comsuption page).

Thank you very much @markov00

**Comment by markov00** [comment]
No problem, you are welcome
I'm happy it worked in the end

**Comment by realvictorprm** [comment]
currently can't get it to render inside a ElasticUI flex group :(

**Comment by nickofthyme** [comment]
@realvictorprm can you reproduce this issue here https://codesandbox.io/s/elasticcharts-playground-puj4y

**Comment by realvictorprm** [comment]
Turns out that happened because the flex box I was using was misconfigured
