### ISSUE TITLE
Inplace editing for axis titles

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#753]
**Is your feature request related to a problem? Please describe.**
When a user wants to change the axis titles on a rendered chart, the most straightforward way of doing so would be to click or double click the actual rendered axis title in the chart and being able to edit it.

**Describe the solution you'd like**
 To make editing charts as easy as possible for the user, being able to provide a consumer-controlled editor component for axis titles which is rendered on a given action (probably double click or focusing the label and hitting enter) would be really nice.

Other tools to this as well, for example
![axisedit](https://user-images.githubusercontent.com/1508364/87666391-d5759300-c768-11ea-87f9-78fa9c93d6e2.gif)

**Describe alternatives you've considered**
Of course it's possible to put the UI for axis titles elsewhere, put making this connection is harder as it should be for the user.

**Additional context**
https://github.com/elastic/kibana/pull/71829#issuecomment-658935909

**Kibana Cross Issues**
Related: https://github.com/elastic/kibana/issues/68315

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by flash1293** [comment]
Maybe adding to this - I think integration into Kibana would be easiest if the editor component is controlled by the caller, not `elastic-charts` itself. This way we can also show additional controls.

**Comment by markov00** [comment]
Closing this because it's not planned to be resolved in the foreseeable future. It will be tracked in our Icebox and will be re-opened if our priorities change. Feel free to re-open if you think it should be melted sooner.
