### ISSUE TITLE
Bars rendered on top of each other when using separate axes

### ISSUE THREAD

**Issue by flash1293** [elastic/elastic-charts#759]
**Describe the bug**
When a two series bar chart is using two separate y axes, the bars are rendered on  top of each  other. When using a single axis, they are rendered next to each other as expected.

**To Reproduce**
Working with a single axis: https://codesandbox.io/s/naughty-sara-okq4f
Not working with two axes:  https://codesandbox.io/s/elated-newton-luvxc

**Expected behaviour**
The bars should still be rendered side by side (it also seems like there is horizontal space reserved for them)

**Screenshots**
Single axis
<img width="473" alt="Screenshot 2020-07-22 at 18 00 26" src="https://user-images.githubusercontent.com/1508364/88199522-41626a80-cc45-11ea-837a-afb46369e020.png">

Two axes - you can see the blue bar hiding the green one
<img width="521" alt="Screenshot 2020-07-22 at 17 59 43" src="https://user-images.githubusercontent.com/1508364/88199518-3f98a700-cc45-11ea-942e-8c8518afe563.png">

**Version (please complete the following information):**
 - OS: macos
 - Browser: rChrome
 - Elastic Charts: 19.7.0

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/72889

**Comment by mbondyra** [comment]
Just to add to this, it doesn't happen for date histogram.
