### ISSUE TITLE
Short labels not show when using legend actions

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#773]
**Describe the bug**
When using legend actions with labels that do not reach the max legend width, the width of the action itself is not accounted for causing the label to be poorly truncated.

**Expected behaviour**
Legend should adjust width when legend actions are available.

**Screenshots**
![image](https://user-images.githubusercontent.com/19007109/88968581-257a4c80-d275-11ea-83bf-498b79103c45.png)

**Version (please complete the following information):**
 - Elastic Charts: all

**Comment by nickofthyme** [comment]
@markov00 This can be prevented using a `spacingBuffer`, something like below, where `20` is the width of the passed `LegendAction` component.

```tsx
<Settings
  theme={{
    legend: {
      spacingBuffer: 20,
    },
  }}
/>
```

The alternative would be to render the component to the dom before but that's not ideal. We could also add an input for the legend action width and if not provided measure the dom element.

What are your thoughts?

**Comment by markov00** [comment]
What if for the moment we limit the Action icon to a specific width/height? from the look and feel I think it will be better to avoid having the user to add any type of element there. What we want is just an icon as a call to action.
With the legend redesign, this can change to accommodate a completely customized legend

**Comment by nickofthyme** [comment]
Added action size constraint here fda6d02
