### ISSUE TITLE
Update UI for legend item interactions

### ISSUE THREAD

**Issue by emmacunningham** [elastic/elastic-charts#79]
**Is your feature request related to a problem? Please describe.**
See discussions from other issues/PRs:
https://github.com/elastic/elastic-charts/issues/25#issuecomment-463898838
https://github.com/elastic/elastic-charts/pull/51

**Describe the solution you'd like**
Would like to settle on what the UI for the legend items interactions should be.  This would cover:

- [x] How to handle the color picker (in current Kibana, it is opened in the same panel as the +/- buttons for removing/focusing a data series, but initial feedback was that this should be independent of that panel and open up just by click on the dot)
- [x] How to handle chart internal data series visibility toggling.  This is currently not a feature in Kibana, but the idea is that separate from actual removal/focus of the data for an actual series (i.e. what currently happens when you click +/- in Kibana), there should be a way to keep the data for a series but not render it within the chart.  This includes:
  * How to show/hide a series within the context of other series being visible (e.g. if I have series a, b, c; I want to toggle the visibility of a while keeping b & c visible)
  * How to show/hide a series individually (which also toggles the visibility of the other series); an example of this is say I have series a, b, c, I want to toggle showing only a (making b & c not visible) and showing everything but a (making b & c visible).
- [x] How to handle chart external data series filtering.  This is currently the functionality of the +/- buttons in Kibana.  The new chart library is agnostic to what actually happens on these events, but it is a way for an application to bind some custom functionality to these interactions so that when a user interacts in these ways, the data for identifying the series gets passed to the custom listeners which can define their own behaviors, e.g. a new query with the values passed to the listener as a filter.

**Describe alternatives you've considered**
See the links in the first section for some options discussed and current implementation.

**Additional context**

**Kibana Cross Issues**

**Checklist**

- [x] this request is checked against already exist requests
- ~[] every related Kibana issue is listed under `Kibana Cross Issues` list~
- ~[] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present~

**Comment by emmacunningham** [comment]
Notes from our bi-weekly sync today:
- add title attributes to legend title items
- legend item should be: [color dot] [title] [button to expand context menu w/ options]
  - color dot functionality will stay as is
  - show/hide series on legend title click (currently on eye icon next to title; this icon will go away)
  - add button next to title which will toggle open/close of context menu with +/- buttons and optionally other items
- instead of directly importing EUI components, instead we will have downstream consumer of the library instead pass the components into the legend themselves.  (they can also then pass in their own items into the context menu)

**Comment by emmacunningham** [comment]
Currently the display value on horizontal legends is spaced incorrectly as below:

![image](https://user-images.githubusercontent.com/452850/55889333-c9625500-5b65-11e9-8c8c-ab606ccdc59a.png)

**Comment by nickofthyme** [comment]
FYI the comment above about spacing has been fixed

**Comment by markov00** [comment]
closing this as the linked legend redesign issue already covers it
