### ISSUE TITLE
Value label is printed out with bad spacing in horizontal bar charts with isValueContainedInElement flag enabled

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#791]
**Describe the bug**
In an horizontal bar chart, there's a special logic to handle value labels for small bars.
In particular when value labels are rendered with an offset and the `isValueContainedInElement` is enabled the label gets a strange spacing.

**To Reproduce**
1. Go to 'Bar Chart - with value label'
2. Click on 'chart rotation' => 90 deg
3. Hide `a` and `b` series, leaving only the `bar` series active
3. Enable the `contain value label within bar element` option
4. See the 0.25 label break 💥 

**Expected behaviour**
The 0.25 label should be rendered with the correct spacing

**Screenshots**

Correct rendering without the `isValueContainedInElement` flag enabled:

<img width="1241" alt="Screenshot 2020-08-24 at 11 43 11" src="https://user-images.githubusercontent.com/924948/91030693-d7e8c980-e5ff-11ea-83aa-f170d1db5330.png">

Wrong rendering with the `isValueContainedInElement` enabled:

<img width="1235" alt="Screenshot 2020-08-24 at 11 43 18" src="https://user-images.githubusercontent.com/924948/91030711-dfa86e00-e5ff-11ea-8220-71b9bb935fe0.png">

Interestingly having a combination of other series may or may not kick in the bug: the bug is preset if any single series is disabled, but it disappear when all series are shown.

<img width="1241" alt="Screenshot 2020-08-24 at 11 48 05" src="https://user-images.githubusercontent.com/924948/91030887-19797480-e600-11ea-99d0-e56c1d128f71.png">

<img width="1246" alt="Screenshot 2020-08-24 at 11 47 59" src="https://user-images.githubusercontent.com/924948/91030898-1da59200-e600-11ea-8462-cf948f972879.png">

**Version (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome: 84.0.4147.135
 - Elastic Charts: 21.0.1

**Errors in browser console**
No errors

**Comment by markov00** [comment]
The `isValueContainedInElement` feature was deprecated in #1233
