### ISSUE TITLE
Sort DataSeries

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#795]
**Is your feature request related to a problem? Please describe.**
We should add the ability to sort every DataSeries created due to a splitAccessor or due to multiple specs ids.
Different sorting order can be applied to rendering, tooltip, legend.

**Describe the solution you'd like**
A first-class component should be built to handle such sorting. Its `id` can be used inside other specific props to reuse the same sorting in multiple places.
```tsx
// sort the tooltip values by specId alphabetically ascenting
<Sort
  id="tooltipOrder"
  by={(spec: Spec, splitAccessorValues: string|number[], datum: Datum ) => {
    return [spec.id];
  }}
  order={['alphaAsc']}
/>
<Tooltip
order="tooltipOrder"
/>

// sort legend items: by specId alphabetically ascending, then by split accessor value numerically descending
<Sort
  id="legendOrder"
  by={(spec: Spec, splitAccessorValues: string|number[], datum: Datum ) => {
    return [spec.id, ...splitAccessorValues];
  }}
  order={['alphaAsc', 'numDesc']}
/>
<Legend
...
order="legendOrder"
/>

// sorting rendering of bars: first stacked series then non stacked series by split accessors values
<Sort
  id="renderingOrder"
  by={(spec: Spec, splitAccessorValues: string|number[], datum: Datum ) => {
    const stackKey = spec.isStacked ? 'A' : 'B';
    const stackKey = spec.isStacked ? 'A' : 'B';
    return [[stackKey, ...splitAccessorValues].join('-')];
  }}
  order={['alphaAsc']}
/>
<BarSeries
...
renderingOrder="renderingOrder"
/>
```

**Describe alternatives you've considered**
Implement this mechanism for each specific component can be too difficult to maintain in the long run and difficult to reuse across multiple chart elements

**Additional context**
Kibana vislib has a different rendering order than the one we currently use, the same happens for TSVB

- related to https://github.com/elastic/elastic-charts/issues/303 having the same order between rendering, tooltip and legend
- related to https://github.com/elastic/elastic-charts/issues/674 where the rendering order describe what element is rendered on top of each other

**Comment by nickofthyme** [comment]
Sort should include `SeriesIdentifier` and if available the given value (per https://github.com/elastic/kibana/issues/46466).

**Comment by nickofthyme** [comment]
@markov00 is this closed with #924?

**Comment by markov00** [comment]
@nickofthyme the #924 doesn't cover the case requested in TSVB where we need to sort the legend by the extra value.
There is also another reason to keep this open: the API is not exposed yet

**Comment by nickofthyme** [comment]
Oh yeah I forgot it's a secret 🤫

**Comment by markov00** [comment]
@nickofthyme probably we can close also this one

**Comment by nickofthyme** [comment]
Yeah
