### ISSUE TITLE
Add customTooltipDetails option in Partition chart

### ISSUE THREAD

**Issue by shahzad31** [elastic/elastic-charts#809]
Partition chart doesn't support customTooltipDetails or deprecated renderTooltip option,

in Kibana Client Side Monitoring app we would like to customise tool tips but there is no option in partition chart 

Example as 

Chrome mobile:
Count 33
% of impressions 37.6%

Kibana issue https://github.com/elastic/kibana/issues/76953

**Comment by monfera** [comment]
Rollout of https://github.com/elastic/elastic-charts/pull/727

**Comment by nickofthyme** [comment]
@shahzad31 After digging into this further we _DO_ in fact support this functionality as of `@elastic/charts@19.4.0`. It was added in https://github.com/elastic/elastic-charts/pull/651.

The API is the same across all chart types accessed via `Settings.tooltip`. Something like...

```tsx
<Chart>
  <Settings tooltip={{ customTooltip: () => <div>My Tooltip</div> }} />
  {/* ... */}
</Chart>
```

I put up a PR to add an example of this to our storybook for partition charts here https://github.com/elastic/elastic-charts/pull/818
