### ISSUE TITLE
Click on point on chart so that tooltip stay visible and "sticky" at where mouse clicks

### ISSUE THREAD

**Issue by yizheliu-amazon** [elastic/elastic-charts#815]
**Is your feature request related to a problem? Please describe.**
Not related to a problem. 

**Describe the solution you'd like**
I want to have a feature that allows user to click on any point of line/bar in the chart so that the tooltip can stay visible and "sticky" at where mouse clicks. 

**Describe alternatives you've considered**
I have thought about manually setting coordinate of Tooltip when click event is triggered, but it looks like `TooltipProps` does not expose position or coordinate attribute to user, and for now Tooltip position is only from `GlobalChartState`, aka position of pointer or mouse.

**Additional context**
N/A

**Kibana Cross Issues**
N/A

**Checklist**

Delete any items that are not applicable to this feature request.

- [X] this request is checked against already exist requests

**Comment by markov00** [comment]
Thank you @yizheliu-amazon for the request, seems an interesting and useful enhancement to add.
We currently have a full roadmap for the next releases so this can take time to implement, in the meantime every external PR that solves that is very welcome

**Comment by markov00** [comment]
Done in #1782
