### ISSUE TITLE
Use normalized path on storybook circular dependency plugin

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#826]
**Describe the bug**
When running storybook on window, the circular dependency plugin has a check to avoid checking circular dependencies inside `node_modules`, but this path check only works on unix-like systems

**To Reproduce**
1. Use a window machine
2. run `yarn start`
3. See error

**Expected behaviour**
We should normalize the path check to avoid system-dependent folders

**Screenshots**
![image](https://user-images.githubusercontent.com/1421091/93452077-473c9b00-f8d8-11ea-8d0f-fb49d8314056.png)

**Version (please complete the following information):**
 - OS: window
 - Elastic Charts: master

**Workaround**
remove the `CircularDependencyPlugin` and its configuration from the `.storybook/webpack.config.js` file

**Comment by nickofthyme** [comment]
Would it be possible to just avoid running on windows machines? I ran into a circular import yesterday so would be nice to keep it if possible.

**Comment by markov00** [comment]
you mean avoid running the circular dependency plugin on window machine? I think so, probably the fix takes the same time to deliver

**Comment by markov00** [comment]
Near zero Windows developer right now
