### ISSUE TITLE
Bar Series doesn't displays single data point

### ISSUE THREAD

**Issue by shahzad31** [elastic/elastic-charts#836]
**Describe the bug**
Bar Series doesn't displays single data point 
here is an example from code sandbox 

https://codesandbox.io/s/jolly-colden-rm5qu?file=/src/App.tsx

if i change data to 

`          data={[[1599066390701, 10], [20]]}
`

then it does displays single bar from first entry.

Here is the code

```
      <Chart size={{ width: "100%", height: 400 }} className="story-chart">
        <Settings xDomain={{ min: 1599036835802, max: 1599235986805 }} />
        <Axis id="bottom" position={Position.Bottom} />

        <BarSeries
          id={"downChart"}
          name="overall"
          timeZone="local"
          xAccessor={0}
          xScaleType={ScaleType.Time}
          yAccessors={[1]}
          yScaleType={ScaleType.Linear}
          data={[[1599066390701, 10], [20]]}
        />
      </Chart>
```

**Comment by nickofthyme** [comment]
Thanks to @mbondyra for the re-explanation.

single bars require a set `minInterval` value with custom `xDomain`.

In the words of the great @markov00 

> Problem: we cannot render the width of the bar because we cannot calculate interval.
At the moment, to render a bar chart automatically we compute the minimum x interval between our data points to know exactly how much space a bar can take along the x axis.
For a single data point it cannot be done. 
BUT we provide a parameter called minInterval in the xDomain, currently expressed in milliseconds if you are using it for a x time scale. This parameter is the minimum number of milliseconds between consecutive buckets. 
> * fine print: Note that this is a static value and doesn’t take in consideration any leap second, daylight savings, so for intervals that spans between those two values, it has to be computed as the minimum in terms of milliseconds between consecutive buckets.

Working example here:
https://codesandbox.io/s/flamboyant-tdd-b0hzt?file=/src/App.tsx

![image](https://user-images.githubusercontent.com/19007109/94601089-954a8a80-0258-11eb-9c00-6acbe80ba475.png)
