### ISSUE TITLE
When the difference between y-axis values are too high the bar chart isn't shown.

### ISSUE THREAD

**Issue by cauemarcondes** [elastic/elastic-charts#874]
**Describe the bug**
A bucket is not shown when the difference between the y-axis is too big.

**To Reproduce**
1. Checkout my branch https://github.com/elastic/kibana/pull/80298
2. Start kibana
3. Navigate to APM
4. Select any service
5. Select any transaction
6. Check the `Transactions duration distribution` chart.

**Expected behaviour**
The chart should show a bucket even when the value is small.

**Screenshots**
<img width="1344" alt="Screenshot 2020-10-19 at 16 25 31" src="https://user-images.githubusercontent.com/55978943/96471885-1da4c580-1230-11eb-86b0-32d6a250c43e.png">

<img width="925" alt="Screenshot 2020-10-19 at 16 25 58" src="https://user-images.githubusercontent.com/55978943/96471900-20071f80-1230-11eb-9f7a-97a452b18484.png">

**Version (please complete the following information):**
 - Elastic Charts: 23.2.1

**Kibana Cross Issues**
https://github.com/elastic/kibana/pull/80298

**Comment by nickofthyme** [comment]
@cauemarcondes I think using the `minBarHeight` might solve your issue. This applies a minimum bar height in px for non-zero  and non-null values. See https://github.com/elastic/elastic-charts/pull/443.

Something like...

```tsx
<BarSeries minBarHeight={2} /* other props */ />
```

**Comment by cauemarcondes** [comment]
That's what I needed. Thanks for the fast reply @nickofthyme

**Comment by nickofthyme** [comment]
Perfect, you are most welcome!
