### ISSUE TITLE
xAccessor offset for timeseries data

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#885]
**Is your feature request related to a problem? Please describe.**
In timelion and APM, there are use cases where we want to display two timeseries with a given offset (i.e. a day, a week). Having a way to facilitate this kind of chart would be nice.

![image](https://user-images.githubusercontent.com/19007109/97718079-7cb9d400-1a93-11eb-9ea2-6775aed21d14.png)

**Describe the solution you'd like**
An offset value on the series, some thing like `xOffset`, which will factor in this offset when rendering the geometry but use the original value for tooltip and interactions.

> I don't know if this should be should be for non-time charts

**Describe alternatives you've considered**
Creating two series with the offset series matching the x values of the non-offset series. Then for the tooltip and interactions, inverting the offset to get the true value. This is less than ideal as this requires consumer to duplicate offset logic in many places.

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/81147

https://github.com/elastic/kibana/pull/98781 - time shift pr in Lens

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by monfera** [comment]
It's in the class of lagging indicators, of which a specific time offset is only one case. There are other ones eg. 
- period difference (called "derivation" in Kibana)
- windowed moving average
- EWMA

Also, other indicators may include not just lookback but also lookahead, eg.
- LOESS or LOWESS smoothing
- radial basis function network (RBNF)

It'd be best to figure out the common approach and implement the solution within such an extensible indicator architecture

**Comment by nickofthyme** [comment]
@monfera any ideas on what the api would look like for this?

**Comment by markov00** [comment]
The correlated issues are implemented/fixed in Kibana. 
The custom solution for now is to pass a shifted dataset and use a custom tooltip to display the shifted time stamp.
