### ISSUE TITLE
Rotated axis labels are misaligned

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#888]
**Describe the bug**
When rotating a label on the axis, seems that the label is not correctly rotated around the axis tick position, but it's misaligned

**Expected behaviour**
Each label should be aligned at their tick when rotating

**Screenshots**
the 0 label in this example seems a bit off
<img width="126" alt="Screenshot 2020-11-04 at 16 23 25" src="https://user-images.githubusercontent.com/1421091/98132040-3d88ea00-1ebc-11eb-999b-83ae185e4592.png">

**Version (please complete the following information):**
 - Elastic Charts: 24

**Additional context**
Detected when testing the vislib replacement PR in Kibana

**Errors in browser console**
N/A

**Comment by nickofthyme** [comment]
Is this using right alignment of the labels?

**Comment by markov00** [comment]
Seems to be the default one, when using the`Near` alignment

**Comment by nickofthyme** [comment]
Yeah, it could be that the rotation is not accounting for the rotation on `Near` and `Far` options.

**Comment by markov00** [comment]
It seems to be fixed
