### ISSUE TITLE
Improve popper.js performance with removing debounce.

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#909]
**Is your feature request related to a problem? Please describe.**
Popper.js has a debounce on the `createPopper` method that may limit the performance of the tooltip with composite and other chart types. This debounce limits this method to _run at most once-per-tick_ which may be unacceptable performance.

**Describe the solution you'd like**
Investigate the removal of the debounce to replace with our own debounce flag to improve performance when not needed.

See https://github.com/popperjs/popper-core/issues/1194

**Comment by monfera** [comment]
Thanks @nickofthyme. The goal is, consistent, synchronous repositioning of the `popper.js`-positioned tooltip AND whatever else moves together with the mouse, eg. the bin highlight (grey rectangle). Right now, if I swipe from left to right, the bin highlight is "glued" to the mouse X, while the tooltip is less in sync with the mouse. So the tooltip and the bin highlight can disturbingly separate from one another, esp. if there's some lag. And it's different when sweeping from left to right and right to left. Happens on current `elastic-charts` [too](https://elastic.github.io/elastic-charts/?path=/story/bar-chart--time-clustered-using-various-specs), more visible on less powerful hardware and/or more contrasty bin highlight, as the current one is not too different from the background.

It might even be the case that we want to debounce, but in a more controllable way, eg. the bin highlight and the tooltip together, ie. outside `popper.js`

**Comment by nickofthyme** [comment]
Relates to https://github.com/elastic/elastic-charts/issues/615

**Comment by markov00** [comment]
@nickofthyme can we close this after #2309 and #2270?

**Comment by nickofthyme** [comment]
Yeah I think so, didn't even remember creating this issue.
