### ISSUE TITLE
Partition nested legends are not depicted well when there are same values per metric

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#918]
**Describe the bug**
I have created a Lens pie chart with two layers. While the pie chart is rendered correctly I can see on the legend bar (with the nested switch on) that the nested legends are not displayed correctly. Some of the values are repeated with a color of a different series.

<img width="1359" alt="Screenshot 2020-11-25 at 10 54 56 AM" src="https://user-images.githubusercontent.com/17003240/100205414-c4564300-2f0d-11eb-9635-52c0b1879ee6.png">

Here the problem is more obvious:
<img width="1356" alt="Screenshot 2020-11-25 at 11 19 57 AM" src="https://user-images.githubusercontent.com/17003240/100207362-2e6fe780-2f10-11eb-8fb8-814ac9231553.png">

**To Reproduce**
1. Go to Kibana Lens
2. Select the `kibana_sample_data_logs` dataset 
3. Drag and drop the machine.os.keyword and the memory fields
4. Switch on the nested legend from the top menu
5. Check that the legends are not displayed correctly

**Expected behaviour**
The nested legends should appear without duplicates from other series.

**Additional context**
I have also found out this problem on migrating the vislib pie chart to the es-charts one.

**Kibana cross-issue**
https://github.com/elastic/kibana/issues/84307

**Comment by flash1293** [comment]
I can reproduce this outside of Lens as well: https://codesandbox.io/s/little-leaf-05w34?file=/src/App.tsx

**Comment by monfera** [comment]
Note to self, check the condition Marco references here: https://github.com/elastic/elastic-charts/pull/939#issuecomment-741731819

**Comment by monfera** [comment]
Fixed by https://github.com/elastic/elastic-charts/pull/947
