### ISSUE TITLE
Tooltip: fixed position instead of following mouse and improved line indicator

### ISSUE THREAD

**Issue by sqren** [elastic/elastic-charts#921]
APM is in the process of migrating from react-vis to Elastic Charts, and while Elastic Charts is getting a lot of things right, I think two small changes could improve the UX:
 
- [ ]  The tooltip should be fixed on the y-axis and only move along along the x-axis. Having it move in both direction is distracting and doesn't add anything
- [ ] As a user I expect to see the point on the line highlighted as I move long the x-axis. Unless it hit the exact spot wrt to both the y-axis and x-axis where the line is, it is not highlighted.

**Old charts (react-vis)**
![apm-old-charts](https://user-images.githubusercontent.com/209966/100233677-59673500-2f2a-11eb-9114-cacdf74f63ca.gif)

**New charts (Elastic Charts)**
![new-charts](https://user-images.githubusercontent.com/209966/100233897-9d5a3a00-2f2a-11eb-903b-6880e60a5e13.gif)

**Comment by formgeist** [comment]
Opened https://github.com/elastic/kibana/issues/98282 to track APM's adoption of this new enhancement 🎉
