### ISSUE TITLE
RectAnnotation markers or annotations outside axis

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#928]
**Describe the solution you'd like**
Some use cases require the annotation to be positioned outside the chart, to improve the chart readability without cluttering with overlapping elements and colors.

We should allow rendering rectangular annotations outside the chart area, for example right below the axis.

Current:
<img width="787" alt="Screenshot 2021-04-07 at 22 18 20" src="https://user-images.githubusercontent.com/1421091/113928506-352c3680-97ef-11eb-9118-85f19e5ecc34.png">

Desired:
<img width="788" alt="Screenshot 2021-04-07 at 22 19 48" src="https://user-images.githubusercontent.com/1421091/113928806-8ccaa200-97ef-11eb-94c8-fe18fc60e892.png">

**Describe alternatives you've considered**
For the implementation we can consider multiple alternatives or go in steps:
1. allow the user to specify a `marker` for `RectAnnotation`s: the marker can be placed below the annotation in the center, like for a line annotation. A `size` parameter representing the width of the annotation in pixel, can be passed to the marker component to size it.
- Add a configuration to allow specifying a `RectAnnotation` outside the "linked" axis (below, above the horizontal axis, or at the right/ left of the vertical axis), but this can subsequentially be a worm hole of requests/options and configurations.
- consider the annotation as a composable chart

**Additional context**

https://codesandbox.io/s/elastic-charts-playground-qs1jr?file=/src/timeseries.tsx

**Comment by sqren** [comment]
For visibility: this is needed for https://github.com/elastic/kibana/issues/96559 which is scheduled for 7.14 (I know, tight deadline).

**Comment by nickofthyme** [comment]
@sqren or @smith could you look at this implementation and let me know if that will suffice for your use case? Thanks

**Comment by sqren** [comment]
Thank you @nickofthyme . I'll defer to @smith since he has been working on this.

**Comment by smith** [comment]
@nickofthyme the implementation on #1207 looks like it fits what we need. cc @katrin-freihofner.
