### ISSUE TITLE
Small multiples for partitioning charts

### ISSUE THREAD

**Issue by stratoula** [elastic/elastic-charts#930]
**Is your feature request related to a problem? Please describe.**
As we are working on replacing the vislib pie chart to the elastic-charts one we have one feature request that is not currently provided and  has to do with the creation of small multiples. Specifically now on vislib the user can select to split the chart by rows or columns:

<img width="1932" alt="Screenshot 2020-12-02 at 4 30 23 PM" src="https://user-images.githubusercontent.com/17003240/100885812-bed39c80-34bb-11eb-802b-8dceafdb2ee4.png">

**Describe the solution you'd like**
We would like to have the same behavior if possible as is depicted on the screenshot above.

**Kibana Cross Issues**
Kibana issue that has to do with the vislib replacement https://github.com/elastic/kibana/issues/56143

**Checklist**

Delete any items that are not applicable to this feature request.

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by markov00** [comment]
closed by #1076 and #1094
