### ISSUE TITLE
[minor] chroma.js throws on 'transparent'

### ISSUE THREAD

**Issue by monfera** [elastic/elastic-charts#941]
**Describe the bug**
chroma.js throws an exception 

**To Reproduce**
1. Copy the `<Chart>` from https://codesandbox.io/s/little-leaf-05w34?file=/src/App.tsx into the Playground
1. Open dev tools, ensure "Pause on caught exceptions" is selected, and load the Playground
3. Error is thrown: `Error: unknown format: transparent`

**Expected behaviour**
No error thrown, handled or unhandled

**Version (please complete the following information):**
 - Elastic Charts: 24.3.0 or commit #7e4512bfc8d8a905bfbe60e72d50ec8bfc019334

**Comment by monfera** [comment]
...looks like it can't be cleanly solved, as `chroma.js`, regrettably, throws routinely. We should replace this library with something else, or our own, that doesn't throw with good input.

**Comment by nickofthyme** [comment]
Could we do a `try`/`catch` to eliminate the error?
