### ISSUE TITLE
Add option to show tooltip for empty buckets

### ISSUE THREAD

**Issue by formgeist** [elastic/elastic-charts#950]
# Summary

Related to https://github.com/elastic/kibana/issues/85793

It would be beneficial to have an option in the charts to always tooltip for instances where multiple charts are synced, but an individual chart instance cannot show a value because of an empty bucket in the data. In this case we'd like to show a custom tooltip message like "Metric: N/A" or similar.

![image](https://user-images.githubusercontent.com/4104278/102099179-5031ff80-3e28-11eb-8252-70d44543f643.png)

<details>
<summary>Example of current tooltip behaviour</summary>

![Kapture 2020-12-15 at 10 14 27](https://user-images.githubusercontent.com/4104278/102195060-612d5000-3ebe-11eb-933d-d8f320d4f5e7.gif)

</details>

**Comment by jpcarey** [comment]
I have a similar use case, where I've hidden the X Axis to try to fit into a table row. I'd like to still see the label tooltip to display the x value / date when the data is null.

Example grid:
![image](https://user-images.githubusercontent.com/5118470/110392754-acbb4a00-8026-11eb-9edc-b778dde77111.png)

Hover on item with a value:
![image](https://user-images.githubusercontent.com/5118470/110393184-5995c700-8027-11eb-8cb7-6d33f1aa3cd4.png)

Current hover where the value = null:
![image](https://user-images.githubusercontent.com/5118470/110393215-64505c00-8027-11eb-8c29-8213b1254d9c.png)
