### ISSUE TITLE
Improve VRTs speed

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#951]
**Context**
The current VRTs took several minutes to complete.
We have nearly 720 snapshots and our CI starts two parallel workers on nearly half of them and complete each of them in about 20 to 27 minutes.

The current snapshot library used is the [jest-image-snapshot](https://github.com/americanexpress/jest-image-snapshot)
At the beginning, I was thinking that we can solve this by just swapping the library with a more performant one like [jest-screenshot](https://github.com/Prior99/jest-screenshot)
that state the following:
> By utilizing native-image-diff instead of pixelmatch and node-libpng instead of pngjs the tests will run much faster than its competitors. ... This library is around 10x faster than jest-image-snapshot.

**Methodology**
I've done a quick review of the new library, and fixed a known issue on our side to correctly match our test file name pattern: https://github.com/markov00/jest-screenshot/commit/752642e43955e450f07b65280da746e36bc3c956

I've then compared the speed of both libraries putting logs between 3 major points in our code:
- on `loadElementFromURL` that loads the page from the URL
- on `screenshotDOMElement` that capture the Buffer image from the browser screen
- on `toMatchImageSnapshot` that compares the Buffer with the one already stored on the FS

**Findings**

At a first glance, both libraries look similar, with an average time per screenshot of 2.5 seconds but looking a bit more in detail:

- the `toMatchImageSnapshot` comparison function takes ~200ms for the current lib and ~4ms on the `jest-screenshot`. In the long run, with ~720 tests the benefit is quite high, near 2 minutes less to complete.
- most of the time is not spent on the screenshot test itself, nor on extracting the image from the browser (that took ~150ms and probably depends only on Puppeteer) but it’s spent on the page loading (~2 Seconds): the `loadElementFromURL` took every time nearly 2 minutes to return.

Cutting down the cost of loading the page to the minimum we can significantly speed up the CI and our testing.

**Proposed solution**
I'm pretty sure that the page load cost is caused by the heaviness of Storybook itself, I haven't checked that with precise measurement, but loading the storybook iframe page took every time 2 seconds to fully load.

One possible solution is to completely bypass Storybook, and use something like our playground as a proxy for every test.
A storybook example loaded through playground, at the moment, tooks nearly 400ms to fully load. An estimation of the speedup can be
- `jest-image-snapshot` (current lib): (2000ms + 200ms + 150ms) * 720 = 28.2 mins
- `jest-screenshot`: (400ms + 4ms + 150ms)*720 = 6.6 mins 
An potential increase of speed of ~4.5X

The drawback of this approach is:
- the Storybook-knobs values, used on some screenshot tests to change parameters through the browser URL are not working without Storybook. A proxy/mock to that library can probably be easily doable
- Each test should be loaded from the browser URL, a simple router needs to be implemented

If we can reduce the loading time and the Puppeteer image screenshot time we can have VRTs at the speed of unit testing or at least we can go very close to that

Few other improvements, at least of the CI is to:
- take advantage of multiple CPUs running a subset of tests locally in separate thread/process, probably doable when removing the `--runInBand` option of jest
- align each CI worker to run the same number of tests

**Comment by monfera** [comment]
Totally agree; wondering if there's a way to not even load any page, just flip through the specs, render, snapshot, discard the DOM root, move on to the next. Besides storybook, page loading itself has quite some overhead, and ideally the snapshot / compare is just a small extra, parallelizable (as in: can run outside the browser main thread) task, so images in theory could be generated as fast as the `elastic-charts` library can do the spec parse => render flow

**Comment by nickofthyme** [comment]
No longer applies after migrating VRT to playwright
