### ISSUE TITLE
Phase out some overly prescriptive code rules: `prefer-destructuring` for array and object

### ISSUE THREAD

**Issue by monfera** [elastic/elastic-charts#957]
I think
```
const [r0] = r;
```
is less preferable than
```
const r0 = r[0];
```
and even if not, it doesn't buy anything. Also, while we should [transition to ES2015](https://github.com/elastic/elastic-charts/issues/956), I don't see a reason for practically enforcing ES2015-only constructs, and currently, the resulting polyfill, where an ES5 construct exists which is often no worse and sometimes better.

I'm eager to learn if there's some justification. The rule description itself lists no benefits but points to clear drawbacks eg. when [indexing arrays](https://eslint.org/docs/rules/prefer-destructuring#when-not-to-use-it). I'm not fond of raising an info or warning for language constructs that seem perfectly legit, so such rules should ideally be activated upon shared conviction.

**Comment by nickofthyme** [comment]
I think overall destructuring (both arrays and objects) is more beneficial from a reading perspective. But admittedly, it does get in the way at times, especially when reassigning values from an array.

```ts
// good
const [first, second] = array;

// bad
const first = array[0];
const second = array[1];
```

**Comment by monfera** [comment]
I agree @nickofthyme and have no plans to discourage the array destructuring, which is often much nicer such as in your example. So my current takeaway is that the linter isn't quite able to judge when one is better than the other, and the developer or code reviewer can. If the linter can't know while we can work out OK usages in what has sometimes grey areas, it ideally isn't enforced one way or the other by the linter

**Comment by nickofthyme** [comment]
Yup agreed
