### ISSUE TITLE
Tooltip position is offset on cursor interaction and centered for synced tooltips

### ISSUE THREAD

**Issue by formgeist** [elastic/elastic-charts#966]
# Summary

When enabling tooltip synchronization on the charts, the tooltip on the active chart is positioned according to the configuration (adjacent to the vertical line), but the synced tooltips show on top of the vertical line not respecting the configuration.

The below screenshot can be reproduced on the APM Service overview page in Kibana 7.11 or master.

<img width="741" alt="Screenshot 2021-01-07 at 08 37 19" src="https://user-images.githubusercontent.com/4104278/103865842-17064b80-50c5-11eb-8ce4-7ef608eef54f.png">

**Comment by cyrille-leclerc** [comment]
Thanks @formgeist . cc @alex-fedotyev

**Comment by nickofthyme** [comment]
@formgeist Thanks for opening this issue.

The external tooltip `placement` can be set via the `externalPointerEvents.tooltip.placement` prop on `Settings` component.

```tsx
<Chart>
  <Settings
    onPointerUpdate={onPointerUpdate}
    externalPointerEvents={{
      tooltip: { placement: 'left' },
    }}
  />
</Chart>
```

Below notice the top tooltip placement change from _left_ to _right_ to _bottom_.

![Screen Recording 2021-01-07 at 10 52 AM](https://user-images.githubusercontent.com/19007109/103920357-d31c4200-50d6-11eb-84fb-5032e32606d7.gif)

See the storybook example [here](https://elastic.github.io/elastic-charts/?path=/story/interactions--cursor-update-action).

Let me know if this solves your problem.

> A current limitation of this is that the height of vertical placement is always at the top of the following chart.

**Comment by formgeist** [comment]
@nickofthyme Thanks for example and that worked! I've opened a PR to reconfigure the chart settings to set the tooltip placement differently https://github.com/elastic/kibana/pull/87729

**Comment by nickofthyme** [comment]
Perfect! No problem, glad to help.
