### ISSUE TITLE
[Legend] Legend dot Icon fixed id string breaks a11y tests

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#983]
**Describe the bug**
The Legend component is using the `DotIcon` underneath, which exposes a SVG component with a fixed id string: this leads to multiple DOM nodes with the same `id` value, which is a problem both in general and at a11y level.

Either remove the `id` (but it is probably used somewhere else) or assign a configurable/dynamic id to it.

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/bubble-chart-alpha--multiple (but any other viz with multiple series will work)
2. Execute this JS code in the console: `document.querySelectorAll('#dot-a').length`
3. Notice the result being > 1

**Expected behaviour**
Unique id used in the visualization DOM tree.

**Kibana Cross Issues**
[Kibana Lens issue](https://github.com/elastic/kibana/issues/88661)

**Checklist**

- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by nickofthyme** [comment]
I think this was fixed by https://github.com/elastic/elastic-charts/pull/973. Please confirm.

**Comment by dej611** [comment]
Oh sorry, didn't find #970 while searching. I guess it can be closed then 👍 
Waiting for the next release to close it on the Kibana side.
