### ISSUE TITLE
[Documentation Suggestions] 

### ISSUE THREAD

**Issue by rshen91** [elastic/elastic-charts#99]
1.  Add  Overview link under Goals section
I'm going through the readme and I think it might be useful to include in the [Goals](https://github.com/elastic/elastic-charts#goals) section a link to the overview from the [Wiki > Documentation > Overview](https://github.com/elastic/elastic-charts/blob/master/wiki/overview.md) section. 

2. Break up rendering Pipeline section in Overview 
[This](https://github.com/elastic/elastic-charts/blob/master/wiki/overview.md#rendering-pipeline) section was a little long and I think we can emphasize further the rendering components vs the state components. I'm thinking we might be able to just add a sub section breaking it up like so: 

> - part of this computation can also be processed server side or on a WebWorker.
> 
> ### Achieving the Rendering Pipeline
> 
> The rendering pipeline is achieved by revisiting the way a chart library is built. Instead of creating a chart library around a set of rendering components: bar series, axis etc., this new implementation decouples the specification of the chart from the rendering components.

... 

3. Dataset Domains definition
I think we might want to reword the first sentence in [here](https://github.com/elastic/elastic-charts/blob/master/wiki/overview.md#dataset-domains). I'm not sure if my phrasing is correct but I'm thinking something like: 
`Dataset domains are the extent the variable is related to a dataset`

4. Typos in overview 
- Line 164 can be changed to ```A chart can be fed with data in the following ways:```
- Line 167 can be changed to ```In this case the data arrays are merged together using the following rules```

5. Would it make sense in the readme potentially in the overview part or spanning off that to include a guide to the directory structure? Not sure if this would introduce more noise over clarity but I could see it being good to clearly lay out the plan for each directory etc. 

5. Include more information about storybook here? 
https://github.com/elastic/elastic-charts#development-environment
I'm adding this just because I got really hung up on knowing how to add an input element so I wanted to make sure not to forget. Looking at the documentation, this might be a good spot to elaborate:
```We use storybook to document API, edge-cases, and the usage of the library (HTML elements are used through storybook). A hosted version is available at https://elastic.github.io/elastic-charts.```

**Comment by markov00** [comment]
Hey @rshen91, this issue is quite old, I'm fine with all the points, but I don't think we should spend more time now on fixing 5 and 6. If in your spear time you want to open a PR to fix those it will be great
