### ISSUE TITLE
Snap cursor position with fit function is wrong

### ISSUE THREAD

**Issue by nickofthyme** [elastic/elastic-charts#990]
**Describe the bug**
When using a fit function where `null` and missing values are filled, the cursor will favor placement towards the left nearest point rather than halfway between the points.

**To Reproduce**
1. Go to https://elastic.github.io/elastic-charts/?path=/story/mixed-charts--fitting-functions-non-stacked-series
2. Hover over the __dark__ green areas, notice the cursor line snap positions
3. Hover over the __light__ green areas, notice the cursor line snap positions

**Expected behavior**
The cursor should jump to the nearest tick no matter if values are missing or `null`

**Screenshots**
![Screen Recording 2021-01-21 at 12 28 PM](https://user-images.githubusercontent.com/19007109/105396443-8318a180-5be5-11eb-94ca-b3f4a47753c2.gif)

Notice the cursor line position when hovers over the dark green areas vs when hovered over the light green areas. The pink lines illustrate the rough snapline/bifurcation of the logic.

**Comment by markov00** [comment]
https://user-images.githubusercontent.com/1421091/127317462-8894924e-e191-4e3b-bd41-972d8b854e65.mp4

Seems to be fixed in 33.0.2, not sure what was the commit that fixed it

**Comment by nickofthyme** [comment]
Nice!!
